/**
 * DEV_MOCK_LEADS
 * 
 * STRICT TEST FIXTURE:
 * - Only enabled when URL contains '?mockLeads=1' in development mode (import.meta.env.DEV).
 * - Never runs or bundles in production.
 * - Contains ONLY real schema fields that actual scanning produces (no fake job titles, no invented fields).
 * - Includes a mix of:
 *   - Leads with photos (local /avatars/*.jpg)
 *   - Leads WITHOUT photos (avatar: null, profilePhotoAvailable: false)
 *   - Business accounts (isBusiness: true, isVerified: true/false)
 *   - Standard active WhatsApp personal numbers
 *   - Realistic discovery timestamps
 */

export const DEV_MOCK_LEADS = [
  {
    number: '+13055581249',
    cleanNumber: '13055581249',
    formatted: '+1 (305) 558-1249',
    detectedCountry: 'US',
    isValidFormat: true,
    exists: true,
    avatar: '/avatars/marco.jpg',
    profilePhotoAvailable: true,
    isBusiness: true,
    isVerified: true,
    displayName: 'Apex Design & Co',
    verifiedName: 'Apex Design & Co',
    city: 'Miami',
    state: 'Florida',
    discoveredAt: Date.now() - 4000
  },
  {
    number: '+13055583892',
    cleanNumber: '13055583892',
    formatted: '+1 (305) 558-3892',
    detectedCountry: 'US',
    isValidFormat: true,
    exists: true,
    avatar: '/avatars/sofia.jpg',
    profilePhotoAvailable: true,
    isBusiness: false,
    isVerified: false,
    displayName: null,
    verifiedName: null,
    city: 'Miami',
    state: 'Florida',
    discoveredAt: Date.now() - 14000
  },
  {
    number: '+13055589124',
    cleanNumber: '13055589124',
    formatted: '+1 (305) 558-9124',
    detectedCountry: 'US',
    isValidFormat: true,
    exists: true,
    avatar: null, // Test fallback iOS silhouette
    profilePhotoAvailable: false,
    isBusiness: false,
    isVerified: false,
    displayName: null,
    verifiedName: null,
    city: 'Miami',
    state: 'Florida',
    discoveredAt: Date.now() - 28000
  },
  {
    number: '+13055584411',
    cleanNumber: '13055584411',
    formatted: '+1 (305) 558-4411',
    detectedCountry: 'US',
    isValidFormat: true,
    exists: true,
    avatar: '/avatars/tomas.jpg',
    profilePhotoAvailable: true,
    isBusiness: true,
    isVerified: false,
    displayName: null,
    verifiedName: null,
    city: 'Miami',
    state: 'Florida',
    discoveredAt: Date.now() - 45000
  },
  {
    number: '+13055587780',
    cleanNumber: '13055587780',
    formatted: '+1 (305) 558-7780',
    detectedCountry: 'US',
    isValidFormat: true,
    exists: true,
    avatar: null, // Test fallback iOS silhouette
    profilePhotoAvailable: false,
    isBusiness: false,
    isVerified: false,
    displayName: null,
    verifiedName: null,
    city: 'Miami',
    state: 'Florida',
    discoveredAt: Date.now() - 72000
  },
  {
    number: '+13055582205',
    cleanNumber: '13055582205',
    formatted: '+1 (305) 558-2205',
    detectedCountry: 'US',
    isValidFormat: true,
    exists: true,
    avatar: '/avatars/lena.jpg',
    profilePhotoAvailable: true,
    isBusiness: false,
    isVerified: false,
    displayName: null,
    verifiedName: null,
    city: 'Miami',
    state: 'Florida',
    discoveredAt: Date.now() - 95000
  },
  {
    number: '+13055586634',
    cleanNumber: '13055586634',
    formatted: '+1 (305) 558-6634',
    detectedCountry: 'US',
    isValidFormat: true,
    exists: true,
    avatar: '/avatars/daniel.jpg',
    profilePhotoAvailable: true,
    isBusiness: true,
    isVerified: true,
    displayName: 'Ocean Prime Logistics',
    verifiedName: 'Ocean Prime Logistics',
    city: 'Miami',
    state: 'Florida',
    discoveredAt: Date.now() - 130000
  },
  {
    number: '+13055589941',
    cleanNumber: '13055589941',
    formatted: '+1 (305) 558-9941',
    detectedCountry: 'US',
    isValidFormat: true,
    exists: true,
    avatar: null, // Fallback silhouette
    profilePhotoAvailable: false,
    isBusiness: false,
    isVerified: false,
    displayName: null,
    verifiedName: null,
    city: 'Miami',
    state: 'Florida',
    discoveredAt: Date.now() - 180000
  },
  {
    number: '+13055583377',
    cleanNumber: '13055583377',
    formatted: '+1 (305) 558-3377',
    detectedCountry: 'US',
    isValidFormat: true,
    exists: true,
    avatar: '/avatars/priya.jpg',
    profilePhotoAvailable: true,
    isBusiness: false,
    isVerified: false,
    displayName: null,
    verifiedName: null,
    city: 'Miami',
    state: 'Florida',
    discoveredAt: Date.now() - 240000
  },
  {
    number: '+13055585562',
    cleanNumber: '13055585562',
    formatted: '+1 (305) 558-5562',
    detectedCountry: 'US',
    isValidFormat: true,
    exists: true,
    avatar: null,
    profilePhotoAvailable: false,
    isBusiness: false,
    isVerified: false,
    displayName: null,
    verifiedName: null,
    city: 'Miami',
    state: 'Florida',
    discoveredAt: Date.now() - 310000
  },
  {
    number: '+13055581109',
    cleanNumber: '13055581109',
    formatted: '+1 (305) 558-1109',
    detectedCountry: 'US',
    isValidFormat: true,
    exists: true,
    avatar: '/avatars/aisha.jpg',
    profilePhotoAvailable: true,
    isBusiness: true,
    isVerified: false,
    displayName: null,
    verifiedName: null,
    city: 'Miami',
    state: 'Florida',
    discoveredAt: Date.now() - 400000
  },
  {
    number: '+13055587714',
    cleanNumber: '13055587714',
    formatted: '+1 (305) 558-7714',
    detectedCountry: 'US',
    isValidFormat: true,
    exists: true,
    avatar: '/avatars/luis.jpg',
    profilePhotoAvailable: true,
    isBusiness: false,
    isVerified: false,
    displayName: null,
    verifiedName: null,
    city: 'Miami',
    state: 'Florida',
    discoveredAt: Date.now() - 520000
  },
  {
    number: '+13055586689',
    cleanNumber: '13055586689',
    formatted: '+1 (305) 558-6689',
    detectedCountry: 'US',
    isValidFormat: true,
    exists: true,
    avatar: null,
    profilePhotoAvailable: false,
    isBusiness: false,
    isVerified: false,
    displayName: null,
    verifiedName: null,
    city: 'Miami',
    state: 'Florida',
    discoveredAt: Date.now() - 610000
  },
  {
    number: '+13055588820',
    cleanNumber: '13055588820',
    formatted: '+1 (305) 558-8820',
    detectedCountry: 'US',
    isValidFormat: true,
    exists: true,
    avatar: '/avatars/farah.jpg',
    profilePhotoAvailable: true,
    isBusiness: true,
    isVerified: true,
    displayName: 'Solari Financial Group',
    verifiedName: 'Solari Financial Group',
    city: 'Miami',
    state: 'Florida',
    discoveredAt: Date.now() - 750000
  },
  {
    number: '+13055584439',
    cleanNumber: '13055584439',
    formatted: '+1 (305) 558-4439',
    detectedCountry: 'US',
    isValidFormat: true,
    exists: true,
    avatar: '/avatars/hana.jpg',
    profilePhotoAvailable: true,
    isBusiness: false,
    isVerified: false,
    displayName: null,
    verifiedName: null,
    city: 'Miami',
    state: 'Florida',
    discoveredAt: Date.now() - 900000
  },
  {
    number: '+13055582291',
    cleanNumber: '13055582291',
    formatted: '+1 (305) 558-2291',
    detectedCountry: 'US',
    isValidFormat: true,
    exists: true,
    avatar: null,
    profilePhotoAvailable: false,
    isBusiness: false,
    isVerified: false,
    displayName: null,
    verifiedName: null,
    city: 'Miami',
    state: 'Florida',
    discoveredAt: Date.now() - 1100000
  },
  {
    number: '+13055583318',
    cleanNumber: '13055583318',
    formatted: '+1 (305) 558-3318',
    detectedCountry: 'US',
    isValidFormat: true,
    exists: true,
    avatar: '/avatars/adeyemi.jpg',
    profilePhotoAvailable: true,
    isBusiness: false,
    isVerified: false,
    displayName: null,
    verifiedName: null,
    city: 'Miami',
    state: 'Florida',
    discoveredAt: Date.now() - 1300000
  },
  {
    number: '+13055589902',
    cleanNumber: '13055589902',
    formatted: '+1 (305) 558-9902',
    detectedCountry: 'US',
    isValidFormat: true,
    exists: true,
    avatar: null,
    profilePhotoAvailable: false,
    isBusiness: true,
    isVerified: false,
    displayName: null,
    verifiedName: null,
    city: 'Miami',
    state: 'Florida',
    discoveredAt: Date.now() - 1500000
  },
  {
    number: '+13055585517',
    cleanNumber: '13055585517',
    formatted: '+1 (305) 558-5517',
    detectedCountry: 'US',
    isValidFormat: true,
    exists: true,
    avatar: '/avatars/omar.jpg',
    profilePhotoAvailable: true,
    isBusiness: false,
    isVerified: false,
    displayName: null,
    verifiedName: null,
    city: 'Miami',
    state: 'Florida',
    discoveredAt: Date.now() - 1800000
  },
  {
    number: '+13055587742',
    cleanNumber: '13055587742',
    formatted: '+1 (305) 558-7742',
    detectedCountry: 'US',
    isValidFormat: true,
    exists: true,
    avatar: null,
    profilePhotoAvailable: false,
    isBusiness: false,
    isVerified: false,
    displayName: null,
    verifiedName: null,
    city: 'Miami',
    state: 'Florida',
    discoveredAt: Date.now() - 2100000
  },
  {
    number: '+13055581183',
    cleanNumber: '13055581183',
    formatted: '+1 (305) 558-1183',
    detectedCountry: 'US',
    isValidFormat: true,
    exists: true,
    avatar: '/avatars/sofia.jpg',
    profilePhotoAvailable: true,
    isBusiness: true,
    isVerified: true,
    displayName: 'Beacon Commercial Group',
    verifiedName: 'Beacon Commercial Group',
    city: 'Miami',
    state: 'Florida',
    discoveredAt: Date.now() - 2500000
  },
  {
    number: '+13055589990',
    cleanNumber: '13055589990',
    formatted: '+1 (305) 558-9990',
    detectedCountry: 'US',
    isValidFormat: true,
    exists: true,
    avatar: null,
    profilePhotoAvailable: false,
    isBusiness: false,
    isVerified: false,
    displayName: null,
    verifiedName: null,
    city: 'Miami',
    state: 'Florida',
    discoveredAt: Date.now() - 3000000
  }
];

export function isDevMockEnabled() {
  if (typeof window === 'undefined') return false;
  if (!import.meta.env.DEV) return false;
  const params = new URLSearchParams(window.location.search);
  return params.get('mockLeads') === '1' || window.__FORCE_MOCK_LEADS__ === true;
}
