import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { parsePhoneNumberFromString } from 'libphonenumber-js';
import { countries } from '../data/countries';

const APP_NAME = 'WhatsApp Shield';
const APP_VERSION = '1.0.0';

// Brand palette
const NAVY = [15, 23, 42];
const GREEN = [0, 217, 126];
const GREEN_DARK = [0, 148, 90];
const SUCCESS = [0, 184, 110];
const ERROR = [239, 68, 68];
const AMBER = [245, 158, 11];
const SLATE = [148, 163, 184];
const SURFACE = [248, 250, 252];
const BORDER = [226, 232, 240];

export const getCountryName = (code) => {
  if (!code) return 'Unknown';
  const c = countries.find(c => c.iso.toLowerCase() === code.toLowerCase() || c.code === code);
  return c ? c.name : code;
};

export const getCountryFlag = (code) => {
  if (!code || code === 'N/A' || code === 'Unknown') return '';
  const c = countries.find(c => c.iso.toLowerCase() === code.toLowerCase());
  if (!c) return '';
  return String.fromCodePoint(...c.iso.toUpperCase().split('').map(ch => 0x1F1E6 + ch.charCodeAt(0) - 65));
};

export const getCountryFromNumber = (num) => {
  try {
    const parsed = parsePhoneNumberFromString(num);
    if (parsed && parsed.country) {
      const c = countries.find(c => c.iso.toLowerCase() === parsed.country.toLowerCase());
      return { code: parsed.country, name: c ? c.name : parsed.country };
    }
  } catch (e) {}
  return { code: 'Unknown', name: 'Unknown' };
};

const getCountryDialCode = (code) => {
  if (!code) return null;
  const c = countries.find(c => c.iso.toLowerCase() === String(code).toLowerCase());
  return c ? c.code : null;
};

function campaignDisplayName(campaign) {
  const country = getCountryName(campaign?.countryCode);
  let dateStr = '';
  if (campaign?.timestamp) {
    const d = new Date(campaign.timestamp);
    if (!isNaN(d)) dateStr = d.toLocaleDateString();
  }
  return `Audience Scan - ${country}${dateStr ? ' - ' + dateStr : ''}`;
}

function buildMetadata(campaign, filterLabel, totalRecords, format) {
  const now = new Date();
  const yieldRatio = campaign.totalChecked > 0
    ? Math.round((campaign.registeredCount / campaign.totalChecked) * 100)
    : 0;
  return {
    generatedAt: now.toISOString(),
    generatedDate: now.toLocaleDateString(),
    generatedTime: now.toLocaleTimeString(),
    appName: APP_NAME,
    appVersion: APP_VERSION,
    generatedBy: 'Generated by WhatsApp Shield',
    exportType: filterLabel || 'Full Campaign Report',
    exportFormat: format || 'PDF',
    totalRecords,
    campaignName: campaignDisplayName(campaign),
    campaign: {
      id: campaign.id,
      ref: campaign.id?.substring(0, 8) || 'N/A',
      timestamp: campaign.timestamp,
      countryCode: campaign.countryCode || 'Unknown',
      countryDialCode: getCountryDialCode(campaign.countryCode),
      countryName: getCountryName(campaign.countryCode),
      shieldMode: campaign.shieldMode ? 'Enabled' : 'Disabled',
      delayMs: campaign.delayMs || 0,
      yieldRatio: yieldRatio + '%',
      totalChecked: campaign.totalChecked || 0,
      registeredCount: campaign.registeredCount || 0,
      unregisteredCount: campaign.unregisteredCount || 0,
      invalidCount: campaign.invalidCount || 0,
    },
  };
}

function formatRecord(r, campaign) {
  const country = r.detectedCountry || getCountryFromNumber(r.formatted || r.number || '');
  const countryName = typeof country === 'object' ? country.name : getCountryName(country);
  const countryCode = typeof country === 'object' ? country.code : country;
  const countryFlag = getCountryFlag(typeof country === 'object' ? country.code : country);
  const status = r.exists ? 'Registered' : (r.isValidFormat ? 'Not Registered' : 'Invalid Format');
  const accountType = r.isBusiness ? 'Business' : (r.exists ? 'Personal' : 'N/A');
  const ts = r.timestamp || campaign?.timestamp || new Date().toISOString();
  const d = new Date(ts);
  return {
    phoneNumber: r.formatted || r.number || '',
    originalNumber: r.number || '',
    countryCode: countryCode || 'Unknown',
    countryDialCode: getCountryDialCode(countryCode),
    countryName,
    countryFlag,
    whatsappStatus: status,
    accountType,
    isVerified: r.isVerified ? 'Yes' : 'No',
    displayName: r.displayName || r.verifiedName || 'None',
    profilePhotoAvailable: r.profilePhotoAvailable === true || !!r.avatar ? 'Yes' : 'No',
    profileImageUrl: r.avatar || '',
    verificationDate: !isNaN(d) ? d.toLocaleDateString() : (ts.split('T')[0] || ''),
    verificationTime: !isNaN(d) ? d.toLocaleTimeString() : '',
  };
}

async function fetchImageDataURL(url) {
  try {
    const res = await fetch(url, { mode: 'cors' });
    if (!res.ok) return null;
    const blob = await res.blob();
    return await new Promise((resolve) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch (e) {
    return null;
  }
}

function convertWebPToPNG(dataUrl) {
  return new Promise((resolve) => {
    try {
      const img = new Image();
      img.onload = () => {
        try {
          const canvas = document.createElement('canvas');
          canvas.width = img.naturalWidth || 64;
          canvas.height = img.naturalHeight || 64;
          canvas.getContext('2d').drawImage(img, 0, 0);
          resolve(canvas.toDataURL('image/png'));
        } catch (e) { resolve(null); }
      };
      img.onerror = () => resolve(null);
      img.src = dataUrl;
    } catch (e) { resolve(null); }
  });
}

function detectImageFormat(dataUrl) {
  if (dataUrl.startsWith('data:image/png')) return 'PNG';
  if (dataUrl.startsWith('data:image/webp')) return 'WEBP';
  return 'JPEG';
}

function escapeCSV(val) {
  const str = String(val ?? '');
  if (str.includes(',') || str.includes('"') || str.includes('\n')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

export function downloadFile(content, fileName, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/* ============================================================
   CSV EXPORT
   ============================================================ */

function buildCSVRow(r, campaign, index) {
  const rec = formatRecord(r, campaign);
  let countryCell;
  if (rec.countryFlag && rec.countryDialCode) {
    countryCell = rec.countryFlag + ' +' + rec.countryDialCode;
  } else if (rec.countryCode && rec.countryCode !== 'Unknown') {
    countryCell = rec.countryCode;
  } else {
    countryCell = 'N/A';
  }
  let profilePhoto = rec.profileImageUrl;
  if (!profilePhoto) {
    if (rec.whatsappStatus === 'Not Registered') profilePhoto = 'Not Registered';
    else if (rec.whatsappStatus === 'Invalid Format') profilePhoto = 'N/A';
    else profilePhoto = 'No Profile Photo';
  }
  return [
    String(index),
    countryCell,
    rec.phoneNumber,
    rec.whatsappStatus,
    rec.accountType,
    rec.displayName === 'None' ? '' : rec.displayName,
    rec.isVerified,
    profilePhoto,
  ].map(escapeCSV).join(',');
}

export function exportFilteredCSV(results, campaign, filterLabel) {
  if (!results || results.length === 0) return;
  const headers = [
    '#', 'Country (Flag + Country Code)', 'Phone Number', 'Status', 'Type', 'Display Name', 'Verified', 'Profile Photo',
  ];
  const rows = results.map((r, i) => buildCSVRow(r, campaign, i + 1));
  const csv = '\uFEFF' + [headers.join(','), ...rows].join('\n');
  downloadFile(csv, `whatsapp-shield-report-${campaign.id?.substring(0, 8) || 'export'}.csv`, 'text/csv;charset=utf-8');
}

export function exportAllHistoryCSV(campaigns, phone) {
  if (!campaigns || campaigns.length === 0) return;
  const headers = [
    '#', 'Country (Flag + Country Code)', 'Phone Number', 'Status', 'Type', 'Display Name', 'Verified', 'Profile Photo',
  ];
  const rows = [];
  let counter = 0;
  campaigns.forEach(c => {
    if (!c.results) return;
    c.results.forEach(r => {
      counter += 1;
      rows.push(buildCSVRow(r, c, counter));
    });
  });
  if (rows.length === 0) return;
  const csv = '\uFEFF' + [headers.join(','), ...rows].join('\n');
  downloadFile(csv, `whatsapp-shield-all-history-${phone || 'export'}.csv`, 'text/csv;charset=utf-8');
}

/* ============================================================
   TXT EXPORT
   ============================================================ */

export function exportFilteredTXT(results, campaign, filterLabel) {
  if (!results || results.length === 0) return;
  const meta = buildMetadata(campaign, filterLabel, results.length, 'TXT');
  const lines = [];
  const sep = '='.repeat(96);
  const sep2 = '-'.repeat(96);
  const pad = (s, n) => String(s).padEnd(n);
  const rpad = (s, n) => String(s).padStart(n);

  lines.push(sep);
  lines.push('  WHATSAPP SHIELD - VALIDATION CAMPAIGN REPORT');
  lines.push(sep);
  lines.push('');
  lines.push(`  Application:      ${meta.appName} v${meta.appVersion}`);
  lines.push(`  Generated By:     WhatsApp Shield`);
  lines.push(`  Export Format:    TXT`);
  lines.push(`  Export Date:      ${meta.generatedDate} ${meta.generatedTime}`);
  lines.push(`  Export Filter:    ${filterLabel || 'All Results'}`);
  lines.push('');
  lines.push(sep2);
  lines.push('  CAMPAIGN SUMMARY');
  lines.push(sep2);
  lines.push(`  Campaign Name:    ${meta.campaignName}`);
  lines.push(`  Campaign ID:      ${meta.campaign.id}`);
  lines.push(`  Campaign Ref:     ${meta.campaign.ref}`);
  lines.push(`  Country:          ${getCountryFlag(meta.campaign.countryCode)} ${meta.campaign.countryName} (+${meta.campaign.countryDialCode || meta.campaign.countryCode})`);
  lines.push(`  Executed:         ${new Date(campaign.timestamp).toLocaleString()}`);
  lines.push(`  Shield Mode:      ${meta.campaign.shieldMode}  |  Delay: ${meta.campaign.delayMs}ms`);
  lines.push(`  Total Checked:    ${meta.campaign.totalChecked}`);
  lines.push(`  Registered:       ${meta.campaign.registeredCount}`);
  lines.push(`  Not Registered:   ${meta.campaign.unregisteredCount}`);
  lines.push(`  Invalid Format:   ${meta.campaign.invalidCount}`);
  lines.push(`  Yield Ratio:      ${meta.campaign.yieldRatio}`);
  lines.push(`  Exported Records: ${results.length}`);
  lines.push('');
  lines.push(sep2);
  lines.push('  VERIFICATION RESULTS');
  lines.push(sep2);
  lines.push('');
  lines.push(`  ${rpad('#', 4)} ${pad('Phone Number', 22)} ${pad('Country', 18)} ${pad('Status', 16)} ${pad('Type', 10)} ${pad('Display Name', 26)}`);
  lines.push(`  ${pad('', 4)} ${pad('', 22)} ${pad('', 18)} ${pad('', 16)} ${pad('', 10)} ${pad('', 26)}`);
  results.forEach((r, i) => {
    const rec = formatRecord(r, campaign);
    const statusIcon = rec.whatsappStatus === 'Registered' ? 'WA' : rec.whatsappStatus === 'Not Registered' ? '--' : '!!';
    const photo = rec.whatsappStatus === 'Registered'
      ? (rec.profilePhotoAvailable === 'Yes' ? 'Yes' : 'No Photo')
      : (rec.whatsappStatus === 'Not Registered' ? 'Not Registered' : 'N/A');
    lines.push(`  ${rpad(i + 1, 4)} ${pad(rec.phoneNumber, 22)} ${pad(getCountryFlag(rec.countryCode) + ' ' + rec.countryName, 18)} ${pad(statusIcon + ' ' + rec.whatsappStatus, 16)} ${pad(rec.accountType, 10)} ${pad(rec.displayName, 26)}`);
  });
  lines.push('');
  lines.push(sep);
  lines.push(`  End of Report | ${meta.appName} v${meta.appVersion}`);
  lines.push(`  Generated: ${meta.generatedAt}`);
  lines.push(sep);
  downloadFile(lines.join('\n'), `whatsapp-shield-report-${campaign.id?.substring(0, 8) || 'export'}.txt`, 'text/plain;charset=utf-8');
}

export function exportAllHistoryTXT(campaigns, phone) {
  if (!campaigns || campaigns.length === 0) return;
  const now = new Date();
  const lines = [];
  const sep = '='.repeat(96);
  const sep2 = '-'.repeat(96);
  const pad = (s, n) => String(s).padEnd(n);
  const rpad = (s, n) => String(s).padStart(n);

  lines.push(sep);
  lines.push('  WHATSAPP SHIELD - COMPLETE ACCOUNT HISTORY');
  lines.push(sep);
  lines.push('');
  lines.push(`  Application:      ${APP_NAME} v${APP_VERSION}`);
  lines.push(`  Generated By:     WhatsApp Shield`);
  lines.push(`  Export Format:    TXT`);
  lines.push(`  Export Date:      ${now.toLocaleDateString()} ${now.toLocaleTimeString()}`);
  const totalRecords = campaigns.reduce((s, c) => s + (c.results?.length || 0), 0);
  lines.push(`  Total Campaigns:  ${campaigns.length}`);
  lines.push(`  Total Records:    ${totalRecords}`);
  lines.push('');
  lines.push(sep2);

  campaigns.forEach((c, ci) => {
    lines.push('');
    lines.push(`  CAMPAIGN ${ci + 1} - ${campaignDisplayName(c)}`);
    lines.push(sep2);
    lines.push(`  Campaign ID:      ${c.id}`);
    lines.push(`  Date:             ${new Date(c.timestamp).toLocaleString()}`);
    lines.push(`  Country:          ${getCountryFlag(c.countryCode)} ${getCountryName(c.countryCode)} (+${getCountryDialCode(c.countryCode) || c.countryCode})`);
    lines.push(`  Shield:           ${c.shieldMode ? 'Enabled' : 'Disabled'}  |  Delay: ${c.delayMs}ms`);
    lines.push(`  Total:            ${c.totalChecked}  |  Registered: ${c.registeredCount}  |  Not Registered: ${c.unregisteredCount}  |  Invalid: ${c.invalidCount}`);
    lines.push('');
    if (c.results && c.results.length > 0) {
      lines.push(`  ${rpad('#', 4)} ${pad('Phone Number', 22)} ${pad('Status', 16)} ${pad('Type', 10)} ${pad('Display Name', 26)}`);
      lines.push(`  ${pad('', 4)} ${pad('', 22)} ${pad('', 16)} ${pad('', 10)} ${pad('', 26)}`);
      c.results.forEach((r, ri) => {
        const rec = formatRecord(r, c);
        lines.push(`  ${rpad(ri + 1, 4)} ${pad(rec.phoneNumber, 22)} ${pad(rec.whatsappStatus, 16)} ${pad(rec.accountType, 10)} ${pad(rec.displayName, 26)}`);
      });
    }
    lines.push('');
    lines.push(sep2);
  });

  lines.push('');
  lines.push(sep);
  lines.push(`  End of Report | ${APP_NAME} v${APP_VERSION}`);
  lines.push(sep);
  downloadFile(lines.join('\n'), `whatsapp-shield-all-history-${phone || 'export'}.txt`, 'text/plain;charset=utf-8');
}

/* ============================================================
   JSON EXPORT
   ============================================================ */

function toRecordJSON(rec) {
  return {
    phoneNumber: rec.phoneNumber,
    originalNumber: rec.originalNumber,
    country: {
      code: rec.countryCode,
      dialCode: rec.countryDialCode ? '+' + rec.countryDialCode : null,
      name: rec.countryName,
      flag: rec.countryFlag,
    },
    whatsappStatus: rec.whatsappStatus,
    accountType: rec.accountType,
    isVerified: rec.isVerified === 'Yes',
    displayName: rec.displayName === 'None' ? null : rec.displayName,
    profile: {
      photoAvailable: rec.profilePhotoAvailable === 'Yes',
      photoUrl: rec.profileImageUrl,
    },
    verification: { date: rec.verificationDate, time: rec.verificationTime },
  };
}

export function exportFilteredJSON(results, campaign, filterLabel) {
  if (!results || results.length === 0) return;
  const meta = buildMetadata(campaign, filterLabel, results.length, 'JSON');
  const output = {
    meta: {
      appName: meta.appName,
      appVersion: meta.appVersion,
      generatedBy: meta.generatedBy,
      generatedAt: meta.generatedAt,
      exportType: meta.exportType,
      exportFormat: meta.exportFormat,
    },
    campaign: {
      id: meta.campaign.id,
      ref: meta.campaign.ref,
      name: meta.campaignName,
      timestamp: meta.campaign.timestamp,
      country: {
        code: meta.campaign.countryCode,
        dialCode: meta.campaign.countryDialCode ? '+' + meta.campaign.countryDialCode : null,
        name: meta.campaign.countryName,
      },
      shieldMode: meta.campaign.shieldMode,
      delayMs: meta.campaign.delayMs,
      yieldRatio: meta.campaign.yieldRatio,
      totalChecked: meta.campaign.totalChecked,
      registeredCount: meta.campaign.registeredCount,
      unregisteredCount: meta.campaign.unregisteredCount,
      invalidCount: meta.campaign.invalidCount,
    },
    summary: {
      totalRecords: meta.campaign.totalChecked,
      exportedRecords: results.length,
      registered: meta.campaign.registeredCount,
      notRegistered: meta.campaign.unregisteredCount,
      invalid: meta.campaign.invalidCount,
      yieldRatio: meta.campaign.yieldRatio,
    },
    records: results.map(r => toRecordJSON(formatRecord(r, campaign))),
  };
  downloadFile(JSON.stringify(output, null, 2), `whatsapp-shield-report-${campaign.id?.substring(0, 8) || 'export'}.json`, 'application/json;charset=utf-8');
}

export function exportAllHistoryJSON(campaigns, phone) {
  if (!campaigns || campaigns.length === 0) return;
  const now = new Date();
  const output = {
    meta: {
      appName: APP_NAME,
      appVersion: APP_VERSION,
      generatedBy: 'Generated by WhatsApp Shield',
      generatedAt: now.toISOString(),
      exportType: 'Full Account History',
      exportFormat: 'JSON',
      totalCampaigns: campaigns.length,
      totalRecords: campaigns.reduce((s, c) => s + (c.results?.length || 0), 0),
    },
    campaigns: campaigns.map(c => ({
      id: c.id,
      name: campaignDisplayName(c),
      timestamp: c.timestamp,
      country: {
        code: c.countryCode,
        dialCode: getCountryDialCode(c.countryCode) ? '+' + getCountryDialCode(c.countryCode) : null,
        name: getCountryName(c.countryCode),
      },
      shieldMode: c.shieldMode ? 'Enabled' : 'Disabled',
      delayMs: c.delayMs,
      totalChecked: c.totalChecked,
      registeredCount: c.registeredCount,
      unregisteredCount: c.unregisteredCount,
      invalidCount: c.invalidCount,
      results: (c.results || []).map(r => toRecordJSON(formatRecord(r, c))),
    })),
  };
  downloadFile(JSON.stringify(output, null, 2), `whatsapp-shield-all-history-${phone || 'export'}.json`, 'application/json;charset=utf-8');
}

/* ============================================================
   PDF EXPORT
   ============================================================ */

function drawLogo(doc, x, y, size) {
  try {
    doc.setFillColor(...GREEN);
    doc.roundedRect(x, y, size, size, size * 0.18, size * 0.18, 'F');
    doc.setDrawColor(255, 255, 255);
    doc.setLineWidth(size * 0.12);
    doc.line(x + size * 0.26, y + size * 0.52, x + size * 0.45, y + size * 0.7);
    doc.line(x + size * 0.45, y + size * 0.7, x + size * 0.76, y + size * 0.32);
    doc.setLineWidth(0.2);
  } catch (e) {}
}

function drawFlagChip(doc, x, y, w, h, code) {
  try {
    doc.setFillColor(...GREEN);
    doc.roundedRect(x, y, w, h, 1, 1, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(5.5);
    doc.setTextColor(15, 23, 42);
    doc.text(code.toUpperCase(), x + w / 2, y + h / 2 + 1, { align: 'center' });
  } catch (e) {}
}

function drawPremiumHeader(doc, meta) {
  const pageW = doc.internal.pageSize.getWidth();
  const bandH = 32;

  doc.setFillColor(...NAVY);
  doc.rect(0, 0, pageW, bandH, 'F');
  doc.setFillColor(33, 46, 74);
  doc.rect(0, 0, pageW, 1.6, 'F');
  doc.setFillColor(...GREEN);
  doc.rect(0, bandH, pageW, 1.2, 'F');

  drawLogo(doc, 12, 6.5, 12);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(255, 255, 255);
  doc.text('WHATSAPP SHIELD', 28, 13);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.text('Enterprise Audience Validation Suite', 28, 18.5);

  const badgeW = 44;
  const badgeH = 6.5;
  doc.setFillColor(...GREEN);
  doc.roundedRect(pageW - 12 - badgeW, 6, badgeW, badgeH, 1, 1, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(6.5);
  doc.setTextColor(15, 23, 42);
  doc.text((meta.exportFormat || 'REPORT').toUpperCase(), pageW - 12 - badgeW / 2, 10.3, { align: 'center' });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12.5);
  doc.setTextColor(255, 255, 255);
  doc.text(meta.reportTitle || 'Campaign Verification Report', pageW - 12, 17.5, { align: 'right' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.8);
  doc.setTextColor(203, 213, 225);
  doc.text(`${meta.generatedDate}   ${meta.generatedTime}`, pageW - 12, 23, { align: 'right' });

  if (meta.campaignName) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(226, 232, 240);
    doc.text(meta.campaignName, pageW - 12, 28.5, { align: 'right', maxWidth: pageW - 200 });
  }
}

function drawSectionTitle(doc, y, label) {
  const pageW = doc.internal.pageSize.getWidth();
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...NAVY);
  doc.text(label, 12, y);
  doc.setDrawColor(...GREEN);
  doc.setLineWidth(0.6);
  doc.line(12, y + 2.2, pageW - 12, y + 2.2);
  return y + 6.5;
}

function drawStatCard(doc, x, y, w, h, label, value, color, chip) {
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(...BORDER);
  doc.setLineWidth(0.2);
  doc.roundedRect(x, y, w, h, 1.2, 1.2, 'FD');

  doc.setFillColor(...(color || NAVY));
  doc.roundedRect(x + 0.7, y + 1.2, 1.3, h - 2.4, 0.6, 0.6, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(5.8);
  doc.setTextColor(...SLATE);
  doc.text(String(label).toUpperCase(), x + 3.4, y + 3.5);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...(color || NAVY));
  const v = (value === null || value === undefined || value === '') ? 'N/A' : String(value);
  if (chip) {
    drawFlagChip(doc, x + 3.4, y + 5.2, 11, 4.4, chip);
    doc.text(v, x + 16, y + 9.4, { maxWidth: w - 20 });
  } else {
    doc.text(v, x + 3.4, y + h - 2.4, { maxWidth: w - 6 });
  }
}

function drawStatGrid(doc, items, startY) {
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 12;
  const cols = 4;
  const gap = 5;
  const cellW = (pageW - 2 * margin - (cols - 1) * gap) / cols;
  const cellH = 12.5;
  const rowGap = 4.5;
  items.forEach((item, i) => {
    const row = Math.floor(i / cols);
    const col = i % cols;
    const x = margin + col * (cellW + gap);
    const cy = startY + row * (cellH + rowGap);
    drawStatCard(doc, x, cy, cellW, cellH, item.label, item.value, item.color, item.chip);
  });
  return startY + Math.ceil(items.length / cols) * (cellH + rowGap);
}

function drawCampaignBanner(doc, y, label, value) {
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 12;
  const bannerH = 11;
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(...BORDER);
  doc.setLineWidth(0.2);
  doc.roundedRect(margin, y, pageW - 2 * margin, bannerH, 1.2, 1.2, 'FD');
  doc.setFillColor(...GREEN);
  doc.roundedRect(margin + 0.7, y + 1.2, 1.3, bannerH - 2.4, 0.6, 0.6, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(5.8);
  doc.setTextColor(...SLATE);
  doc.text(String(label).toUpperCase(), margin + 3.4, y + 3.5);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...NAVY);
  doc.text(String(value), margin + 3.4, y + bannerH - 2.4, { maxWidth: pageW - 2 * margin - 8 });
  return y + bannerH;
}

function drawCompactHeader(doc, pageNum, campaignName, generatedDate) {
  const pageW = doc.internal.pageSize.getWidth();
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, pageW, 11, 'F');
  doc.setFillColor(...GREEN);
  doc.rect(0, 11, pageW, 0.7, 'F');
  drawLogo(doc, 4, 3, 5);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(255, 255, 255);
  doc.text('WHATSAPP SHIELD', 11.5, 6.8);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.3);
  doc.setTextColor(203, 213, 225);
  const name = campaignName || 'Campaign Report';
  doc.text(name.length > 62 ? name.slice(0, 62) + '...' : name, 11.5, 10.2);
  doc.setTextColor(165, 175, 190);
  const pageStr = `Page ${pageNum}`;
  const pageWmm = doc.getTextWidth(pageStr);
  doc.text(pageStr, pageW - 12, 6.8, { align: 'right' });
  if (generatedDate) doc.text(generatedDate, pageW - 12 - pageWmm - 5, 6.8, { align: 'right' });
}

function photoPlaceholderLabel(r, hasPhoto) {
  if (hasPhoto) return 'Photo';
  if (r.exists) return 'No Profile Photo';
  if (r.isValidFormat) return 'Not Registered';
  return 'Invalid';
}

function drawPage1Header(doc, meta) {
  const pageW = doc.internal.pageSize.getWidth();  // 297 in landscape
  const pageH = doc.internal.pageSize.getHeight();  // 210 in landscape
  const headerH = 88;

  // Dark charcoal-to-emerald gradient background approximation
  // Top dark navy #0B0F17 (from y=0 to y=headerH/2)
  doc.setFillColor(11, 15, 42); // #0B0F17
  doc.rect(0, 0, pageW, headerH / 2, 'F');
  // Bottom emerald #064E3B (from y=headerH/2 to y=headerH)
  doc.setFillColor(6, 78, 59); // #064E3B
  doc.rect(0, headerH / 2, pageW, headerH / 2, 'F');

  // Accent strip: 3px solid #10B981 along entire bottom edge of header
  doc.setFillColor(16, 185, 129); // #10B981
  doc.setLineWidth(3);
  doc.line(0, headerH - 3, pageW, headerH - 3);  // 3px from bottom edge of header
  doc.setLineWidth(1);

  // Left Column: Shield Icon + Title + Subtitle
  const leftX = 12;
  const leftY = headerH / 2 + 14;  // below the gradient, vertical center of lower half

  // Shield icon: white outline 28x28
  const shieldSize = 28;
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(16, 185, 129); // #10B981
  doc.setLineWidth(1.5);
  doc.roundedRect(leftX, leftY + 2, shieldSize, shieldSize * 0.8, 3, 3, 'FD');
  // Shield top simplified
  doc.setLineWidth(1);
  doc.line(leftX + 4, leftY + shieldSize * 0.8, leftX + 4 + shieldSize - 8, leftY + shieldSize * 0.8);
  doc.line(leftX + 4, leftY + shieldSize * 0.8, leftX + 4 + (shieldSize - 8) / 2, leftY + shieldSize * 0.65);

  // Title: "WHATSAPP SHIELD" 14pt bold white
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.text('WHATSAPP SHIELD', leftX + shieldSize + 8, leftY + 16);

  // Subtitle: "Enterprise Audience Validation" 8.5pt #9CA3AF
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(156, 163, 175); // #9CA3AF
  doc.text('Enterprise Audience Validation', leftX + shieldSize + 8, leftY + 4);

  // Right Column: PDF Badge + Document Title + Date
  const rightStart = pageW - 12;

  // PDF Badge: pill [PDF] with translucent emerald fill
  const badgeW = 44;
  const badgeH = 16;
  const badgeX = rightStart - badgeW - 4;
  const badgeY = headerH / 2 + 14;  // same vertical position as left content

  doc.setFillColor(16, 185, 129, 0.15); // rgba(16,185,129,0.15)
  doc.setDrawColor(16, 185, 129);
  doc.setLineWidth(1);
  doc.roundedRect(badgeX, badgeY, badgeW, badgeH, 3, 3, 'FD');

  // "[PDF]" text: 8pt bold white
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(6.5);
  doc.setTextColor(255, 255, 255);
  doc.text('[PDF]', badgeX + 3, badgeY + 3);

  // Filter Applied badge: small pill with filter label
  const filterLabel = meta.exportType || 'All Results';
  const filterBadgeW = 36;
  const filterBadgeH = 14;
  const filterBadgeX = badgeX - filterBadgeW - 4;
  const filterBadgeY = badgeY + badgeH + 2;

  doc.setFillColor(16, 185, 129, 0.15);
  doc.setDrawColor(16, 185, 129);
  doc.setLineWidth(1);
  doc.roundedRect(filterBadgeX, filterBadgeY, filterBadgeW, filterBadgeH, 3, 3, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(6);
  doc.setTextColor(16, 185, 129);
  doc.text(filterLabel, filterBadgeX + 3, filterBadgeY + 10);

  // Document Title: "Campaign Verification Report" 11pt bold white
  const titleX = rightStart;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(255, 255, 255);
  doc.text('Campaign Verification Report', titleX, badgeY + 24);

  // Date Stamp: 8.5pt #9CA3AF
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(156, 163, 175); // #9CA3AF
  doc.text(`${meta.generatedDate} ${meta.generatedTime}`, titleX, badgeY + 40);

  // Campaign Name Bar (Full Width, below header)
  const cnbH = 36;
  const cnbY = headerH + 4;  // below the 88px header, with small gap
  const cnbW = pageW - 24;

  // White card with #E2E8F0 border, 8px rounded corners
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(226, 232, 240); // #E2E8F0
  doc.setLineWidth(1);
  doc.roundedRect(12, cnbY, cnbW, cnbH, 8, 8, 'FD');

  // Emerald accent pill on left inside edge: 4px wide, #10B981
  doc.setFillColor(16, 185, 129);
  doc.roundedRect(12, cnbY + 2, 4, cnbH - 4, 2, 2, 'F');

  // Label: "CAMPAIGN NAME" 7.5pt uppercase #64748B
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139); // #64748B
  doc.text('CAMPAIGN NAME', 12 + 12, cnbY + cnbH - 5);

  // Value: campaign_name 12pt bold #0F172A
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(13, 23, 42); // #0F172A
  doc.text(meta.campaignName || 'Unknown Campaign', 12 + 12, cnbY + cnbH - 20);
}

function drawPage2PlusHeader(doc, pageNum, campaignName, generatedDate) {
  const pageW = doc.internal.pageSize.getWidth();
  const minHdr = 20;

  // Dark navy background
  doc.setFillColor(15, 23, 42); // #0B0F17
  doc.rect(0, 0, pageW, minHdr, 'F');

  // Thin 1px neutral border along bottom
  doc.setDrawColor(226, 232, 240); // #E2E8F0
  doc.setLineWidth(1);
  doc.line(0, minHdr, pageW, minHdr);

  // Left: Shield Icon + "WHATSAPP SHIELD" | "Enterprise Audience Validation"
  const leftX = 12;
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(16, 185, 129); // #10B981
  doc.setLineWidth(1.5);
  const shieldSize = 16;
  doc.roundedRect(leftX, 4, shieldSize, shieldSize * 0.8, 3, 3, 'FD');
  doc.line(leftX + 4, 4 + shieldSize * 0.8, leftX + 4 + shieldSize - 8, 4 + shieldSize * 0.8);
  doc.line(leftX + 4, 4 + shieldSize * 0.8, leftX + 4 + (shieldSize - 8) / 2, 4 + shieldSize * 0.65);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.setTextColor(255, 255, 255);
  doc.text('WHATSAPP SHIELD', leftX + shieldSize + 6, 6 + 8);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(5.5);
  doc.setTextColor(156, 163, 175); // #9CA3AF
  doc.text('Enterprise Audience Validation', leftX + shieldSize + 6, 6 + 4.5);

  // Right: Campaign Name + "Exported: {export_date}"
  const rightX = pageW - 12;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(100, 116, 139); // #64748B
  const cName = campaignName ? campaignName.length > 40 ? campaignName.slice(0, 40) + '...' : campaignName : 'Campaign Report';
  doc.text(cName, rightX - 12, 6 + 8);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.5);
  doc.setTextColor(156, 163, 175); // #9CA3AF
  doc.text(`Exported: ${generatedDate || ''}`, rightX - 12, 6 + 15);
}

function hexToRgb(hex) {
  const cleanHex = hex.startsWith('#') ? hex.substring(1) : hex;
  const result = /^([0-9a-fA-F]{2})([0-9a-fA-F]{2})([0-9a-fA-F]{2})$/.exec(cleanHex);
  if (!result) return [0, 0, 0];
  return [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)];
}

function drawKPICard(doc, x, y, w, h, label, value, labelColor, valueColor, bgColor, iconChar) {
  // Card background
  if (bgColor) {
    const [bgR, bgG, bgB] = hexToRgb(bgColor);
    doc.setFillColor(bgR / 255, bgG / 255, bgB / 255);
    doc.roundedRect(x, y, w, h, 8, 8, 'F');
    doc.setDrawColor(...hexToRgb(valueColor));
  } else {
    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(226, 232, 240); // #E2E8F0
    doc.setLineWidth(0.5);
    doc.roundedRect(x, y, w, h, 8, 8, 'FD');
  }

  // Label: uppercase, 7.5pt, color
  const [labelR, labelG, labelB] = hexToRgb(labelColor);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(labelR, labelG, labelB);
  doc.text(label.toUpperCase(), x + 6, y + h - 5);

  // Value: 22pt heavy bold
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  const [valR, valG, valB] = hexToRgb(valueColor);
  doc.setTextColor(valR, valG, valB);
  doc.text(String(value), x + 6, y + 6);

  // Right icon
  if (iconChar) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(12);
    doc.setTextColor(255, 255, 255);
    doc.text(iconChar, x + w - 18, y + h - 5);
  }
}

function drawCountryPill(doc, x, y, w, countryCode, countryName) {
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(226, 232, 240); // #E2E8F0
  doc.setLineWidth(1);
  doc.roundedRect(x, y, w, 24, 8, 8, 'FD');

  // Label: "COUNTRY" 7.5pt uppercase #64748B
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139); // #64748B
  doc.text('COUNTRY', x + 8, y + 24 - 5);

  // Flag emoji + country name bold uppercase
  const flagEmoji = _getFlagEmojiJSPDF(countryCode);
  const displayFlag = flagEmoji ? flagEmoji : countryCode.toUpperCase();

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(13, 23, 42); // #0F172A
  doc.text(displayFlag, x + 18, y + 24 - 5);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.text(countryName.toUpperCase(), x + 32, y + 24 - 5);
}

function _getFlagEmojiJSPDF(code) {
  if (!code || code === 'Unknown') return '';
  try {
    const c = code.toUpperCase();
    if (c.length === 2) {
      return String.fromCodePoint(...c.split('').map(ch => 0x1F1E6 + ch.charCodeAt(0) - 65));
    }
  } catch (e) {}
  return '';
}

function drawFooter(doc, pageNum, totalPages) {
  const pageH = doc.internal.pageSize.getHeight();
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 12;

  // Top border: thin subtle divider line above footer
  doc.setDrawColor(226, 232, 240); // #E2E8F0
  doc.setLineWidth(0.5);
  doc.line(margin, pageH - 14, pageW - margin, pageH - 14);

  // Left: "WhatsApp Shield v1.0.0" (7.5pt #94A3B8)
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(148, 163, 184); // #94A3B8
  doc.text('WhatsApp Shield v1.0.0', margin, pageH - 8);

  // Right: "Page X" (7.5pt #94A3B8) per spec section 4
  const pageStr = `Page ${pageNum}`;
  const pageWmm = doc.getTextWidth(pageStr);
  doc.text(pageW - margin - pageWmm, pageH - 8, pageStr, { align: 'right' });
}

function drawMicroBadges(doc, x, y, w, items) {
  const badgeH = 8;
  const badgeW = (w - 8) / items.length;
  const gap = 4;

  items.forEach((item, i) => {
    const bx = x + 4 + i * (badgeW + gap);
    // Micro badge background
    const [r, g, b] = hexToRgb(item.color);
    doc.setFillColor(r / 255, g / 255, b / 255);
    doc.roundedRect(bx, y, badgeW, badgeH, 3, 3, 'F');
    // Border
    doc.setDrawColor(r, g, b);
    doc.setLineWidth(0.5);
    doc.roundedRect(bx, y, badgeW, badgeH, 3, 3, 'S');
    // Text
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(6);
    doc.setTextColor(255, 255, 255);
    doc.text(item.label, bx + 1, y + badgeH - 1);
  });
}

export async function exportFilteredPDF(results, campaign, sessionUser, filterLabel) {
  if (!results || results.length === 0) return;
  const meta = buildMetadata(campaign, filterLabel, results.length, 'PDF');
  meta.reportTitle = 'Campaign Verification Report';
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 12;

  const totalChecked = meta.campaign.totalChecked || results.length;
  const registeredCount = meta.campaign.registeredCount || 0;
  const notRegisteredCount = meta.campaign.unregisteredCount || 0;
  const invalidCount = meta.campaign.invalidCount || 0;
  const yieldRatio = totalChecked > 0 ? Math.round((registeredCount / totalChecked) * 100) : 0;
  const dialCode = meta.campaign.countryDialCode;
  const countryName = meta.campaign.countryName === 'Unknown' ? 'Not Specified' : meta.campaign.countryName;
  const exportFilter = filterLabel || 'All Results';

  // Page 1: Full header + dashboard + table
  drawPage1Header(doc, meta);

  // Layout constants
  const headerH = 88;  // dark header band height
  const cnbH = 36;     // campaign name bar height
  const kpiH = 32;     // KPI card height
  const kpiGap = 8;    // gap between KPI cards
  const cardW = (pageW - 24 - 3 * kpiGap) / 4;  // 4 cards with gaps
  const cardXStart = 12;

  // ── Campaign Name Bar (below the 88px header) ──────────────────────
  // Header occupies y=0 to y=88. Name bar starts at y=92 (88+4 gap).
  const cnbY = headerH + 4;  // 92mm from top - below the header
  const cnbW = pageW - 24;   // full width with 12mm margins

  // White card with #E2E8F0 border, 8px rounded corners
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(1);
  doc.roundedRect(12, cnbY, cnbW, cnbH, 8, 8, 'FD');

  // Emerald accent pill on left inside edge: 4px wide, #10B981
  doc.setFillColor(16, 185, 129);
  doc.roundedRect(12, cnbY + 2, 4, cnbH - 4, 2, 2, 'F');

  // Label: "CAMPAIGN NAME" 7.5pt uppercase #64748B
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text('CAMPAIGN NAME', 12 + 12, cnbY + cnbH - 5);

  // Value: campaign_name 12pt bold #0F172A
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(13, 23, 42);
  doc.text(meta.campaignName || 'Unknown Campaign', 12 + 12, cnbY + cnbH - 20);

  // ── 4-Column KPI Statistic Cards Grid (below campaign name bar) ─────
  // KPI cards positioned below the name bar: y = cnbY + cnbH + 4 = 92 + 36 + 4 = 132
  const kpiY = cnbY + cnbH + 4;

  // KPI data with exact spec colors
  const kpiData = [
    {
      label: 'TOTAL CHECKED',
      value: totalChecked,
      labelColor: '#64748B',
      valueColor: '#0F172A',
      bgColor: null,
      icon: '⏚',
    },
    {
      label: 'REGISTERED',
      value: registeredCount,
      labelColor: '#64748B',
      valueColor: '#15803D',
      bgColor: '#F0FDF4',
      icon: '✓',
    },
    {
      label: 'NOT REGISTERED',
      value: notRegisteredCount,
      labelColor: '#64748B',
      valueColor: '#B91C1C',
      bgColor: '#FEF2F2',
      icon: '✗',
    },
    {
      label: 'YIELD RATIO',
      value: `${yieldRatio}%`,
      labelColor: '#64748B',
      valueColor: '#047857',
      bgColor: null,
      icon: '▲',
    },
  ];

  kpiData.forEach((kpi, i) => {
    const kpiX = cardXStart + i * (cardW + kpiGap);

    drawKPICard(doc, kpiX, kpiY, cardW, kpiH, kpi.label, kpi.value, kpi.labelColor, kpi.valueColor, kpi.bgColor, kpi.icon);
  });

  // Micro-badges for optional counts > 0 (Invalid)
  const microBadgeY = kpiY - 10;
  const microBadgeItems = [];
  if (invalidCount > 0) microBadgeItems.push({ label: 'Invalid', value: invalidCount, color: '#B45309' });

  if (microBadgeItems.length > 0) {
    drawMicroBadges(doc, 12, microBadgeY, pageW - 24, microBadgeItems);
  }

  // ── Country Secondary Pill Card ──────────────────────────────────────
  // Country pill positioned below KPI cards (y=132 to y=164, so pill at y=164 to y=188)
  const countryCardY = kpiY + kpiH;  // 164 - starts at y=164
  const countryCardH = 24;
  const countryCardW = pageW - 24;

  drawCountryPill(doc, 12, countryCardY, countryCardW, dialCode || 'Unknown', countryName);

  // ── Verification Results Data Table ─────────────────────────────────
  // Table starts immediately below country card
  const tableStartY = countryCardY + countryCardH;  // 164 + 24 = 188

  // Build table data with exact column specs
  const tableHeaders = ['#', 'Phone Number', 'Status', 'Type', 'Display Name', 'Profile'];

  const tableRows = [tableHeaders.slice()];
  const photoDataList = [];

  // Fetch profile pictures through the same-origin cached endpoint (no CORS) so
  // they can be embedded directly in the PDF. Only registered numbers with a
  // legitimately-recorded picture are queried, and fetches run concurrently with
  // a small concurrency cap so large exports don't stall on sequential requests.
  const concurrency = 6;
  const fetchTasks = [];
  for (let idx = 0; idx < results.length; idx++) {
    const r = results[idx];
    const rec = formatRecord(r, campaign);
    const phoneDigits = String(r.cleanNumber || r.number || '').replace(/\D/g, '');
    const hasAvatar = (r.profilePhotoAvailable === true || !!(r.avatar || r.profileImageUrl)) && r.exists && phoneDigits;
    const task = hasAvatar
      ? fetchImageDataURL(`/api/profile-picture?phone=${phoneDigits}`)
      : Promise.resolve(null);
    fetchTasks.push({ idx, task });
  }
  // Resolve with limited concurrency (keep table row index alignment).
  for (let start = 0; start < fetchTasks.length; start += concurrency) {
    const batch = fetchTasks.slice(start, start + concurrency);
    const settled = await Promise.all(batch.map(b => b.task));
    batch.forEach((b, i) => { photoDataList[b.idx] = settled[i] || null; });
  }

  for (let idx = 0; idx < results.length; idx++) {
    const r = results[idx];
    const rec = formatRecord(r, campaign);

    // Phone number formatted with country code
    let phone = rec.phoneNumber || '';
    if (phone && !phone.startsWith('+')) phone = '+' + phone;

    // Status
    let statusText = 'Not Registered';
    let statusColor = '#DC2626';
    if (r.exists && r.isValidFormat) {
      statusText = 'Registered';
      statusColor = '#16A34A';
    } else if (!r.exists && r.isValidFormat) {
      statusText = 'Not Registered';
      statusColor = '#DC2626';
    }

    // Type with icon prefix
    const isBusiness = r.isBusiness === true;
    const typeText = isBusiness ? '💼 Business' : '👤 Consumer';

    // Display Name - fallback to "None" if empty
    let dispName = rec.displayName || rec.verifiedName || '';
    if (!dispName || dispName === 'None') dispName = 'None';

    tableRows.push([
      String(idx + 1),
      phone,
      statusText,
      typeText,
      dispName,
      '',
    ]);
  }

  // Column widths: 5% + 25% + 18% + 18% + 22% + 12% = ~100%
  const colWidths = [
    (pageW - 24) * 0.05,   // #: 5%
    (pageW - 24) * 0.25,   // Phone Number: 25%
    (pageW - 24) * 0.18,   // Status: 18%
    (pageW - 24) * 0.18,   // Type: 18%
    (pageW - 24) * 0.22,   // Display Name: 22%
    (pageW - 24) * 0.12,   // Profile: 12%
  ];

  // Build autoTable configuration
  const autoTableConfig = {
    startY: tableStartY,
    head: [tableHeaders],
    body: tableRows,
    theme: 'striped',
    showHead: 'everyPage', // Repeat header on subsequent pages
    headStyles: {
      fillColor: [226, 232, 240], // #E2E8F0
      textColor: [51, 65, 85],    // #334155
      fontStyle: 'bold',
      fontSize: 8.5,
      cellPadding: 4,
    },
    styles: {
      cellPadding: 4,
      fontSize: 7.5,
      overflow: 'linebreak',
      lineColor: [226, 232, 240], // #E2E8F0
      lineWidth: 0.5,
      valign: 'middle',
      pageBreak: 'avoided',
    },
    alternateRowStyles: {
      fillColor: [255, 255, 255], // #FFFFFF
    },
    columnStyles: {
      0: { cellWidth: (pageW - 24) * 0.05, halign: 'center' },       // #: center
      1: { cellWidth: (pageW - 24) * 0.25, fontStyle: 'courier' },     // Phone Number: monospace, left
      2: { cellWidth: (pageW - 24) * 0.18, halign: 'left' },           // Status: left
      3: { cellWidth: (pageW - 24) * 0.18, halign: 'left' },           // Type: left
      4: { cellWidth: (pageW - 24) * 0.22, halign: 'left' },           // Display Name: left
      5: { cellWidth: (pageW - 24) * 0.12, halign: 'center' },          // Profile: center
    },
    didParseCell: function (data) {
      if (data.section !== 'body') return;

      // Column 2: Status text colors
      if (data.column.index === 2) {
        const val = String(data.cell.raw);
        if (val === 'Registered') data.cell.styles.textColor = [22, 163, 74]; // #16A34A
        else if (val === 'Not Registered') data.cell.styles.textColor = [219, 28, 28]; // #DC2626
      }

      // Column 4: Display Name fallback color
      if (data.column.index === 4) {
        const val = String(data.cell.raw);
        if (val === 'None' || val === '') data.cell.styles.textColor = [100, 116, 139]; // #64748B
      }

      // Column 5: Profile avatar rendering
      if (data.column.index === 5) {
        // willDrawCell handles the actual avatar rendering
      }
    },
    didDrawCell: function (data) {
      // Column 5: Profile - render 22x22px circular image or placeholder
      if (data.section === 'body' && data.column.index === 5) {
        const dataUrl = photoDataList[data.row.index];
        const cellX = data.cell.x || 0;
        const cellY = data.cell.y || 0;
        const cellW = data.cell.width || data.cell.w || 0;
        const cellH = data.cell.height || data.cell.h || 0;
        const x = cellX + 1;
        const y = cellY + (cellH - 22) / 2;
        const size = 22;

        if (dataUrl) {
          try {
            const fmt = detectImageFormat(dataUrl);
            doc.addImage(dataUrl, fmt, x + (cellW - 22) / 2, y + (cellH - 22) / 2 - 1, 22, 22);
          } catch (e) {}
        } else {
          // Draw 22x22px user-circle placeholder in #64748B neutral gray
          doc.setDrawColor(156, 163, 175); // #9CA3AF
          doc.setLineWidth(1);
          doc.circle(x + 11, y + 11, 10, 'FD');
          // Inner white circle
          doc.setFillColor(255, 255, 255);
          doc.circle(x + 11, y + 11, 4.5, 'FD');
        }
      }
    },
    margin: { left: 12, right: 12, top: 15, bottom: 10 },
    willDrawPage: function (data) {
      const pageNum = data.pageNumber;
      const totalPages = data.pageNumber || 1;

      if (pageNum > 1) {
        // Page 2+ minimal header
        drawPage2PlusHeader(doc, pageNum, meta.campaignName, `${meta.generatedDate}`);
      }

      // Draw footer on all pages
      drawFooter(doc, pageNum, totalPages);
    },
  };

  autoTable(doc, autoTableConfig);

  doc.save(`whatsapp-shield-report-${campaign.id?.substring(0, 8) || 'export'}.pdf`);
}

export function exportAllHistoryPDF(campaigns, phone, sessionUser) {
  if (!campaigns || campaigns.length === 0) return;
  const now = new Date();
  const totalRecords = campaigns.reduce((s, c) => s + (c.results?.length || 0), 0);
  const totalChecked = campaigns.reduce((s, c) => s + (c.totalChecked || 0), 0);
  const totalRegistered = campaigns.reduce((s, c) => s + (c.registeredCount || 0), 0);
  const totalUnregistered = campaigns.reduce((s, c) => s + (c.unregisteredCount || 0), 0);
  const totalInvalid = campaigns.reduce((s, c) => s + (c.invalidCount || 0), 0);
  const avgYield = totalChecked > 0 ? Math.round((totalRegistered / totalChecked) * 100) : 0;

  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 12;

  const account = sessionUser?.name || sessionUser?.number || phone || 'N/A';
  const meta = {
    exportFormat: 'PDF',
    reportTitle: 'Account History Report',
    generatedDate: now.toLocaleDateString(),
    generatedTime: now.toLocaleTimeString(),
    campaignName: `Complete Account History - ${account}`,
  };

  drawPremiumHeader(doc, meta);

  let y = 40;
  y = drawSectionTitle(doc, y, 'HISTORY SUMMARY');
  y = drawCampaignBanner(doc, y, 'Account', account);
  y += 5;

  const items = [
    { label: 'Campaigns', value: campaigns.length, color: NAVY },
    { label: 'Total Checked', value: totalChecked, color: NAVY },
    { label: 'Total Records', value: totalRecords, color: NAVY },
    { label: 'Export Format', value: 'PDF', color: NAVY },
    { label: 'Registered', value: totalRegistered, color: SUCCESS },
    { label: 'Not Registered', value: totalUnregistered, color: ERROR },
    { label: 'Invalid', value: totalInvalid, color: AMBER },
    { label: 'Average Yield', value: avgYield + '%', color: GREEN_DARK },
    { label: 'Export Date', value: meta.generatedDate + '  ' + meta.generatedTime, color: NAVY },
    { label: 'Report Type', value: 'Full Account History', color: NAVY },
    { label: 'Generated By', value: 'WhatsApp Shield', color: NAVY },
    { label: 'Account Status', value: 'All Campaigns', color: NAVY },
  ];
  y = drawStatGrid(doc, items, y);

  y += 4.5;
  y = drawSectionTitle(doc, y, 'CAMPAIGN HISTORY');
  const tableStart = y + 3.5;

  const tableData = campaigns.map((c, i) => [
    String(i + 1),
    c.id ? c.id.substring(0, 18) : 'N/A',
    new Date(c.timestamp).toLocaleDateString(),
    getCountryName(c.countryCode),
    c.shieldMode ? 'Enabled' : 'Disabled',
    String(c.totalChecked || 0),
    String(c.registeredCount || 0),
    String(c.unregisteredCount || 0),
    c.totalChecked > 0 ? Math.round((c.registeredCount / c.totalChecked) * 100) + '%' : '0%',
  ]);

  autoTable(doc, {
    startY: tableStart,
    head: [['#', 'Campaign ID', 'Date', 'Country', 'Shield', 'Total', 'Registered', 'Not Reg.', 'Yield']],
    body: tableData,
    theme: 'striped',
    showHead: 'everyPage',
    headStyles: {
      fillColor: NAVY,
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 7.5,
      cellPadding: 1.6,
    },
    styles: {
      cellPadding: 1.8,
      fontSize: 7,
      overflow: 'linebreak',
      lineColor: BORDER,
      lineWidth: 0.15,
      valign: 'middle',
    },
    alternateRowStyles: {
      fillColor: SURFACE,
    },
    columnStyles: {
      0: { cellWidth: 12, halign: 'center' },
      1: { cellWidth: 48, fontStyle: 'courier' },
      2: { cellWidth: 26 },
      3: { cellWidth: 40 },
      4: { cellWidth: 22, halign: 'center' },
      5: { cellWidth: 22, halign: 'center' },
      6: { cellWidth: 24, halign: 'center' },
      7: { cellWidth: 24, halign: 'center' },
      8: { cellWidth: 22, halign: 'center' },
    },
    didParseCell: function (data) {
      if (data.section !== 'body') return;
      if (data.column.index === 6) data.cell.styles.textColor = SUCCESS;
      if (data.column.index === 7) data.cell.styles.textColor = ERROR;
    },
    margin: { left: margin, right: margin, top: 15, bottom: 10 },
    willDrawPage: function (data) {
      const pageNum = data.pageNumber;
      const totalPages = data.pageNumber || 1;
      if (pageNum > 1) drawCompactHeader(doc, pageNum, meta.campaignName, meta.generatedDate);
      drawFooter(doc, pageNum, totalPages);
    },
  });

  doc.save(`whatsapp-shield-full-history-${phone || 'export'}.pdf`);
}
