import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { parsePhoneNumberFromString } from 'libphonenumber-js';
import { countries, getCountryByCallingCode } from '../data/countries';
import { rawFlagSvg } from './flagAssets';

const APP_NAME = 'WhatsApp Shield';
const APP_VERSION = '1.0.0';

// Brand palette
const NAVY = [15, 23, 42];
const GREEN = [0, 217, 126];
const GREEN_DARK = [0, 148, 90];
const SUCCESS = [0, 184, 110];
const ERROR = [239, 68, 68];
const AMBER = [245, 158, 11];
const SLATE = [148, 163, 184];
const SURFACE = [248, 250, 252];
const BORDER = [226, 232, 240];

export const getCountryName = (code) => {
  if (!code) return 'Unknown';
  const isoMatch = countries.find(c => c.iso.toLowerCase() === String(code).toLowerCase());
  if (isoMatch) return isoMatch.name;
  // Calling-code path: resolve shared codes deterministically (e.g. +1 → United
  // States) instead of returning the ambiguous "+1".
  const byCode = getCountryByCallingCode(code);
  if (byCode) return byCode.name;
  return code;
};

export const getCountryFlag = (code) => {
  if (!code || code === 'N/A' || code === 'Unknown') return '';
  // Prefer iso resolution; fall back to calling-code resolution so a shared
  // code like '1' renders the product default flag (US) instead of nothing.
  const byIso = countries.find(c => c.iso.toLowerCase() === String(code).toLowerCase());
  const c = byIso || getCountryByCallingCode(code);
  if (!c) return '';
  return String.fromCodePoint(...c.iso.toUpperCase().split('').map(ch => 0x1F1E6 + ch.charCodeAt(0) - 65));
};

export const getCountryFromNumber = (num) => {
  try {
    const parsed = parsePhoneNumberFromString(num);
    if (parsed && parsed.country) {
      const c = countries.find(c => c.iso.toLowerCase() === parsed.country.toLowerCase());
      return { code: parsed.country, name: c ? c.name : parsed.country };
    }
  } catch (e) {}
  return { code: 'Unknown', name: 'Unknown' };
};

const getCountryDialCode = (code) => {
  if (!code) return null;
  const c = countries.find(c => c.iso.toLowerCase() === String(code).toLowerCase());
  return c ? c.code : null;
};

function campaignDisplayName(campaign) {
  const country = campaign?.countryName || getCountryName(campaign?.countryIso || campaign?.countryCode);
  let dateStr = '';
  if (campaign?.timestamp) {
    const d = new Date(campaign.timestamp);
    if (!isNaN(d)) dateStr = d.toLocaleDateString();
  }
  return `Audience Scan - ${country}${dateStr ? ' - ' + dateStr : ''}`;
}

// Resolve a campaign's country for display/reporting, honoring the detected
// country (countryIso/countryName) ahead of any stale dial-code field.
const campaignCountryMeta = (c) => {
  const iso = c?.countryIso;
  const dial = c?.countryCode;
  const resolved = iso ? countries.find(x => x.iso.toLowerCase() === String(iso).toLowerCase()) : null;
  return {
    name: c?.countryName || (resolved ? resolved.name : getCountryName(iso || dial || '')),
    flag: getCountryFlag(iso || dial || ''),
    dial: resolved?.code || dial || '',
  };
};

function buildMetadata(campaign, filterLabel, totalRecords, format) {
  const now = new Date();
  const yieldRatio = campaign.totalChecked > 0
    ? Math.round((campaign.registeredCount / campaign.totalChecked) * 100)
    : 0;
  return {
    generatedAt: now.toISOString(),
    generatedDate: now.toLocaleDateString(),
    generatedTime: now.toLocaleTimeString(),
    appName: APP_NAME,
    appVersion: APP_VERSION,
    generatedBy: 'Generated by WhatsApp Shield',
    exportType: filterLabel || 'Full Campaign Report',
    exportFormat: format || 'PDF',
    totalRecords,
    campaignName: campaignDisplayName(campaign),
    campaign: {
      id: campaign.id,
      ref: campaign.refId || campaign.id?.substring(0, 8) || 'N/A',
      timestamp: campaign.timestamp,
      countryCode: campaign.countryIso || campaign.countryCode || 'Unknown',
      countryDialCode: campaign.countryCode || getCountryDialCode(campaign.countryIso),
      countryName: campaign.countryName || getCountryName(campaign.countryIso || campaign.countryCode || ''),
      shieldMode: campaign.shieldMode ? 'Enabled' : 'Disabled',
      delayMs: campaign.delayMs || 0,
      yieldRatio: yieldRatio + '%',
      totalChecked: campaign.totalChecked || 0,
      registeredCount: campaign.registeredCount || 0,
      unregisteredCount: campaign.unregisteredCount || 0,
      invalidCount: campaign.invalidCount || 0,
    },
  };
}

function formatRecord(r, campaign) {
  const country = r.detectedCountry || getCountryFromNumber(r.formatted || r.number || '');
  const countryName = typeof country === 'object' ? country.name : getCountryName(country);
  const countryCode = typeof country === 'object' ? country.code : country;
  const countryFlag = getCountryFlag(typeof country === 'object' ? country.code : country);
  const status = recordStatus(r);
  const accountType = r.isBusiness ? 'Business' : (r.exists === true ? 'Personal' : 'N/A');
  const ts = r.timestamp || campaign?.timestamp || new Date().toISOString();
  const d = new Date(ts);
  return {
    phoneNumber: r.formatted || r.number || '',
    originalNumber: r.number || '',
    countryCode: countryCode || 'Unknown',
    countryDialCode: getCountryDialCode(countryCode),
    countryName,
    countryFlag,
    whatsappStatus: status,
    accountType,
    isVerified: r.isVerified ? 'Yes' : 'No',
    displayName: r.displayName || r.verifiedName || 'None',
    profilePhotoAvailable: r.profilePhotoAvailable === true || !!r.avatar ? 'Yes' : 'No',
    profileImageUrl: r.avatar || '',
    verificationDate: !isNaN(d) ? d.toLocaleDateString() : (ts.split('T')[0] || ''),
    verificationTime: !isNaN(d) ? d.toLocaleTimeString() : '',
  };
}

async function fetchImageDataURL(url) {
  try {
    const res = await fetch(url, { mode: 'cors' });
    if (!res.ok) return null;
    const blob = await res.blob();
    return await new Promise((resolve) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch (e) {
    return null;
  }
}

function convertWebPToPNG(dataUrl) {
  return new Promise((resolve) => {
    try {
      const img = new Image();
      img.onload = () => {
        try {
          const canvas = document.createElement('canvas');
          canvas.width = img.naturalWidth || 64;
          canvas.height = img.naturalHeight || 64;
          canvas.getContext('2d').drawImage(img, 0, 0);
          resolve(canvas.toDataURL('image/png'));
        } catch (e) { resolve(null); }
      };
      img.onerror = () => resolve(null);
      img.src = dataUrl;
    } catch (e) { resolve(null); }
  });
}

function detectImageFormat(dataUrl) {
  if (dataUrl.startsWith('data:image/png')) return 'PNG';
  if (dataUrl.startsWith('data:image/webp')) return 'WEBP';
  return 'JPEG';
}

function escapeCSV(val) {
  const str = String(val ?? '');
  if (str.includes(',') || str.includes('"') || str.includes('\n')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

export function downloadFile(content, fileName, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/* ============================================================
   CSV EXPORT
   ============================================================ */

// Google-Contacts-style CSV row. Columns follow the History page's table:
//   Profile        -> the contact's WhatsApp display name (verifiedName preferred,
//                     displayName as fallback) — no profile picture is included
//   Phone Number   -> the number as imported/checked
//   Status         -> Registered / Not Registered / Invalid Format
//   Type           -> Business / Personal (or empty when not applicable)
//   Display Name   -> the display name recorded for this result
//   Action         -> "Add" for registered, "Skip" otherwise (import-ready)
function buildContactCSVRow(r) {
  const hasName = (v) => v && v !== 'None' && String(v).trim() !== '';
  const profile = hasName(r.verifiedName) ? r.verifiedName : (hasName(r.displayName) ? r.displayName : '');
  const type = r.isBusiness === true ? 'Business' : (r.exists === true ? 'Personal' : '');
  const displayName = hasName(r.displayName) ? r.displayName : '';
  const action = r.exists === true ? 'Add' : 'Skip';
  return [
    profile,
    r.formatted || r.number || '',
    recordStatus(r),
    type,
    displayName,
    action,
  ].map(escapeCSV).join(',');
}

const CONTACT_CSV_HEADERS = ['Profile', 'Phone Number', 'Status', 'Type', 'Display Name', 'Action'];

export function exportFilteredCSV(results, campaign, filterLabel) {
  if (!results || results.length === 0) return;
  const rows = results.map(r => buildContactCSVRow(r));
  const csv = '\uFEFF' + [CONTACT_CSV_HEADERS.join(','), ...rows].join('\n');
  downloadFile(csv, `whatsapp-shield-report-${campaign.id?.substring(0, 8) || 'export'}.csv`, 'text/csv;charset=utf-8');
}

export function exportAllHistoryCSV(campaigns, phone) {
  if (!campaigns || campaigns.length === 0) return;
  const rows = [];
  campaigns.forEach(c => {
    if (!c.results) return;
    c.results.forEach(r => { rows.push(buildContactCSVRow(r)); });
  });
  if (rows.length === 0) return;
  const csv = '\uFEFF' + [CONTACT_CSV_HEADERS.join(','), ...rows].join('\n');
  downloadFile(csv, `whatsapp-shield-all-history-${phone || 'export'}.csv`, 'text/csv;charset=utf-8');
}

/* ============================================================
   TXT EXPORT
   ============================================================ */

export function exportFilteredTXT(results, campaign, filterLabel) {
  if (!results || results.length === 0) return;
  const meta = buildMetadata(campaign, filterLabel, results.length, 'TXT');
  const lines = [];
  const sep = '='.repeat(96);
  const sep2 = '-'.repeat(96);
  const pad = (s, n) => String(s).padEnd(n);
  const rpad = (s, n) => String(s).padStart(n);

  lines.push(sep);
  lines.push('  WHATSAPP SHIELD - VALIDATION CAMPAIGN REPORT');
  lines.push(sep);
  lines.push('');
  lines.push(`  Application:      ${meta.appName} v${meta.appVersion}`);
  lines.push(`  Generated By:     WhatsApp Shield`);
  lines.push(`  Export Format:    TXT`);
  lines.push(`  Export Date:      ${meta.generatedDate} ${meta.generatedTime}`);
  lines.push(`  Export Filter:    ${filterLabel || 'All Results'}`);
  lines.push('');
  lines.push(sep2);
  lines.push('  CAMPAIGN SUMMARY');
  lines.push(sep2);
  lines.push(`  Campaign Name:    ${meta.campaignName}`);
  lines.push(`  Campaign ID:      ${meta.campaign.id}`);
  lines.push(`  Campaign Ref:     ${meta.campaign.ref}`);
  lines.push(`  Country:          ${getCountryFlag(meta.campaign.countryCode)} ${meta.campaign.countryName} (+${meta.campaign.countryDialCode || meta.campaign.countryCode})`);
  lines.push(`  Executed:         ${new Date(campaign.timestamp).toLocaleString()}`);
  lines.push(`  Shield Mode:      ${meta.campaign.shieldMode}  |  Delay: ${meta.campaign.delayMs}ms`);
  lines.push(`  Total Checked:    ${meta.campaign.totalChecked}`);
  lines.push(`  Registered:       ${meta.campaign.registeredCount}`);
  lines.push(`  Not Registered:   ${meta.campaign.unregisteredCount}`);
  lines.push(`  Invalid Format:   ${meta.campaign.invalidCount}`);
  lines.push(`  Yield Ratio:      ${meta.campaign.yieldRatio}`);
  lines.push(`  Exported Records: ${results.length}`);
  lines.push('');
  lines.push(sep2);
  lines.push('  VERIFICATION RESULTS');
  lines.push(sep2);
  lines.push('');
  lines.push(`  ${rpad('#', 4)} ${pad('Phone Number', 22)} ${pad('Country', 18)} ${pad('Status', 16)} ${pad('Type', 10)} ${pad('Display Name', 26)}`);
  lines.push(`  ${pad('', 4)} ${pad('', 22)} ${pad('', 18)} ${pad('', 16)} ${pad('', 10)} ${pad('', 26)}`);
  results.forEach((r, i) => {
    const rec = formatRecord(r, campaign);
    const statusIcon = rec.whatsappStatus === 'Registered' ? 'WA' : rec.whatsappStatus === 'Not Registered' ? '--' : '!!';
    const photo = rec.whatsappStatus === 'Registered'
      ? (rec.profilePhotoAvailable === 'Yes' ? 'Yes' : 'No Photo')
      : (rec.whatsappStatus === 'Not Registered' ? 'Not Registered' : 'N/A');
    lines.push(`  ${rpad(i + 1, 4)} ${pad(rec.phoneNumber, 22)} ${pad(getCountryFlag(rec.countryCode) + ' ' + rec.countryName, 18)} ${pad(statusIcon + ' ' + rec.whatsappStatus, 16)} ${pad(rec.accountType, 10)} ${pad(rec.displayName, 26)}`);
  });
  lines.push('');
  lines.push(sep);
  lines.push(`  End of Report | ${meta.appName} v${meta.appVersion}`);
  lines.push(`  Generated: ${meta.generatedAt}`);
  lines.push(sep);
  downloadFile(lines.join('\n'), `whatsapp-shield-report-${campaign.id?.substring(0, 8) || 'export'}.txt`, 'text/plain;charset=utf-8');
}

export function exportAllHistoryTXT(campaigns, phone) {
  if (!campaigns || campaigns.length === 0) return;
  const now = new Date();
  const lines = [];
  const sep = '='.repeat(96);
  const sep2 = '-'.repeat(96);
  const pad = (s, n) => String(s).padEnd(n);
  const rpad = (s, n) => String(s).padStart(n);

  lines.push(sep);
  lines.push('  WHATSAPP SHIELD - COMPLETE ACCOUNT HISTORY');
  lines.push(sep);
  lines.push('');
  lines.push(`  Application:      ${APP_NAME} v${APP_VERSION}`);
  lines.push(`  Generated By:     WhatsApp Shield`);
  lines.push(`  Export Format:    TXT`);
  lines.push(`  Export Date:      ${now.toLocaleDateString()} ${now.toLocaleTimeString()}`);
  const totalRecords = campaigns.reduce((s, c) => s + (c.results?.length || 0), 0);
  lines.push(`  Total Campaigns:  ${campaigns.length}`);
  lines.push(`  Total Records:    ${totalRecords}`);
  lines.push('');
  lines.push(sep2);

  campaigns.forEach((c, ci) => {
    lines.push('');
    lines.push(`  CAMPAIGN ${ci + 1} - ${campaignDisplayName(c)}`);
    lines.push(sep2);
    lines.push(`  Campaign ID:      ${c.id}`);
    lines.push(`  Date:             ${new Date(c.timestamp).toLocaleString()}`);
    const cc = campaignCountryMeta(c);
    lines.push(`  Country:          ${cc.flag} ${cc.name}${cc.dial ? ' (+' + cc.dial + ')' : ''}`);
    lines.push(`  Shield:           ${c.shieldMode ? 'Enabled' : 'Disabled'}  |  Delay: ${c.delayMs}ms`);
    lines.push(`  Total:            ${c.totalChecked}  |  Registered: ${c.registeredCount}  |  Not Registered: ${c.unregisteredCount}  |  Invalid: ${c.invalidCount}`);
    lines.push('');
    if (c.results && c.results.length > 0) {
      lines.push(`  ${rpad('#', 4)} ${pad('Phone Number', 22)} ${pad('Status', 16)} ${pad('Type', 10)} ${pad('Display Name', 26)}`);
      lines.push(`  ${pad('', 4)} ${pad('', 22)} ${pad('', 16)} ${pad('', 10)} ${pad('', 26)}`);
      c.results.forEach((r, ri) => {
        const rec = formatRecord(r, c);
        lines.push(`  ${rpad(ri + 1, 4)} ${pad(rec.phoneNumber, 22)} ${pad(rec.whatsappStatus, 16)} ${pad(rec.accountType, 10)} ${pad(rec.displayName, 26)}`);
      });
    }
    lines.push('');
    lines.push(sep2);
  });

  lines.push('');
  lines.push(sep);
  lines.push(`  End of Report | ${APP_NAME} v${APP_VERSION}`);
  lines.push(sep);
  downloadFile(lines.join('\n'), `whatsapp-shield-all-history-${phone || 'export'}.txt`, 'text/plain;charset=utf-8');
}

/* ============================================================
   JSON EXPORT
   ============================================================ */

function toRecordJSON(rec) {
  return {
    phoneNumber: rec.phoneNumber,
    originalNumber: rec.originalNumber,
    country: {
      code: rec.countryCode,
      dialCode: rec.countryDialCode ? '+' + rec.countryDialCode : null,
      name: rec.countryName,
      flag: rec.countryFlag,
    },
    whatsappStatus: rec.whatsappStatus,
    accountType: rec.accountType,
    isVerified: rec.isVerified === 'Yes',
    displayName: rec.displayName === 'None' ? null : rec.displayName,
    profile: {
      photoAvailable: rec.profilePhotoAvailable === 'Yes',
      photoUrl: rec.profileImageUrl,
    },
    verification: { date: rec.verificationDate, time: rec.verificationTime },
  };
}

export function exportFilteredJSON(results, campaign, filterLabel) {
  if (!results || results.length === 0) return;
  const meta = buildMetadata(campaign, filterLabel, results.length, 'JSON');
  const output = {
    meta: {
      appName: meta.appName,
      appVersion: meta.appVersion,
      generatedBy: meta.generatedBy,
      generatedAt: meta.generatedAt,
      exportType: meta.exportType,
      exportFormat: meta.exportFormat,
    },
    campaign: {
      id: meta.campaign.id,
      ref: meta.campaign.ref,
      name: meta.campaignName,
      timestamp: meta.campaign.timestamp,
      country: {
        code: meta.campaign.countryCode,
        dialCode: meta.campaign.countryDialCode ? '+' + meta.campaign.countryDialCode : null,
        name: meta.campaign.countryName,
      },
      shieldMode: meta.campaign.shieldMode,
      delayMs: meta.campaign.delayMs,
      yieldRatio: meta.campaign.yieldRatio,
      totalChecked: meta.campaign.totalChecked,
      registeredCount: meta.campaign.registeredCount,
      unregisteredCount: meta.campaign.unregisteredCount,
      invalidCount: meta.campaign.invalidCount,
    },
    summary: {
      totalRecords: meta.campaign.totalChecked,
      exportedRecords: results.length,
      registered: meta.campaign.registeredCount,
      notRegistered: meta.campaign.unregisteredCount,
      invalid: meta.campaign.invalidCount,
      yieldRatio: meta.campaign.yieldRatio,
    },
    records: results.map(r => toRecordJSON(formatRecord(r, campaign))),
  };
  downloadFile(JSON.stringify(output, null, 2), `whatsapp-shield-report-${campaign.id?.substring(0, 8) || 'export'}.json`, 'application/json;charset=utf-8');
}

export function exportAllHistoryJSON(campaigns, phone) {
  if (!campaigns || campaigns.length === 0) return;
  const now = new Date();
  const output = {
    meta: {
      appName: APP_NAME,
      appVersion: APP_VERSION,
      generatedBy: 'Generated by WhatsApp Shield',
      generatedAt: now.toISOString(),
      exportType: 'Full Account History',
      exportFormat: 'JSON',
      totalCampaigns: campaigns.length,
      totalRecords: campaigns.reduce((s, c) => s + (c.results?.length || 0), 0),
    },
    campaigns: campaigns.map((c) => {
      const cc = campaignCountryMeta(c);
      return {
        id: c.id,
        name: campaignDisplayName(c),
        timestamp: c.timestamp,
        country: {
          code: c.countryIso || c.countryCode,
          dialCode: cc.dial ? '+' + cc.dial : null,
          name: cc.name,
        },
        shieldMode: c.shieldMode ? 'Enabled' : 'Disabled',
        delayMs: c.delayMs,
        totalChecked: c.totalChecked,
        registeredCount: c.registeredCount,
        unregisteredCount: c.unregisteredCount,
        invalidCount: c.invalidCount,
        results: (c.results || []).map((r) => toRecordJSON(formatRecord(r, c))),
      };
    }),
  };
  downloadFile(JSON.stringify(output, null, 2), `whatsapp-shield-all-history-${phone || 'export'}.json`, 'application/json;charset=utf-8');
}


/* ============================================================
   PDF EXPORT — Shared enterprise "Campaign Verification Report"
   ------------------------------------------------------------------
   Single professional template used by BOTH the Dashboard export
   (Audit Reports → Download PDF) and the Campaign History export
   (History → Download PDF). Fixed-coordinate, mm-based, portrait
   A4, and renderer-safe for jsPDF + jspdf-autotable.
   ============================================================ */

// ---- Brand palette (RGB) --------------------------------------------------
const PDF_NAVY = [11, 15, 42];                 // #0B0F17
const PDF_EMERALD_DARK = [6, 78, 59];          // #064E3B
const PDF_EMERALD = [16, 185, 129];            // #10B981
const PDF_GREEN_600 = [5, 150, 105];           // #059669
const PDF_GREEN_700 = [4, 120, 87];            // #047857
const PDF_GREEN_800 = [21, 128, 61];           // #15803D
const PDF_GREEN_TINT = [240, 253, 244];        // #F0FDF4
const PDF_GREEN_TINT_BORDER = [220, 252, 231]; // #DCFCE7
const PDF_RED_600 = [220, 38, 38];             // #DC2626
const PDF_RED_700 = [185, 28, 28];             // #B91C1C
const PDF_RED_TINT = [254, 242, 242];          // #FEF2F2
const PDF_RED_TINT_BORDER = [254, 226, 226];   // #FEE2E2
const PDF_AMBER_700 = [180, 83, 9];            // #B45309
const PDF_AMBER_TINT = [254, 243, 199];        // #FEF3C7
const PDF_SLATE_500 = [100, 116, 139];         // #64748B
const PDF_SLATE_600 = [71, 85, 105];           // #475569
const PDF_SLATE_400 = [148, 163, 184];         // #94A3B8
const PDF_ZINC_400 = [156, 163, 175];          // #9CA3AF
const PDF_DARK = [15, 23, 42];                 // #0F172A
const PDF_BORDER = [226, 232, 240];            // #E2E8F0
const PDF_BG = [250, 250, 252];                // #FAFAFC
const PDF_WHITE = [255, 255, 255];
const PDF_HEADER_BG = [241, 245, 249];         // #F1F5F9

const PDF_PAGE_W = 210;                        // A4 portrait (mm)
const PDF_PAGE_H = 297;
const PDF_MARGIN = 10;                         // left/right content margin
const PDF_CONTENT_W = PDF_PAGE_W - 2 * PDF_MARGIN; // 190mm

const pxToMm = (px) => (px / 96) * 25.4;

function pdfFont(doc, style, size) {
  doc.setFont('helvetica', style || 'normal');
  doc.setFontSize(size || 8);
}

function fillRGB(doc, rgb) {
  doc.setFillColor(rgb[0], rgb[1], rgb[2]);
}

function drawRGB(doc, rgb) {
  doc.setDrawColor(rgb[0], rgb[1], rgb[2]);
}

function textRGB(doc, rgb) {
  doc.setTextColor(rgb[0], rgb[1], rgb[2]);
}

function clipText(doc, text, maxW) {
  const t = String(text ?? '');
  if (doc.getTextWidth(t) <= maxW) return t;
  let s = t;
  while (s.length > 1 && doc.getTextWidth(s + '…') > maxW) s = s.slice(0, -1);
  return s + '…';
}

function drawShieldLogo(doc, x, y, size) {
  doc.setFillColor(PDF_EMERALD[0], PDF_EMERALD[1], PDF_EMERALD[2]);
  doc.roundedRect(x, y, size, size, size * 0.26, size * 0.26, 'F');
  doc.setDrawColor(255, 255, 255);
  doc.setLineWidth(size * 0.11);
  doc.setLineCap('round');
  doc.line(x + size * 0.22, y + size * 0.55, x + size * 0.42, y + size * 0.75);
  doc.line(x + size * 0.42, y + size * 0.75, x + size * 0.8, y + size * 0.3);
  doc.setLineCap('butt');
  doc.setLineWidth(0.2);
}

// ---- Page 1: dark executive header ----------------------------------------
function drawPage1Header(doc, meta) {
  const H = 22;
  const strips = 24;
  fillRGB(doc, PDF_NAVY);
  doc.rect(0, 0, PDF_PAGE_W, H, 'F');
  const gradH = H - 0.6;
  for (let i = 0; i < strips; i += 1) {
    const t = i / (strips - 1);
    doc.setFillColor(
      Math.round(PDF_NAVY[0] + (PDF_EMERALD_DARK[0] - PDF_NAVY[0]) * t),
      Math.round(PDF_NAVY[1] + (PDF_EMERALD_DARK[1] - PDF_NAVY[1]) * t),
      Math.round(PDF_NAVY[2] + (PDF_EMERALD_DARK[2] - PDF_NAVY[2]) * t),
    );
    doc.rect(0, (gradH * i) / strips, PDF_PAGE_W, gradH / strips + 0.1, 'F');
  }
  // 2px vivid-emerald bottom accent line
  fillRGB(doc, PDF_EMERALD);
  doc.rect(0, H - 0.5, PDF_PAGE_W, 0.5, 'F');

  const leftX = 16;
  drawShieldLogo(doc, leftX, (H - 11) / 2, 11);
  const textX = leftX + 15;

  pdfFont(doc, 'bold', 14);
  textRGB(doc, PDF_WHITE);
  doc.text('WHATSAPP SHIELD', textX, 14);
  pdfFont(doc, 'normal', 8.5);
  textRGB(doc, PDF_ZINC_400);
  doc.text('Enterprise Audience Validation', textX, 8.5);

  const rightX = PDF_PAGE_W - 16;
  const badgeW = 13;
  const badgeH = 5.5;
  doc.setFillColor(16, 185, 129, 0.15);
  doc.setDrawColor(16, 185, 129);
  doc.setLineWidth(0.35);
  doc.roundedRect(rightX - badgeW, 4, badgeW, badgeH, 1.4, 1.4, 'FD');
  pdfFont(doc, 'bold', 8);
  textRGB(doc, PDF_WHITE);
  doc.text('[PDF]', rightX - badgeW / 2, 7.9, { align: 'center' });

  pdfFont(doc, 'bold', 11);
  textRGB(doc, PDF_WHITE);
  doc.text('Campaign Verification Report', rightX, 15.5, { align: 'right' });
  pdfFont(doc, 'normal', 8);
  textRGB(doc, PDF_SLATE_500);
  doc.text(`Exported: ${meta.exportTimestamp}`, rightX, 19.5, { align: 'right' });
}

// ---- Campaign identity card ------------------------------------------------
function drawCampaignCard(doc, meta, startY) {
  const h = 15;
  fillRGB(doc, PDF_WHITE);
  drawRGB(doc, PDF_BORDER);
  doc.setLineWidth(0.2);
  doc.roundedRect(PDF_MARGIN, startY, PDF_CONTENT_W, h, 2, 2, 'FD');
  fillRGB(doc, PDF_EMERALD);
  doc.roundedRect(PDF_MARGIN + 2.5, startY + 2.5, 1, h - 5, 0.5, 0.5, 'F');

  pdfFont(doc, 'normal', 7.5);
  textRGB(doc, PDF_SLATE_500);
  doc.text('CAMPAIGN NAME', PDF_MARGIN + 6, startY + 5.4);
  pdfFont(doc, 'bold', 13);
  textRGB(doc, PDF_DARK);
  doc.text(clipText(doc, meta.campaignName, PDF_CONTENT_W - 14), PDF_MARGIN + 6, startY + 12.4);
  return startY + h;
}

// ---- KPI micro-metric cards ------------------------------------------------
function kpiIconDash(doc, cx, cy, s) {
  fillRGB(doc, PDF_SLATE_400);
  doc.roundedRect(cx - s * 0.42, cy - s * 0.1, s * 0.84, s * 0.2, s * 0.1, s * 0.1, 'F');
}

function kpiIconCheck(doc, cx, cy, s) {
  fillRGB(doc, PDF_GREEN_600);
  doc.circle(cx, cy, s * 0.48, 'F');
  doc.setDrawColor(255, 255, 255);
  doc.setLineWidth(s * 0.14);
  doc.setLineCap('round');
  doc.line(cx - s * 0.22, cy, cx - s * 0.06, cy + s * 0.18);
  doc.line(cx - s * 0.06, cy + s * 0.18, cx + s * 0.26, cy - s * 0.2);
  doc.setLineCap('butt');
  doc.setLineWidth(0.2);
}

function kpiIconCross(doc, cx, cy, s) {
  fillRGB(doc, PDF_RED_600);
  doc.circle(cx, cy, s * 0.48, 'F');
  doc.setDrawColor(255, 255, 255);
  doc.setLineWidth(s * 0.14);
  doc.setLineCap('round');
  const d = s * 0.22;
  doc.line(cx - d, cy - d, cx + d, cy + d);
  doc.line(cx - d, cy + d, cx + d, cy - d);
  doc.setLineCap('butt');
  doc.setLineWidth(0.2);
}

function kpiIconTrend(doc, cx, cy, s) {
  fillRGB(doc, PDF_EMERALD);
  const bw = s * 0.18;
  const gap = s * 0.1;
  const base = cy + s * 0.4;
  const heights = [s * 0.22, s * 0.42, s * 0.62];
  heights.forEach((hgt, i) => {
    const bx = cx - s * 0.5 + i * (bw + gap);
    doc.rect(bx, base - hgt, bw, hgt, 'F');
  });
}

function drawKPIRow(doc, kpis, startY) {
  const gap = 2.5;
  const cardW = (PDF_CONTENT_W - 3 * gap) / 4;
  const h = 17;
  kpis.forEach((k, i) => {
    const x = PDF_MARGIN + i * (cardW + gap);
    fillRGB(doc, k.bg);
    drawRGB(doc, k.border);
    doc.setLineWidth(0.25);
    doc.roundedRect(x, startY, cardW, h, 2, 2, 'FD');

    pdfFont(doc, 'normal', 7.5);
    textRGB(doc, PDF_SLATE_500);
    doc.text(k.label, x + 5, startY + 6);

    pdfFont(doc, 'bold', 20);
    textRGB(doc, k.color);
    doc.text(String(k.value), x + 5, startY + h - 3.6);

    if (k.icon) k.icon(doc, x + cardW - 6.5, startY + 6.2, 5);
  });
  return startY + h;
}

// ---- Meta information pill bar (Country / Shield Mode / Filter) ------------
function drawMetaBar(doc, meta, startY, flagPng) {
  const h = 12;
  fillRGB(doc, PDF_WHITE);
  drawRGB(doc, PDF_BORDER);
  doc.setLineWidth(0.2);
  doc.roundedRect(PDF_MARGIN, startY, PDF_CONTENT_W, h, 2, 2, 'FD');

  const cellW = PDF_CONTENT_W / 3;
  const labelY = startY + 4.1;
  const valueY = startY + 9.7;
  const valueCenterY = valueY - 1.1;

  drawRGB(doc, PDF_BORDER);
  doc.setLineWidth(0.15);
  for (let i = 1; i < 3; i += 1) {
    const dx = PDF_MARGIN + i * cellW;
    doc.line(dx, startY + 2, dx, startY + h - 2);
  }

  // 1) Country (flag + code chip + name)
  const x1 = PDF_MARGIN + 5;
  pdfFont(doc, 'normal', 6.5);
  textRGB(doc, PDF_SLATE_500);
  doc.text('COUNTRY', x1, labelY);
  const labelW1 = doc.getTextWidth('COUNTRY');
  let cx = x1 + labelW1 + 3.5;
  if (flagPng) {
    const fw = 5.5;
    const fh = 3.7;
    const fx = cx;
    const fy = valueCenterY - fh / 2;
    try {
      doc.addImage(flagPng, 'PNG', fx, fy, fw, fh);
    } catch (e) {}
    drawRGB(doc, PDF_BORDER);
    doc.setLineWidth(0.15);
    doc.roundedRect(fx, fy, fw, fh, 0.6, 0.6, 'S');
    cx += fw + 2;
  }
  const chipW = 7;
  const chipH = 5;
  const chipX = cx;
  const chipY = valueCenterY - chipH / 2;
  fillRGB(doc, PDF_HEADER_BG);
  drawRGB(doc, PDF_BORDER);
  doc.setLineWidth(0.15);
  doc.roundedRect(chipX, chipY, chipW, chipH, 1.2, 1.2, 'FD');
  pdfFont(doc, 'bold', 6);
  textRGB(doc, PDF_SLATE_600);
  doc.text(meta.countryCode.toUpperCase(), chipX + chipW / 2, chipY + chipH / 2 + 1, { align: 'center' });

  const nameX = chipX + chipW + 2.5;
  pdfFont(doc, 'bold', 8.5);
  textRGB(doc, PDF_DARK);
  doc.text(clipText(doc, meta.countryName, cellW - 5 - (nameX - x1) - 3), nameX, valueY);

  // 2) Shield Mode
  const x2 = PDF_MARGIN + cellW + 5;
  pdfFont(doc, 'normal', 6.5);
  textRGB(doc, PDF_SLATE_500);
  doc.text('SHIELD MODE', x2, labelY);
  const labelW2 = doc.getTextWidth('SHIELD MODE');
  const badgeW = 14;
  const badgeH = 5;
  const badgeX = x2 + labelW2 + 4;
  const badgeY = valueCenterY - badgeH / 2;
  const isOn = meta.shieldMode === 'Enabled';
  fillRGB(doc, isOn ? PDF_GREEN_TINT : PDF_HEADER_BG);
  drawRGB(doc, isOn ? PDF_GREEN_TINT_BORDER : PDF_BORDER);
  doc.setLineWidth(0.15);
  doc.roundedRect(badgeX, badgeY, badgeW, badgeH, 1.2, 1.2, 'FD');
  pdfFont(doc, 'bold', 6.5);
  textRGB(doc, isOn ? PDF_GREEN_800 : PDF_SLATE_600);
  doc.text(meta.shieldMode, badgeX + badgeW / 2, badgeY + badgeH / 2 + 1.1, { align: 'center' });

  // 3) Filter Applied (with dynamic display count)
  const x3 = PDF_MARGIN + 2 * cellW + 5;
  pdfFont(doc, 'normal', 6.5);
  textRGB(doc, PDF_SLATE_500);
  doc.text('FILTER', x3, labelY);
  const labelW3 = doc.getTextWidth('FILTER');
  const countText = `${meta.filteredCount} of ${meta.campaignTotals.total}`;
  pdfFont(doc, 'normal', 5.5);
  const countW = doc.getTextWidth(countText);
  pdfFont(doc, 'bold', 8.5);
  textRGB(doc, PDF_DARK);
  doc.text(clipText(doc, meta.filterLabel, cellW - 5 - labelW3 - 10 - countW - 6), x3 + labelW3 + 4, valueY);
  pdfFont(doc, 'normal', 5.5);
  textRGB(doc, PDF_SLATE_500);
  doc.text(countText, x3 + cellW - 5, startY + 11.3, { align: 'right' });

  return startY + h;
}

// ---- Page 2+ compact continuation header -----------------------------------
function drawCompactHeader(doc, meta, pageNum) {
  const H = 10;
  fillRGB(doc, PDF_WHITE);
  doc.rect(0, 0, PDF_PAGE_W, H, 'F');
  drawRGB(doc, PDF_BORDER);
  doc.setLineWidth(0.15);
  doc.line(0, H, PDF_PAGE_W, H);

  drawShieldLogo(doc, PDF_MARGIN, (H - 5) / 2, 5);
  pdfFont(doc, 'bold', 9);
  textRGB(doc, PDF_DARK);
  doc.text('WhatsApp Shield', PDF_MARGIN + 7.5, H / 2 + 1.5);

  pdfFont(doc, 'normal', 7.5);
  textRGB(doc, PDF_SLATE_500);
  const rightText = clipText(doc, `${meta.campaignName}  ·  Exported: ${meta.exportTimestamp}`, 132);
  doc.text(rightText, PDF_PAGE_W - PDF_MARGIN, H / 2 + 1.5, { align: 'right' });
}

// ---- Footer (all pages) ------------------------------------------------------
function drawFooter(doc, pageNum) {
  drawRGB(doc, PDF_BORDER);
  doc.setLineWidth(0.15);
  doc.line(PDF_MARGIN, PDF_PAGE_H - 12, PDF_PAGE_W - PDF_MARGIN, PDF_PAGE_H - 12);
  pdfFont(doc, 'normal', 7.5);
  textRGB(doc, PDF_SLATE_400);
  doc.text('WhatsApp Shield v1.0.0', PDF_MARGIN, PDF_PAGE_H - 7);
  doc.text(`Page ${pageNum}`, PDF_PAGE_W - PDF_MARGIN, PDF_PAGE_H - 7, { align: 'right' });
}

// ---- Table cell renderers -----------------------------------------------------
function drawStatusBadge(doc, rec, x, centerY) {
  const status = recordStatus(rec);
  const { bg, fg } = statusColors(rec);
  pdfFont(doc, 'bold', 7.5);
  const w = doc.getTextWidth(status) + 6;
  const h = 5.4;
  fillRGB(doc, bg);
  drawRGB(doc, fg);
  doc.setLineWidth(0.15);
  doc.roundedRect(x, centerY - h / 2, w, h, 1.3, 1.3, 'FD');
  textRGB(doc, fg);
  doc.text(status, x + w / 2, centerY + 1.2, { align: 'center' });
}

function drawTypeCell(doc, rec, x, centerY) {
  const isBusiness = rec.isBusiness === true;
  const s = 3.4;
  if (isBusiness) {
    drawRGB(doc, PDF_SLATE_600);
    doc.setLineWidth(0.45);
    doc.roundedRect(x, centerY - s * 0.36, s * 1.2, s * 0.72, 0.6, 0.6, 'S');
    doc.line(x + s * 0.15, centerY - s * 0.36, x + s * 0.15, centerY - s * 0.36 - s * 0.18);
    doc.line(x + s * 1.05, centerY - s * 0.36, x + s * 1.05, centerY - s * 0.36 - s * 0.18);
  } else {
    fillRGB(doc, PDF_SLATE_500);
    doc.circle(x + s * 0.6, centerY - s * 0.15, s * 0.17, 'F');
    doc.roundedRect(x + s * 0.18, centerY + s * 0.05, s * 0.84, s * 0.5, s * 0.25, s * 0.25, 'F');
  }
}

function drawUserPlaceholder(doc, cx, cy, d) {
  const r = d / 2;
  fillRGB(doc, PDF_HEADER_BG);
  doc.circle(cx, cy, r, 'F');
  fillRGB(doc, PDF_ZINC_400);
  doc.circle(cx, cy - r * 0.18, r * 0.26, 'F');
  doc.roundedRect(cx - r * 0.62, cy + r * 0.02, r * 1.24, r * 0.55, r * 0.28, r * 0.28, 'F');
}

function drawAvatar(doc, dataUrl, cx, cy) {
  const d = pxToMm(22);
  const x = cx - d / 2;
  const y = cy - d / 2;
  if (dataUrl) {
    try {
      doc.addImage(dataUrl, 'PNG', x, y, d, d);
    } catch (e) {
      drawUserPlaceholder(doc, cx, cy, d);
    }
    drawRGB(doc, PDF_BORDER);
    doc.setLineWidth(0.15);
    doc.circle(cx, cy, d / 2, 'S');
  } else {
    drawUserPlaceholder(doc, cx, cy, d);
  }
}

// ---- Avatar fetching / normalization ----------------------------------------
async function fetchAvatars(records) {
  const list = new Array(records.length).fill(null);
  const concurrency = 6;
  const tasks = records.map((r, idx) => {
    const phoneDigits = String(r.cleanNumber || r.number || '').replace(/\D/g, '');
    const hasAvatar = (r.profilePhotoAvailable === true || !!(r.avatar || r.profileImageUrl)) && r.exists && phoneDigits;
    return {
      idx,
      task: hasAvatar ? fetchImageDataURL(`/api/profile-picture?phone=${phoneDigits}`) : Promise.resolve(null),
    };
  });
  for (let start = 0; start < tasks.length; start += concurrency) {
    const batch = tasks.slice(start, start + concurrency);
    const settled = await Promise.all(batch.map((b) => b.task));
    batch.forEach((b, i) => {
      list[b.idx] = settled[i] || null;
    });
  }
  const out = new Array(records.length).fill(null);
  await Promise.all(
    list.map(async (src, i) => {
      if (!src) return;
      out[i] = await normalizeAvatarDataURL(src);
    }),
  );
  return out;
}

function normalizeAvatarDataURL(dataUrl) {
  return new Promise((resolve) => {
    try {
      const img = new Image();
      img.onload = () => {
        try {
          const size = 22;
          const canvas = document.createElement('canvas');
          canvas.width = size;
          canvas.height = size;
          const ctx = canvas.getContext('2d');
          const srcW = img.naturalWidth || size;
          const srcH = img.naturalHeight || size;
          const scale = Math.max(size / srcW, size / srcH);
          const sw = size / scale;
          const sh = size / scale;
          const sx = (srcW - sw) / 2;
          const sy = (srcH - sh) / 2;
          ctx.drawImage(img, sx, sy, sw, sh, 0, 0, size, size);
          // Pre-mask the avatar as a circle so the PDF needs no doc-level
          // clipping (which could leave an unbalanced graphics state).
          ctx.globalCompositeOperation = 'destination-in';
          ctx.beginPath();
          ctx.arc(size / 2, size / 2, size / 2, 0, Math.PI * 2);
          ctx.fill();
          ctx.globalCompositeOperation = 'source-over';
          resolve(canvas.toDataURL('image/png'));
        } catch (e) {
          resolve(dataUrl);
        }
      };
      img.onerror = () => resolve(null);
      img.src = dataUrl;
    } catch (e) {
      resolve(null);
    }
  });
}

// ---- Data helpers ---------------------------------------------------------------
function formatExportTimestamp(date) {
  return `${date.toLocaleDateString()} ${date.toLocaleTimeString()}`;
}

export function filterKeyFromLabel(label) {
  const l = String(label || '').toLowerCase();
  if (l.startsWith('not registered')) return 'unregistered';
  if (l.startsWith('registered')) return 'registered';
  if (l.startsWith('invalid')) return 'invalid';
  if (l.includes('business')) return 'business';
  if (l.includes('consumer')) return 'consumer';
  return 'all';
}

export function recordStatusKey(rec) {
  if (rec?.exists === true) return 'registered';
  if (rec?.isValidFormat === false) return 'invalid';
  return 'unregistered';
}

export function recordStatus(rec) {
  const key = recordStatusKey(rec);
  return key === 'registered' ? 'Registered' : key === 'invalid' ? 'Invalid Format' : 'Not Registered';
}

export function applyReportFilter(records, filterKey) {
  if (!Array.isArray(records)) return [];
  if (filterKey === 'registered') return records.filter((r) => recordStatusKey(r) === 'registered');
  if (filterKey === 'unregistered') return records.filter((r) => recordStatusKey(r) === 'unregistered');
  if (filterKey === 'invalid') return records.filter((r) => recordStatusKey(r) === 'invalid');
  if (filterKey === 'business') return records.filter((r) => r.isBusiness === true);
  if (filterKey === 'consumer') return records.filter((r) => r.isBusiness !== true);
  return records;
}

export function computeTotals(records) {
  let registered = 0;
  let notRegistered = 0;
  let invalid = 0;
  (records || []).forEach((r) => {
    const key = recordStatusKey(r);
    if (key === 'registered') registered += 1;
    else if (key === 'unregistered') notRegistered += 1;
    else invalid += 1;
  });
  return { total: records.length, registered, notRegistered, invalid };
}

export function countryOfRecord(rec) {
  const iso = String(rec?.detectedCountry || '').trim();
  if (iso && iso !== 'Unknown' && iso !== 'N/A') {
    return { code: iso.toUpperCase(), name: getCountryName(iso), dialCode: getCountryDialCode(iso) };
  }
  const fromNumber = getCountryFromNumber(rec?.formatted || rec?.number || '');
  if (fromNumber && fromNumber.code && fromNumber.code !== 'Unknown') {
    return { code: fromNumber.code, name: fromNumber.name, dialCode: getCountryDialCode(fromNumber.code) };
  }
  return { code: 'Unknown', name: 'Unknown', dialCode: null };
}

export function buildCountryGroups(records) {
  const map = new Map();
  (records || []).forEach((r) => {
    const c = countryOfRecord(r);
    if (!map.has(c.code)) map.set(c.code, { ...c, records: [] });
    map.get(c.code).records.push(r);
  });
  const groups = Array.from(map.values());
  groups.sort((a, b) => b.records.length - a.records.length || a.name.localeCompare(b.name));
  return groups;
}

function isValidContactRecord(rec) {
  if (!rec || rec.from === 'them') return false;
  const num = String(rec?.formatted || rec?.number || rec?.cleanNumber || '').trim();
  if (!num) return false;
  const digits = num.replace(/\D/g, '');
  return digits.length >= 7 && digits.length <= 15;
}

export function buildPdfModel(records, filterLabel, opts) {
  const filterKey = filterKeyFromLabel(filterLabel);
  const valid = (Array.isArray(records) ? records : []).filter(isValidContactRecord);
  // When records arrive pre-filtered (the caller already applied the status +
  // search filter), only drop non-contact records — never re-filter.
  const source = opts?.prefiltered ? valid : applyReportFilter(valid, filterKey);

  // Campaign-level totals always come from the FULL campaign dataset, never from
  // the filtered subset, so the KPI summary stays intact regardless of filter.
  const campaignRecords = (opts?.campaignRecords && Array.isArray(opts.campaignRecords))
    ? opts.campaignRecords.filter(isValidContactRecord)
    : valid;
  const totals = computeTotals(campaignRecords);
  const yieldRatio = totals.total > 0 ? Math.round((totals.registered / totals.total) * 100) : 0;
  const countries = buildCountryGroups(source);
  return { filterKey, records: source, totals, yieldRatio, countries, filteredCount: source.length };
}

function statusLabel(rec) {
  return recordStatus(rec);
}

function statusColors(rec) {
  const key = recordStatusKey(rec);
  if (key === 'registered') return { bg: PDF_GREEN_TINT, fg: PDF_GREEN_800 };
  if (key === 'invalid') return { bg: PDF_AMBER_TINT, fg: PDF_AMBER_700 };
  return { bg: PDF_RED_TINT, fg: PDF_RED_700 };
}

function recordKey(rec) {
  return String(rec?.cleanNumber || rec?.number || rec?.formatted || '');
}

function buildTableRow(rec, index) {
  let phone = rec.formatted || rec.number || '';
  if (phone && !phone.startsWith('+')) phone = `+${phone}`;
  const dispName = rec.displayName || rec.verifiedName || '';
  return [
    String(index),
    phone,
    statusLabel(rec),
    rec.isBusiness ? 'Business' : 'Consumer',
    dispName && dispName !== 'None' ? dispName : '-',
    '',
  ];
}

// ---- Flag rasterization (browser-only; Node falls back to ISO chips) ----------
const flagPngCache = {};

async function rasterizeFlag(code) {
  const svg = rawFlagSvg(code);
  if (!svg || typeof document === 'undefined') return null;
  try {
    // Give the SVG explicit intrinsic dimensions (from its viewBox) so
    // browsers rasterize it at the correct 3:2 aspect ratio.
    const view = svg.match(/viewBox="([\d.]+)[\s,]+([\d.]+)[\s,]+([\d.]+)[\s,]+([\d.]+)"/);
    const vw = view ? parseFloat(view[3]) : 640;
    const vh = view ? parseFloat(view[4]) : 480;
    const fixed = svg.replace(/<svg([^>]*)>/, (m, attrs) => {
      const addW = !/\bwidth\s*=/.test(attrs);
      const addH = !/\bheight\s*=/.test(attrs);
      return `<svg${attrs}${addW ? ` width="${vw}"` : ''}${addH ? ` height="${vh}"` : ''}>`;
    });
    const size = 96;
    const canvas = document.createElement('canvas');
    canvas.width = size;
    canvas.height = Math.round((size * vh) / vw);
    const ctx = canvas.getContext('2d');
    const img = new Image();
    const url = URL.createObjectURL(new Blob([fixed], { type: 'image/svg+xml' }));
    await new Promise((resolve, reject) => {
      img.onload = resolve;
      img.onerror = reject;
      img.src = url;
    });
    ctx.drawImage(img, 0, 0, size, canvas.height);
    URL.revokeObjectURL(url);
    // Pre-mask the flag as a rounded rectangle so the PDF needs no doc-level
    // clipping (which could leave an unbalanced graphics state).
    const r = Math.round(size * 0.12);
    const mask = document.createElement('canvas');
    mask.width = size;
    mask.height = canvas.height;
    const mctx = mask.getContext('2d');
    mctx.beginPath();
    mctx.moveTo(r, 0);
    mctx.arcTo(size, 0, size, canvas.height, r);
    mctx.arcTo(size, canvas.height, 0, canvas.height, r);
    mctx.arcTo(0, canvas.height, 0, 0, r);
    mctx.arcTo(0, 0, size, 0, r);
    mctx.closePath();
    mctx.fill();
    mctx.globalCompositeOperation = 'source-in';
    mctx.drawImage(canvas, 0, 0);
    return mask.toDataURL('image/png');
  } catch (e) {
    return null;
  }
}

async function getFlagPng(code) {
  if (!code || code === 'Unknown') return null;
  const key = code.toUpperCase();
  if (key in flagPngCache) return flagPngCache[key];
  const png = await rasterizeFlag(key);
  flagPngCache[key] = png || null;
  return flagPngCache[key];
}

// ---- Verification Results section heading ------------------------------------
function drawSectionHeading(doc, title, subtitle, startY) {
  fillRGB(doc, PDF_EMERALD);
  doc.roundedRect(PDF_MARGIN, startY, 2, 6, 0.8, 0.8, 'F');
  pdfFont(doc, 'bold', 12.5);
  textRGB(doc, PDF_DARK);
  doc.text(title, PDF_MARGIN + 5, startY + 4.6);
  if (subtitle) {
    pdfFont(doc, 'normal', 8);
    textRGB(doc, PDF_SLATE_500);
    doc.text(subtitle, PDF_MARGIN + 5, startY + 8.4);
  }
  return startY + (subtitle ? 12 : 9);
}

function drawFlagFallback(doc, code, x, y, w, h) {
  fillRGB(doc, PDF_HEADER_BG);
  drawRGB(doc, PDF_BORDER);
  doc.setLineWidth(0.2);
  doc.roundedRect(x, y, w, h, 1, 1, 'FD');
  pdfFont(doc, 'bold', 7);
  textRGB(doc, PDF_SLATE_600);
  doc.text(clipText(doc, code, w - 2), x + w / 2, y + h / 2 + 1.1, { align: 'center' });
}

function drawCountryBanner(doc, group, index, total, startY, flagPng) {
  const h = 17;
  fillRGB(doc, PDF_WHITE);
  drawRGB(doc, PDF_BORDER);
  doc.setLineWidth(0.25);
  doc.roundedRect(PDF_MARGIN, startY, PDF_CONTENT_W, h, 2, 2, 'FD');
  fillRGB(doc, PDF_EMERALD);
  doc.roundedRect(PDF_MARGIN + 2, startY + 2, 1.2, h - 4, 0.5, 0.5, 'F');

  const fw = 12;
  const fh = 8;
  const fx = PDF_MARGIN + 6;
  const nameBaseline = startY + 9.4;
  // Align the flag's vertical center with the country name's glyph center.
  const fy = (nameBaseline - 0.35 * pxToMm(12)) - fh / 2;
  if (flagPng) {
    try {
      doc.addImage(flagPng, 'PNG', fx, fy, fw, fh);
      drawRGB(doc, PDF_BORDER);
      doc.setLineWidth(0.15);
      doc.roundedRect(fx, fy, fw, fh, 1, 1, 'S');
    } catch (e) {
      drawFlagFallback(doc, group.code, fx, fy, fw, fh);
    }
  } else {
    drawFlagFallback(doc, group.code, fx, fy, fw, fh);
  }

  const tx = fx + fw + 3;
  pdfFont(doc, 'normal', 6.5);
  textRGB(doc, PDF_SLATE_400);
  doc.text(`SECTION ${index} OF ${total}`, tx, startY + 4.6);
  pdfFont(doc, 'bold', 12);
  textRGB(doc, PDF_DARK);
  doc.text(clipText(doc, group.name, 44), tx, startY + 9.4);

  if (group.dialCode) {
    pdfFont(doc, 'bold', 6.5);
    textRGB(doc, PDF_SLATE_600);
    fillRGB(doc, PDF_HEADER_BG);
    drawRGB(doc, PDF_BORDER);
    doc.setLineWidth(0.15);
    doc.roundedRect(tx, startY + 11.4, 13, 4, 1, 1, 'FD');
    doc.text(`+${group.dialCode}`, tx + 6.5, startY + 13.9, { align: 'center' });
  }

  return startY + h;
}

// ---- Report metadata ----------------------------------------------------------
function buildPdfMeta(records, filterLabel, opts) {
  const model = buildPdfModel(records, filterLabel, opts);
  const campaignRecords = (opts?.campaignRecords && Array.isArray(opts.campaignRecords))
    ? opts.campaignRecords.filter(isValidContactRecord)
    : model.records;
  // Primary country comes from the FULL campaign dataset, never the filtered
  // subset, so the COUNTRY summary stays correct under any filter.
  const fullCountries = buildCountryGroups(campaignRecords);
  const primary = fullCountries[0];
  const fallbackCode = opts?.countryCode;
  const code = primary ? primary.code : (fallbackCode || 'Unknown');
  const countryName = primary ? primary.name : getCountryName(code);
  let campaignName = opts?.campaignName;
  if (!campaignName) {
    let dateStr = '';
    if (opts?.campaign?.timestamp) {
      const d = new Date(opts.campaign.timestamp);
      if (!isNaN(d)) dateStr = d.toLocaleDateString();
    }
    campaignName = `Audience Scan - ${countryName}${dateStr ? ' - ' + dateStr : ''}`;
  }
  return {
    campaignName,
    countryCode: code,
    countryName,
    primaryDialCode: primary ? primary.dialCode : getCountryDialCode(code),
    shieldMode: opts?.shieldMode ? 'Enabled' : 'Disabled',
    filterLabel: filterLabel || 'All Results',
    exportTimestamp: formatExportTimestamp(new Date()),
    filterKey: model.filterKey,
    campaignTotals: model.totals,
    campaignYield: model.yieldRatio,
    filteredCount: model.filteredCount,
  };
}

// ---- Per-country results table -------------------------------------------------
function renderCountryTable(ctx, group, startY, photoByKey) {
  const { doc, meta, preparedPages } = ctx;
  const headers = ['#', 'Phone Number', 'Status', 'Type', 'Display Name', 'Profile'];
  const body = group.records.map((rec, i) => buildTableRow(rec, i + 1));

  autoTable(doc, {
    startY,
    head: [headers],
    body,
    showHead: 'everyPage',
    theme: 'plain',
    tableLineColor: PDF_BORDER,
    tableLineWidth: 0.15,
    margin: { left: PDF_MARGIN, right: PDF_MARGIN, top: 13, bottom: 14 },
    styles: {
      font: 'helvetica',
      fontStyle: 'normal',
      fontSize: 8.5,
      cellPadding: { top: 3, right: 3, bottom: 3, left: 3 },
      textColor: PDF_DARK,
      lineColor: PDF_BORDER,
      lineWidth: 0.15,
      valign: 'middle',
      overflow: 'linebreak',
      minCellHeight: 11,
    },
    headStyles: {
      fillColor: PDF_HEADER_BG,
      textColor: PDF_SLATE_600,
      fontStyle: 'bold',
      fontSize: 8,
      halign: 'left',
      valign: 'middle',
      cellPadding: { top: 3, right: 3, bottom: 3, left: 3 },
      minCellHeight: 9,
    },
    columnStyles: {
      0: { cellWidth: PDF_CONTENT_W * 0.09, halign: 'center', textColor: PDF_SLATE_600, fontSize: 7.5, cellPadding: { top: 3, right: 1, bottom: 3, left: 1 } },
      1: { cellWidth: PDF_CONTENT_W * 0.23, font: 'courier', fontStyle: 'normal', fontSize: 8.5, textColor: PDF_DARK, halign: 'left' },
      2: { cellWidth: PDF_CONTENT_W * 0.17, halign: 'left', fontSize: 7.5, fontStyle: 'bold' },
      3: { cellWidth: PDF_CONTENT_W * 0.2, halign: 'left', fontSize: 8 },
      4: { cellWidth: PDF_CONTENT_W * 0.19, halign: 'left', fontSize: 8 },
      5: { cellWidth: PDF_CONTENT_W * 0.12, halign: 'center', fontSize: 8 },
    },
    didParseCell: (data) => {
      if (data.section !== 'body') return;
      data.cell.styles.fillColor = data.row.index % 2 === 1 ? PDF_BG : PDF_WHITE;
      if (data.column.index === 2) {
        const rec = group.records[data.row.index];
        if (rec) data.cell.styles.textColor = statusColors(rec).fg;
        // Custom badge drawn in didDrawCell; suppress autoTable's raw text so
        // the status is not drawn twice (duplicate text in the PDF layer).
        data.cell.text = [''];
      }
      if (data.column.index === 3) {
        data.cell.styles.cellPadding = { top: 2, right: 3, bottom: 2, left: 7.5 };
        // Icon drawn in didDrawCell; the Business/Consumer label stays as the
        // cell's single raw text (not duplicated).
      }
      if (data.column.index === 5) {
        // Avatar drawn in didDrawCell; ensure no raw text is drawn.
        data.cell.text = [''];
      }
      if (data.column.index === 4 && String(data.cell.raw) === '-') {
        data.cell.styles.textColor = PDF_SLATE_500;
      }
    },
    didDrawCell: (data) => {
      if (data.section !== 'body') return;
      const rec = group.records[data.row.index];
      if (!rec) return;
      const centerY = data.cell.y + data.cell.height / 2;
      try {
        if (data.column.index === 2) drawStatusBadge(doc, rec, data.cell.x + 2, centerY);
        else if (data.column.index === 3) drawTypeCell(doc, rec, data.cell.x + 2.5, centerY);
        else if (data.column.index === 5) drawAvatar(doc, photoByKey.get(recordKey(rec)), data.cell.x + data.cell.width / 2, centerY);
      } catch (e) {}
    },
    willDrawPage: (data) => {
      // data.pageNumber is autoTable's INTERNAL page counter (resets to 1 for
      // every autoTable() call); use the real jsPDF page number for footer,
      // compact header and dedup of manually-prepared section pages.
      const p = doc.getNumberOfPages();
      if (preparedPages.has(p)) return;
      if (p > 1) drawCompactHeader(doc, meta, p);
      drawFooter(doc, p);
    },
  });

  const last = doc.lastAutoTable;
  return last ? last.finalY : startY;
}

// ---- Shared report builder (used by Dashboard AND History) --------------------
async function exportCampaignReportPDF(meta, records, fileName, opts) {
  const model = buildPdfModel(records, meta.filterLabel, opts);
  if (!model.records.length) return;

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  doc.setProperties({
    title: 'WhatsApp Shield - Campaign Verification Report',
    subject: meta.campaignName,
    creator: 'WhatsApp Shield',
    author: 'WhatsApp Shield',
  });

  drawPage1Header(doc, meta);
  let y = 22 + 7;
  y = drawCampaignCard(doc, meta, y);
  y += 3.5;
  y = drawKPIRow(doc, [
    { label: 'TOTAL CHECKED', value: model.totals.total, color: PDF_DARK, bg: PDF_WHITE, border: PDF_BORDER, icon: kpiIconDash },
    { label: 'REGISTERED', value: model.totals.registered, color: PDF_GREEN_600, bg: PDF_GREEN_TINT, border: PDF_GREEN_TINT_BORDER, icon: kpiIconCheck },
    { label: 'NOT REGISTERED', value: model.totals.notRegistered, color: PDF_RED_600, bg: PDF_RED_TINT, border: PDF_RED_TINT_BORDER, icon: kpiIconCross },
    { label: 'YIELD RATIO', value: `${model.yieldRatio}%`, color: PDF_GREEN_700, bg: PDF_WHITE, border: PDF_BORDER, icon: kpiIconTrend },
  ], y);
  y += 3.5;
  y = drawMetaBar(doc, meta, y, await getFlagPng(meta.countryCode));
  y += 5;
  y = drawSectionHeading(doc, 'Verification Results', `${meta.filterLabel}  ·  ${model.records.length} verified numbers`, y);
  y += 2;

  const photoDataList = await fetchAvatars(model.records);
  const photoByKey = new Map();
  model.records.forEach((r, i) => {
    if (photoDataList[i]) photoByKey.set(recordKey(r), photoDataList[i]);
  });

  const preparedPages = new Set();
  const ctx = { doc, meta, preparedPages };

  for (let i = 0; i < model.countries.length; i += 1) {
    const group = model.countries[i];
    if (i > 0) {
      doc.addPage();
      const p = doc.getNumberOfPages();
      preparedPages.add(p);
      drawCompactHeader(doc, meta, p);
      drawFooter(doc, p);
      y = 24;
    }
    const flagPng = await getFlagPng(group.code);
    y = drawCountryBanner(doc, group, i + 1, model.countries.length, y, flagPng);
    y = renderCountryTable(ctx, group, y, photoByKey) + 6;
  }

  doc.save(fileName);
}

// ---- Public entry points --------------------------------------------------------

/**
 * Dashboard + History single-campaign export.
 * Receives the CURRENT filtered results, campaign and filter — never hardcodes data.
 * The dataset is always re-derived from the selected campaign's own records so the
 * KPI summary, country, filter and table rows stay synchronized with that campaign.
 */
export async function exportFilteredPDF(results, campaign, sessionUser, filterLabel) {
  if (!results || results.length === 0) return;
  const label = filterLabel || 'All Results';
  const key = filterKeyFromLabel(label);
  const campaignRecords = Array.isArray(campaign?.results) && campaign.results.length > 0 ? campaign.results : null;
  let dataset;
  if (campaignRecords) {
    dataset = key === 'all' ? campaignRecords.slice() : applyReportFilter(campaignRecords, key);
    const searchMatch = label.match(/"([^"]*)"/);
    const term = searchMatch ? searchMatch[1].toLowerCase() : '';
    if (term) {
      dataset = dataset.filter((r) => {
        const num = String(r.formatted || r.number || '').toLowerCase();
        const name = String(r.displayName || r.verifiedName || '').toLowerCase();
        return num.includes(term) || name.includes(term);
      });
    }
    if (dataset.length === 0) return;
  } else {
    dataset = results;
  }
  const meta = buildPdfMeta(dataset, label, {
    campaign,
    countryCode: campaign?.countryCode,
    shieldMode: campaign?.shieldMode,
    campaignRecords,
  });
  const fileName = `whatsapp-shield-report-${campaign?.id?.substring(0, 8) || 'export'}.pdf`;
  await exportCampaignReportPDF(meta, dataset, fileName, {
    prefiltered: true,
    campaignRecords,
  });
}

/**
 * History "Export All" — aggregates the selected history dataset into the same
 * shared professional Campaign Verification Report template.
 */
export async function exportAllHistoryPDF(campaigns, phone, sessionUser) {
  if (!campaigns || campaigns.length === 0) return;
  const account = sessionUser?.name || sessionUser?.number || phone || 'N/A';
  const records = [];
  campaigns.forEach((c) => {
    if (c.results) records.push(...c.results);
  });
  const meta = buildPdfMeta(records, `All Campaigns (${campaigns.length})`, {
    campaignName: `Complete Account History - ${account}`,
    shieldMode: campaigns.some((c) => c.shieldMode),
  });
  const fileName = `whatsapp-shield-full-history-${phone || 'export'}.pdf`;
  await exportCampaignReportPDF(meta, records, fileName);
}

