import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { parsePhoneNumberFromString } from 'libphonenumber-js';
import { countries } from '../data/countries';

const APP_NAME = 'WhatsApp Shield';
const APP_VERSION = '1.0.0';

// Brand palette
const NAVY = [15, 23, 42];
const GREEN = [0, 217, 126];
const GREEN_DARK = [0, 148, 90];
const SUCCESS = [0, 184, 110];
const ERROR = [239, 68, 68];
const AMBER = [245, 158, 11];
const SLATE = [148, 163, 184];
const SURFACE = [248, 250, 252];
const BORDER = [226, 232, 240];

export const getCountryName = (code) => {
  if (!code) return 'Unknown';
  const c = countries.find(c => c.iso.toLowerCase() === code.toLowerCase() || c.code === code);
  return c ? c.name : code;
};

export const getCountryFlag = (code) => {
  if (!code || code === 'N/A' || code === 'Unknown') return '';
  const c = countries.find(c => c.iso.toLowerCase() === code.toLowerCase());
  if (!c) return '';
  return String.fromCodePoint(...c.iso.toUpperCase().split('').map(ch => 0x1F1E6 + ch.charCodeAt(0) - 65));
};

export const getCountryFromNumber = (num) => {
  try {
    const parsed = parsePhoneNumberFromString(num);
    if (parsed && parsed.country) {
      const c = countries.find(c => c.iso.toLowerCase() === parsed.country.toLowerCase());
      return { code: parsed.country, name: c ? c.name : parsed.country };
    }
  } catch (e) {}
  return { code: 'Unknown', name: 'Unknown' };
};

const getCountryDialCode = (code) => {
  if (!code) return null;
  const c = countries.find(c => c.iso.toLowerCase() === String(code).toLowerCase());
  return c ? c.code : null;
};

function campaignDisplayName(campaign) {
  const country = getCountryName(campaign?.countryCode);
  let dateStr = '';
  if (campaign?.timestamp) {
    const d = new Date(campaign.timestamp);
    if (!isNaN(d)) dateStr = d.toLocaleDateString();
  }
  return `Audience Scan - ${country}${dateStr ? ' - ' + dateStr : ''}`;
}

function buildMetadata(campaign, filterLabel, totalRecords, format) {
  const now = new Date();
  const yieldRatio = campaign.totalChecked > 0
    ? Math.round((campaign.registeredCount / campaign.totalChecked) * 100)
    : 0;
  return {
    generatedAt: now.toISOString(),
    generatedDate: now.toLocaleDateString(),
    generatedTime: now.toLocaleTimeString(),
    appName: APP_NAME,
    appVersion: APP_VERSION,
    generatedBy: 'Generated by WhatsApp Shield',
    exportType: filterLabel || 'Full Campaign Report',
    exportFormat: format || 'PDF',
    totalRecords,
    campaignName: campaignDisplayName(campaign),
    campaign: {
      id: campaign.id,
      ref: campaign.id?.substring(0, 8) || 'N/A',
      timestamp: campaign.timestamp,
      countryCode: campaign.countryCode || 'Unknown',
      countryDialCode: getCountryDialCode(campaign.countryCode),
      countryName: getCountryName(campaign.countryCode),
      shieldMode: campaign.shieldMode ? 'Enabled' : 'Disabled',
      delayMs: campaign.delayMs || 0,
      yieldRatio: yieldRatio + '%',
      totalChecked: campaign.totalChecked || 0,
      registeredCount: campaign.registeredCount || 0,
      unregisteredCount: campaign.unregisteredCount || 0,
      invalidCount: campaign.invalidCount || 0,
    },
  };
}

function formatRecord(r, campaign) {
  const country = r.detectedCountry || getCountryFromNumber(r.formatted || r.number || '');
  const countryName = typeof country === 'object' ? country.name : getCountryName(country);
  const countryCode = typeof country === 'object' ? country.code : country;
  const countryFlag = getCountryFlag(typeof country === 'object' ? country.code : country);
  const status = r.exists ? 'Registered' : (r.isValidFormat ? 'Not Registered' : 'Invalid Format');
  const accountType = r.isBusiness ? 'Business' : (r.exists ? 'Personal' : 'N/A');
  const ts = r.timestamp || campaign?.timestamp || new Date().toISOString();
  const d = new Date(ts);
  return {
    phoneNumber: r.formatted || r.number || '',
    originalNumber: r.number || '',
    countryCode: countryCode || 'Unknown',
    countryDialCode: getCountryDialCode(countryCode),
    countryName,
    countryFlag,
    whatsappStatus: status,
    accountType,
    isVerified: r.isVerified ? 'Yes' : 'No',
    displayName: r.displayName || r.verifiedName || 'None',
    profilePhotoAvailable: r.avatar ? 'Yes' : 'No',
    profileImageUrl: r.avatar || '',
    verificationDate: !isNaN(d) ? d.toLocaleDateString() : (ts.split('T')[0] || ''),
    verificationTime: !isNaN(d) ? d.toLocaleTimeString() : '',
  };
}

async function fetchImageDataURL(url) {
  try {
    const res = await fetch(url, { mode: 'cors' });
    if (!res.ok) return null;
    const blob = await res.blob();
    return await new Promise((resolve) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch (e) {
    return null;
  }
}

function convertWebPToPNG(dataUrl) {
  return new Promise((resolve) => {
    try {
      const img = new Image();
      img.onload = () => {
        try {
          const canvas = document.createElement('canvas');
          canvas.width = img.naturalWidth || 64;
          canvas.height = img.naturalHeight || 64;
          canvas.getContext('2d').drawImage(img, 0, 0);
          resolve(canvas.toDataURL('image/png'));
        } catch (e) { resolve(null); }
      };
      img.onerror = () => resolve(null);
      img.src = dataUrl;
    } catch (e) { resolve(null); }
  });
}

function detectImageFormat(dataUrl) {
  if (dataUrl.startsWith('data:image/png')) return 'PNG';
  if (dataUrl.startsWith('data:image/webp')) return 'WEBP';
  return 'JPEG';
}

function escapeCSV(val) {
  const str = String(val ?? '');
  if (str.includes(',') || str.includes('"') || str.includes('\n')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

export function downloadFile(content, fileName, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/* ============================================================
   CSV EXPORT
   ============================================================ */

function buildCSVRow(r, campaign, index) {
  const rec = formatRecord(r, campaign);
  let countryCell;
  if (rec.countryFlag && rec.countryDialCode) {
    countryCell = rec.countryFlag + ' +' + rec.countryDialCode;
  } else if (rec.countryCode && rec.countryCode !== 'Unknown') {
    countryCell = rec.countryCode;
  } else {
    countryCell = 'N/A';
  }
  let profilePhoto = rec.profileImageUrl;
  if (!profilePhoto) {
    if (rec.whatsappStatus === 'Not Registered') profilePhoto = 'Not Registered';
    else if (rec.whatsappStatus === 'Invalid Format') profilePhoto = 'N/A';
    else profilePhoto = 'No Profile Photo';
  }
  return [
    String(index),
    countryCell,
    rec.phoneNumber,
    rec.whatsappStatus,
    rec.accountType,
    rec.displayName === 'None' ? '' : rec.displayName,
    rec.isVerified,
    profilePhoto,
  ].map(escapeCSV).join(',');
}

export function exportFilteredCSV(results, campaign, filterLabel) {
  if (!results || results.length === 0) return;
  const headers = [
    '#', 'Country (Flag + Country Code)', 'Phone Number', 'Status', 'Type', 'Display Name', 'Verified', 'Profile Photo',
  ];
  const rows = results.map((r, i) => buildCSVRow(r, campaign, i + 1));
  const csv = '\uFEFF' + [headers.join(','), ...rows].join('\n');
  downloadFile(csv, `whatsapp-shield-report-${campaign.id?.substring(0, 8) || 'export'}.csv`, 'text/csv;charset=utf-8');
}

export function exportAllHistoryCSV(campaigns, phone) {
  if (!campaigns || campaigns.length === 0) return;
  const headers = [
    '#', 'Country (Flag + Country Code)', 'Phone Number', 'Status', 'Type', 'Display Name', 'Verified', 'Profile Photo',
  ];
  const rows = [];
  let counter = 0;
  campaigns.forEach(c => {
    if (!c.results) return;
    c.results.forEach(r => {
      counter += 1;
      rows.push(buildCSVRow(r, c, counter));
    });
  });
  if (rows.length === 0) return;
  const csv = '\uFEFF' + [headers.join(','), ...rows].join('\n');
  downloadFile(csv, `whatsapp-shield-all-history-${phone || 'export'}.csv`, 'text/csv;charset=utf-8');
}

/* ============================================================
   TXT EXPORT
   ============================================================ */

export function exportFilteredTXT(results, campaign, filterLabel) {
  if (!results || results.length === 0) return;
  const meta = buildMetadata(campaign, filterLabel, results.length, 'TXT');
  const lines = [];
  const sep = '='.repeat(96);
  const sep2 = '-'.repeat(96);
  const pad = (s, n) => String(s).padEnd(n);
  const rpad = (s, n) => String(s).padStart(n);

  lines.push(sep);
  lines.push('  WHATSAPP SHIELD - VALIDATION CAMPAIGN REPORT');
  lines.push(sep);
  lines.push('');
  lines.push(`  Application:      ${meta.appName} v${meta.appVersion}`);
  lines.push(`  Generated By:     WhatsApp Shield`);
  lines.push(`  Export Format:    TXT`);
  lines.push(`  Export Date:      ${meta.generatedDate} ${meta.generatedTime}`);
  lines.push(`  Export Filter:    ${filterLabel || 'All Results'}`);
  lines.push('');
  lines.push(sep2);
  lines.push('  CAMPAIGN SUMMARY');
  lines.push(sep2);
  lines.push(`  Campaign Name:    ${meta.campaignName}`);
  lines.push(`  Campaign ID:      ${meta.campaign.id}`);
  lines.push(`  Campaign Ref:     ${meta.campaign.ref}`);
  lines.push(`  Country:          ${getCountryFlag(meta.campaign.countryCode)} ${meta.campaign.countryName} (+${meta.campaign.countryDialCode || meta.campaign.countryCode})`);
  lines.push(`  Executed:         ${new Date(campaign.timestamp).toLocaleString()}`);
  lines.push(`  Shield Mode:      ${meta.campaign.shieldMode}  |  Delay: ${meta.campaign.delayMs}ms`);
  lines.push(`  Total Checked:    ${meta.campaign.totalChecked}`);
  lines.push(`  Registered:       ${meta.campaign.registeredCount}`);
  lines.push(`  Not Registered:   ${meta.campaign.unregisteredCount}`);
  lines.push(`  Invalid Format:   ${meta.campaign.invalidCount}`);
  lines.push(`  Yield Ratio:      ${meta.campaign.yieldRatio}`);
  lines.push(`  Exported Records: ${results.length}`);
  lines.push('');
  lines.push(sep2);
  lines.push('  VERIFICATION RESULTS');
  lines.push(sep2);
  lines.push('');
  lines.push(`  ${rpad('#', 4)} ${pad('Phone Number', 22)} ${pad('Country', 18)} ${pad('Status', 16)} ${pad('Type', 10)} ${pad('Display Name', 26)}`);
  lines.push(`  ${pad('', 4)} ${pad('', 22)} ${pad('', 18)} ${pad('', 16)} ${pad('', 10)} ${pad('', 26)}`);
  results.forEach((r, i) => {
    const rec = formatRecord(r, campaign);
    const statusIcon = rec.whatsappStatus === 'Registered' ? 'WA' : rec.whatsappStatus === 'Not Registered' ? '--' : '!!';
    const photo = rec.whatsappStatus === 'Registered'
      ? (rec.profilePhotoAvailable === 'Yes' ? 'Yes' : 'No Photo')
      : (rec.whatsappStatus === 'Not Registered' ? 'Not Registered' : 'N/A');
    lines.push(`  ${rpad(i + 1, 4)} ${pad(rec.phoneNumber, 22)} ${pad(getCountryFlag(rec.countryCode) + ' ' + rec.countryName, 18)} ${pad(statusIcon + ' ' + rec.whatsappStatus, 16)} ${pad(rec.accountType, 10)} ${pad(rec.displayName, 26)}`);
  });
  lines.push('');
  lines.push(sep);
  lines.push(`  End of Report | ${meta.appName} v${meta.appVersion}`);
  lines.push(`  Generated: ${meta.generatedAt}`);
  lines.push(sep);
  downloadFile(lines.join('\n'), `whatsapp-shield-report-${campaign.id?.substring(0, 8) || 'export'}.txt`, 'text/plain;charset=utf-8');
}

export function exportAllHistoryTXT(campaigns, phone) {
  if (!campaigns || campaigns.length === 0) return;
  const now = new Date();
  const lines = [];
  const sep = '='.repeat(96);
  const sep2 = '-'.repeat(96);
  const pad = (s, n) => String(s).padEnd(n);
  const rpad = (s, n) => String(s).padStart(n);

  lines.push(sep);
  lines.push('  WHATSAPP SHIELD - COMPLETE ACCOUNT HISTORY');
  lines.push(sep);
  lines.push('');
  lines.push(`  Application:      ${APP_NAME} v${APP_VERSION}`);
  lines.push(`  Generated By:     WhatsApp Shield`);
  lines.push(`  Export Format:    TXT`);
  lines.push(`  Export Date:      ${now.toLocaleDateString()} ${now.toLocaleTimeString()}`);
  const totalRecords = campaigns.reduce((s, c) => s + (c.results?.length || 0), 0);
  lines.push(`  Total Campaigns:  ${campaigns.length}`);
  lines.push(`  Total Records:    ${totalRecords}`);
  lines.push('');
  lines.push(sep2);

  campaigns.forEach((c, ci) => {
    lines.push('');
    lines.push(`  CAMPAIGN ${ci + 1} - ${campaignDisplayName(c)}`);
    lines.push(sep2);
    lines.push(`  Campaign ID:      ${c.id}`);
    lines.push(`  Date:             ${new Date(c.timestamp).toLocaleString()}`);
    lines.push(`  Country:          ${getCountryFlag(c.countryCode)} ${getCountryName(c.countryCode)} (+${getCountryDialCode(c.countryCode) || c.countryCode})`);
    lines.push(`  Shield:           ${c.shieldMode ? 'Enabled' : 'Disabled'}  |  Delay: ${c.delayMs}ms`);
    lines.push(`  Total:            ${c.totalChecked}  |  Registered: ${c.registeredCount}  |  Not Registered: ${c.unregisteredCount}  |  Invalid: ${c.invalidCount}`);
    lines.push('');
    if (c.results && c.results.length > 0) {
      lines.push(`  ${rpad('#', 4)} ${pad('Phone Number', 22)} ${pad('Status', 16)} ${pad('Type', 10)} ${pad('Display Name', 26)}`);
      lines.push(`  ${pad('', 4)} ${pad('', 22)} ${pad('', 16)} ${pad('', 10)} ${pad('', 26)}`);
      c.results.forEach((r, ri) => {
        const rec = formatRecord(r, c);
        lines.push(`  ${rpad(ri + 1, 4)} ${pad(rec.phoneNumber, 22)} ${pad(rec.whatsappStatus, 16)} ${pad(rec.accountType, 10)} ${pad(rec.displayName, 26)}`);
      });
    }
    lines.push('');
    lines.push(sep2);
  });

  lines.push('');
  lines.push(sep);
  lines.push(`  End of Report | ${APP_NAME} v${APP_VERSION}`);
  lines.push(sep);
  downloadFile(lines.join('\n'), `whatsapp-shield-all-history-${phone || 'export'}.txt`, 'text/plain;charset=utf-8');
}

/* ============================================================
   JSON EXPORT
   ============================================================ */

function toRecordJSON(rec) {
  return {
    phoneNumber: rec.phoneNumber,
    originalNumber: rec.originalNumber,
    country: {
      code: rec.countryCode,
      dialCode: rec.countryDialCode ? '+' + rec.countryDialCode : null,
      name: rec.countryName,
      flag: rec.countryFlag,
    },
    whatsappStatus: rec.whatsappStatus,
    accountType: rec.accountType,
    isVerified: rec.isVerified === 'Yes',
    displayName: rec.displayName === 'None' ? null : rec.displayName,
    profile: {
      photoAvailable: rec.profilePhotoAvailable === 'Yes',
      photoUrl: rec.profileImageUrl,
    },
    verification: { date: rec.verificationDate, time: rec.verificationTime },
  };
}

export function exportFilteredJSON(results, campaign, filterLabel) {
  if (!results || results.length === 0) return;
  const meta = buildMetadata(campaign, filterLabel, results.length, 'JSON');
  const output = {
    meta: {
      appName: meta.appName,
      appVersion: meta.appVersion,
      generatedBy: meta.generatedBy,
      generatedAt: meta.generatedAt,
      exportType: meta.exportType,
      exportFormat: meta.exportFormat,
    },
    campaign: {
      id: meta.campaign.id,
      ref: meta.campaign.ref,
      name: meta.campaignName,
      timestamp: meta.campaign.timestamp,
      country: {
        code: meta.campaign.countryCode,
        dialCode: meta.campaign.countryDialCode ? '+' + meta.campaign.countryDialCode : null,
        name: meta.campaign.countryName,
      },
      shieldMode: meta.campaign.shieldMode,
      delayMs: meta.campaign.delayMs,
      yieldRatio: meta.campaign.yieldRatio,
      totalChecked: meta.campaign.totalChecked,
      registeredCount: meta.campaign.registeredCount,
      unregisteredCount: meta.campaign.unregisteredCount,
      invalidCount: meta.campaign.invalidCount,
    },
    summary: {
      totalRecords: meta.campaign.totalChecked,
      exportedRecords: results.length,
      registered: meta.campaign.registeredCount,
      notRegistered: meta.campaign.unregisteredCount,
      invalid: meta.campaign.invalidCount,
      yieldRatio: meta.campaign.yieldRatio,
    },
    records: results.map(r => toRecordJSON(formatRecord(r, campaign))),
  };
  downloadFile(JSON.stringify(output, null, 2), `whatsapp-shield-report-${campaign.id?.substring(0, 8) || 'export'}.json`, 'application/json;charset=utf-8');
}

export function exportAllHistoryJSON(campaigns, phone) {
  if (!campaigns || campaigns.length === 0) return;
  const now = new Date();
  const output = {
    meta: {
      appName: APP_NAME,
      appVersion: APP_VERSION,
      generatedBy: 'Generated by WhatsApp Shield',
      generatedAt: now.toISOString(),
      exportType: 'Full Account History',
      exportFormat: 'JSON',
      totalCampaigns: campaigns.length,
      totalRecords: campaigns.reduce((s, c) => s + (c.results?.length || 0), 0),
    },
    campaigns: campaigns.map(c => ({
      id: c.id,
      name: campaignDisplayName(c),
      timestamp: c.timestamp,
      country: {
        code: c.countryCode,
        dialCode: getCountryDialCode(c.countryCode) ? '+' + getCountryDialCode(c.countryCode) : null,
        name: getCountryName(c.countryCode),
      },
      shieldMode: c.shieldMode ? 'Enabled' : 'Disabled',
      delayMs: c.delayMs,
      totalChecked: c.totalChecked,
      registeredCount: c.registeredCount,
      unregisteredCount: c.unregisteredCount,
      invalidCount: c.invalidCount,
      results: (c.results || []).map(r => toRecordJSON(formatRecord(r, c))),
    })),
  };
  downloadFile(JSON.stringify(output, null, 2), `whatsapp-shield-all-history-${phone || 'export'}.json`, 'application/json;charset=utf-8');
}

/* ============================================================
   PDF EXPORT
   ============================================================ */

function drawLogo(doc, x, y, size) {
  try {
    doc.setFillColor(...GREEN);
    doc.roundedRect(x, y, size, size, size * 0.18, size * 0.18, 'F');
    doc.setDrawColor(255, 255, 255);
    doc.setLineWidth(size * 0.12);
    doc.line(x + size * 0.26, y + size * 0.52, x + size * 0.45, y + size * 0.7);
    doc.line(x + size * 0.45, y + size * 0.7, x + size * 0.76, y + size * 0.32);
    doc.setLineWidth(0.2);
  } catch (e) {}
}

function drawFlagChip(doc, x, y, w, h, code) {
  try {
    doc.setFillColor(...GREEN);
    doc.roundedRect(x, y, w, h, 1, 1, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(5.5);
    doc.setTextColor(15, 23, 42);
    doc.text(code.toUpperCase(), x + w / 2, y + h / 2 + 1, { align: 'center' });
  } catch (e) {}
}

function drawPremiumHeader(doc, meta) {
  const pageW = doc.internal.pageSize.getWidth();
  const bandH = 32;

  doc.setFillColor(...NAVY);
  doc.rect(0, 0, pageW, bandH, 'F');
  doc.setFillColor(33, 46, 74);
  doc.rect(0, 0, pageW, 1.6, 'F');
  doc.setFillColor(...GREEN);
  doc.rect(0, bandH, pageW, 1.2, 'F');

  drawLogo(doc, 12, 6.5, 12);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(255, 255, 255);
  doc.text('WHATSAPP SHIELD', 28, 13);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.text('Enterprise Audience Validation Suite', 28, 18.5);

  const badgeW = 44;
  const badgeH = 6.5;
  doc.setFillColor(...GREEN);
  doc.roundedRect(pageW - 12 - badgeW, 6, badgeW, badgeH, 1, 1, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(6.5);
  doc.setTextColor(15, 23, 42);
  doc.text((meta.exportFormat || 'REPORT').toUpperCase(), pageW - 12 - badgeW / 2, 10.3, { align: 'center' });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12.5);
  doc.setTextColor(255, 255, 255);
  doc.text(meta.reportTitle || 'Campaign Verification Report', pageW - 12, 17.5, { align: 'right' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.8);
  doc.setTextColor(203, 213, 225);
  doc.text(`${meta.generatedDate}   ${meta.generatedTime}`, pageW - 12, 23, { align: 'right' });

  if (meta.campaignName) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(226, 232, 240);
    doc.text(meta.campaignName, pageW - 12, 28.5, { align: 'right', maxWidth: pageW - 200 });
  }
}

function drawSectionTitle(doc, y, label) {
  const pageW = doc.internal.pageSize.getWidth();
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...NAVY);
  doc.text(label, 12, y);
  doc.setDrawColor(...GREEN);
  doc.setLineWidth(0.6);
  doc.line(12, y + 2.2, pageW - 12, y + 2.2);
  return y + 6.5;
}

function drawStatCard(doc, x, y, w, h, label, value, color, chip) {
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(...BORDER);
  doc.setLineWidth(0.2);
  doc.roundedRect(x, y, w, h, 1.2, 1.2, 'FD');

  doc.setFillColor(...(color || NAVY));
  doc.roundedRect(x + 0.7, y + 1.2, 1.3, h - 2.4, 0.6, 0.6, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(5.8);
  doc.setTextColor(...SLATE);
  doc.text(String(label).toUpperCase(), x + 3.4, y + 3.5);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...(color || NAVY));
  const v = (value === null || value === undefined || value === '') ? 'N/A' : String(value);
  if (chip) {
    drawFlagChip(doc, x + 3.4, y + 5.2, 11, 4.4, chip);
    doc.text(v, x + 16, y + 9.4, { maxWidth: w - 20 });
  } else {
    doc.text(v, x + 3.4, y + h - 2.4, { maxWidth: w - 6 });
  }
}

function drawStatGrid(doc, items, startY) {
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 12;
  const cols = 4;
  const gap = 5;
  const cellW = (pageW - 2 * margin - (cols - 1) * gap) / cols;
  const cellH = 12.5;
  const rowGap = 4.5;
  items.forEach((item, i) => {
    const row = Math.floor(i / cols);
    const col = i % cols;
    const x = margin + col * (cellW + gap);
    const cy = startY + row * (cellH + rowGap);
    drawStatCard(doc, x, cy, cellW, cellH, item.label, item.value, item.color, item.chip);
  });
  return startY + Math.ceil(items.length / cols) * (cellH + rowGap);
}

function drawCampaignBanner(doc, y, label, value) {
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 12;
  const bannerH = 11;
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(...BORDER);
  doc.setLineWidth(0.2);
  doc.roundedRect(margin, y, pageW - 2 * margin, bannerH, 1.2, 1.2, 'FD');
  doc.setFillColor(...GREEN);
  doc.roundedRect(margin + 0.7, y + 1.2, 1.3, bannerH - 2.4, 0.6, 0.6, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(5.8);
  doc.setTextColor(...SLATE);
  doc.text(String(label).toUpperCase(), margin + 3.4, y + 3.5);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...NAVY);
  doc.text(String(value), margin + 3.4, y + bannerH - 2.4, { maxWidth: pageW - 2 * margin - 8 });
  return y + bannerH;
}

function drawCompactHeader(doc, pageNum, campaignName, generatedDate) {
  const pageW = doc.internal.pageSize.getWidth();
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, pageW, 11, 'F');
  doc.setFillColor(...GREEN);
  doc.rect(0, 11, pageW, 0.7, 'F');
  drawLogo(doc, 4, 3, 5);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(255, 255, 255);
  doc.text('WHATSAPP SHIELD', 11.5, 6.8);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.3);
  doc.setTextColor(203, 213, 225);
  const name = campaignName || 'Campaign Report';
  doc.text(name.length > 62 ? name.slice(0, 62) + '...' : name, 11.5, 10.2);
  doc.setTextColor(165, 175, 190);
  const pageStr = `Page ${pageNum}`;
  const pageWmm = doc.getTextWidth(pageStr);
  doc.text(pageStr, pageW - 12, 6.8, { align: 'right' });
  if (generatedDate) doc.text(generatedDate, pageW - 12 - pageWmm - 5, 6.8, { align: 'right' });
}

function drawFooter(doc, pageNum) {
  const pageH = doc.internal.pageSize.getHeight();
  const pageW = doc.internal.pageSize.getWidth();
  doc.setDrawColor(...BORDER);
  doc.setLineWidth(0.2);
  doc.line(12, pageH - 7.5, pageW - 12, pageH - 7.5);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.5);
  doc.setTextColor(140, 140, 140);
  doc.text('WhatsApp Shield v1.0.0 - Confidential Validation Report', 12, pageH - 4);
  doc.text(`Page ${pageNum}`, pageW - 12, pageH - 4, { align: 'right' });
  doc.setLineWidth(0.2);
}

function photoPlaceholderLabel(r, hasPhoto) {
  if (hasPhoto) return 'Photo';
  if (r.exists) return 'No Profile Photo';
  if (r.isValidFormat) return 'Not Registered';
  return 'Invalid';
}

export async function exportFilteredPDF(results, campaign, sessionUser, filterLabel) {
  if (!results || results.length === 0) return;
  const meta = buildMetadata(campaign, filterLabel, results.length, 'PDF');
  meta.reportTitle = 'Campaign Verification Report';
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 12;

  const verifiedCount = results.filter(r => r.isVerified === true).length;
  const dialCode = meta.campaign.countryDialCode;
  const countryName = meta.campaign.countryName === 'Unknown' ? 'Not Specified' : meta.campaign.countryName;

  drawPremiumHeader(doc, meta);

  let y = 40;
  y = drawSectionTitle(doc, y, 'CAMPAIGN SUMMARY');
  y = drawCampaignBanner(doc, y, 'Campaign Name', meta.campaignName);
  y += 5;

  const items = [
    { label: 'Campaign ID', value: meta.campaign.id, color: NAVY },
    { label: 'Reference ID', value: meta.campaign.ref, color: NAVY },
    { label: 'Country', value: countryName, color: NAVY, chip: dialCode ? meta.campaign.countryCode : null },
    { label: 'Country Code', value: dialCode ? '+' + dialCode : 'N/A', color: NAVY },
    { label: 'Export Date & Time', value: meta.generatedDate + '  ' + meta.generatedTime, color: NAVY },
    { label: 'Executed', value: campaign.timestamp ? new Date(campaign.timestamp).toLocaleString() : 'N/A', color: NAVY },
    { label: 'Total Checked', value: meta.campaign.totalChecked, color: NAVY },
    { label: 'Registered', value: meta.campaign.registeredCount, color: SUCCESS },
    { label: 'Not Registered', value: meta.campaign.unregisteredCount, color: ERROR },
    { label: 'Invalid', value: meta.campaign.invalidCount, color: AMBER },
    { label: 'Verified', value: verifiedCount, color: [37, 99, 235] },
    { label: 'Yield Ratio', value: meta.campaign.yieldRatio, color: GREEN_DARK },
    { label: 'Shield Mode', value: meta.campaign.shieldMode, color: NAVY },
    { label: 'Rate Limiting', value: meta.campaign.delayMs + 'ms', color: NAVY },
    { label: 'Export Filter', value: meta.exportType, color: NAVY },
    { label: 'Exported Records', value: results.length, color: NAVY },
  ];
  y = drawStatGrid(doc, items, y);

  y += 4.5;
  y = drawSectionTitle(doc, y, 'VERIFICATION RESULTS');
  const tableStart = y + 3.5;

  const photoMap = {};
  await Promise.all(results.map(async (r) => {
    if (r.avatar && !photoMap[r.avatar]) {
      let dataUrl = await fetchImageDataURL(r.avatar);
      if (dataUrl && dataUrl.startsWith('data:image/webp')) {
        const png = await convertWebPToPNG(dataUrl);
        if (png) dataUrl = png;
      }
      if (dataUrl) photoMap[r.avatar] = dataUrl;
    }
  }));

  const photoByRow = {};
  const tableData = results.map((r, i) => {
    const rec = formatRecord(r, campaign);
    const dataUrl = r.avatar && photoMap[r.avatar] ? photoMap[r.avatar] : null;
    if (dataUrl) photoByRow[i] = dataUrl;
    return [
      String(i + 1),
      rec.phoneNumber,
      rec.countryName,
      rec.whatsappStatus,
      rec.accountType,
      rec.displayName,
      rec.isVerified,
      photoPlaceholderLabel(r, !!dataUrl),
    ];
  });

  autoTable(doc, {
    startY: tableStart,
    head: [['#', 'Phone Number', 'Country', 'Status', 'Type', 'Display Name', 'Verified', 'Profile Photo']],
    body: tableData,
    theme: 'striped',
    showHead: 'everyPage',
    headStyles: {
      fillColor: NAVY,
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 7.5,
      cellPadding: 1.6,
    },
    styles: {
      cellPadding: 1.6,
      fontSize: 7,
      overflow: 'linebreak',
      lineColor: BORDER,
      lineWidth: 0.15,
      valign: 'middle',
    },
    alternateRowStyles: {
      fillColor: SURFACE,
    },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      1: { cellWidth: 52, fontStyle: 'courier' },
      2: { cellWidth: 30 },
      3: { cellWidth: 27 },
      4: { cellWidth: 18, halign: 'center' },
      5: { cellWidth: 90 },
      6: { cellWidth: 17, halign: 'center' },
      7: { cellWidth: 29, halign: 'center', fontSize: 5.5 },
    },
    didParseCell: function (data) {
      if (data.section !== 'body') return;
      if (data.column.index === 3) {
        const val = String(data.cell.raw);
        if (val === 'Registered') data.cell.styles.textColor = GREEN_DARK;
        else if (val === 'Not Registered') data.cell.styles.textColor = ERROR;
        else data.cell.styles.textColor = AMBER;
      }
      if (data.column.index === 4) {
        const val = String(data.cell.raw);
        if (val === 'Business') data.cell.styles.textColor = GREEN_DARK;
        else if (val === 'Personal') data.cell.styles.textColor = [59, 130, 246];
        else data.cell.styles.textColor = SLATE;
      }
      if (data.column.index === 7) {
        const dataUrl = photoByRow[data.row.index];
        if (dataUrl) {
          data.cell.text = [];
          data.cell.photoData = dataUrl;
        } else {
          const val = String(data.cell.raw);
          if (val === 'No Profile Photo') data.cell.styles.textColor = SLATE;
          else if (val === 'Not Registered') data.cell.styles.textColor = ERROR;
          else data.cell.styles.textColor = AMBER;
        }
      }
    },
    didDrawCell: function (data) {
      if (data.section === 'body' && data.column.index === 7 && data.cell.photoData) {
        try {
          const fmt = detectImageFormat(data.cell.photoData);
          const size = Math.min(data.cell.width - 4, data.cell.height - 3, 9);
          if (size > 2) {
            doc.addImage(data.cell.photoData, fmt, data.cell.x + (data.cell.width - size) / 2, data.cell.y + (data.cell.height - size) / 2, size, size);
          }
        } catch (e) {
          data.cell.styles.textColor = SLATE;
        }
      }
    },
    margin: { left: margin, right: margin, top: 15, bottom: 10 },
    willDrawPage: function (data) {
      const pageNum = data.pageNumber;
      if (pageNum > 1) drawCompactHeader(doc, pageNum, meta.campaignName, meta.generatedDate);
      drawFooter(doc, pageNum);
    },
  });

  doc.save(`whatsapp-shield-report-${campaign.id?.substring(0, 8) || 'export'}.pdf`);
}

export function exportAllHistoryPDF(campaigns, phone, sessionUser) {
  if (!campaigns || campaigns.length === 0) return;
  const now = new Date();
  const totalRecords = campaigns.reduce((s, c) => s + (c.results?.length || 0), 0);
  const totalChecked = campaigns.reduce((s, c) => s + (c.totalChecked || 0), 0);
  const totalRegistered = campaigns.reduce((s, c) => s + (c.registeredCount || 0), 0);
  const totalUnregistered = campaigns.reduce((s, c) => s + (c.unregisteredCount || 0), 0);
  const totalInvalid = campaigns.reduce((s, c) => s + (c.invalidCount || 0), 0);
  const avgYield = totalChecked > 0 ? Math.round((totalRegistered / totalChecked) * 100) : 0;

  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 12;

  const account = sessionUser?.name || sessionUser?.number || phone || 'N/A';
  const meta = {
    exportFormat: 'PDF',
    reportTitle: 'Account History Report',
    generatedDate: now.toLocaleDateString(),
    generatedTime: now.toLocaleTimeString(),
    campaignName: `Complete Account History - ${account}`,
  };

  drawPremiumHeader(doc, meta);

  let y = 40;
  y = drawSectionTitle(doc, y, 'HISTORY SUMMARY');
  y = drawCampaignBanner(doc, y, 'Account', account);
  y += 5;

  const items = [
    { label: 'Campaigns', value: campaigns.length, color: NAVY },
    { label: 'Total Checked', value: totalChecked, color: NAVY },
    { label: 'Total Records', value: totalRecords, color: NAVY },
    { label: 'Export Format', value: 'PDF', color: NAVY },
    { label: 'Registered', value: totalRegistered, color: SUCCESS },
    { label: 'Not Registered', value: totalUnregistered, color: ERROR },
    { label: 'Invalid', value: totalInvalid, color: AMBER },
    { label: 'Average Yield', value: avgYield + '%', color: GREEN_DARK },
    { label: 'Export Date', value: meta.generatedDate + '  ' + meta.generatedTime, color: NAVY },
    { label: 'Report Type', value: 'Full Account History', color: NAVY },
    { label: 'Generated By', value: 'WhatsApp Shield', color: NAVY },
    { label: 'Account Status', value: 'All Campaigns', color: NAVY },
  ];
  y = drawStatGrid(doc, items, y);

  y += 4.5;
  y = drawSectionTitle(doc, y, 'CAMPAIGN HISTORY');
  const tableStart = y + 3.5;

  const tableData = campaigns.map((c, i) => [
    String(i + 1),
    c.id ? c.id.substring(0, 18) : 'N/A',
    new Date(c.timestamp).toLocaleDateString(),
    getCountryName(c.countryCode),
    c.shieldMode ? 'Enabled' : 'Disabled',
    String(c.totalChecked || 0),
    String(c.registeredCount || 0),
    String(c.unregisteredCount || 0),
    c.totalChecked > 0 ? Math.round((c.registeredCount / c.totalChecked) * 100) + '%' : '0%',
  ]);

  autoTable(doc, {
    startY: tableStart,
    head: [['#', 'Campaign ID', 'Date', 'Country', 'Shield', 'Total', 'Registered', 'Not Reg.', 'Yield']],
    body: tableData,
    theme: 'striped',
    showHead: 'everyPage',
    headStyles: {
      fillColor: NAVY,
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 7.5,
      cellPadding: 1.6,
    },
    styles: {
      cellPadding: 1.8,
      fontSize: 7,
      overflow: 'linebreak',
      lineColor: BORDER,
      lineWidth: 0.15,
      valign: 'middle',
    },
    alternateRowStyles: {
      fillColor: SURFACE,
    },
    columnStyles: {
      0: { cellWidth: 12, halign: 'center' },
      1: { cellWidth: 48, fontStyle: 'courier' },
      2: { cellWidth: 26 },
      3: { cellWidth: 40 },
      4: { cellWidth: 22, halign: 'center' },
      5: { cellWidth: 22, halign: 'center' },
      6: { cellWidth: 24, halign: 'center' },
      7: { cellWidth: 24, halign: 'center' },
      8: { cellWidth: 22, halign: 'center' },
    },
    didParseCell: function (data) {
      if (data.section !== 'body') return;
      if (data.column.index === 6) data.cell.styles.textColor = SUCCESS;
      if (data.column.index === 7) data.cell.styles.textColor = ERROR;
    },
    margin: { left: margin, right: margin, top: 15, bottom: 10 },
    willDrawPage: function (data) {
      const pageNum = data.pageNumber;
      if (pageNum > 1) drawCompactHeader(doc, pageNum, meta.campaignName, meta.generatedDate);
      drawFooter(doc, pageNum);
    },
  });

  doc.save(`whatsapp-shield-full-history-${phone || 'export'}.pdf`);
}
