const PROVIDER_CATALOG = {
  // ──────────── Major International Models ────────────
  openai: {
    id: 'openai',
    name: 'OpenAI',
    description: 'GPT frontier and mini models for chat completions and structured JSON.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.openai.com/v1/chat/completions',
    modelsUrl: 'https://api.openai.com/v1/models',
    jsonMode: true,
    keyHint: 'sk-...',
    pricing: 'usage',
    color: '#10a37f',
    defaultModel: 'gpt-4.1-mini',
    freeTier: false,
    modelsApi: 'openai',
    models: [
      { id: 'gpt-5.6-sol', label: 'GPT-5.6 Sol', tier: 'frontier', contextLength: 200000 },
      { id: 'gpt-5.6-terra', label: 'GPT-5.6 Terra', tier: 'premium', contextLength: 200000 },
      { id: 'gpt-5.6-luna', label: 'GPT-5.6 Luna', tier: 'balanced', contextLength: 200000 },
      { id: 'gpt-5.5', label: 'GPT-5.5', tier: 'frontier', contextLength: 200000 },
      { id: 'gpt-5.4', label: 'GPT-5.4', tier: 'premium', contextLength: 200000 },
      { id: 'gpt-5.4-mini', label: 'GPT-5.4 mini', tier: 'balanced', contextLength: 200000 },
      { id: 'gpt-5.4-nano', label: 'GPT-5.4 nano', tier: 'fast', contextLength: 200000 },
      { id: 'gpt-4.1', label: 'GPT-4.1', tier: 'premium', contextLength: 200000 },
      { id: 'gpt-4.1-mini', label: 'GPT-4.1 mini', tier: 'balanced', contextLength: 200000 },
      { id: 'gpt-4.1-nano', label: 'GPT-4.1 nano', tier: 'fast', contextLength: 200000 },
      { id: 'gpt-oss-120b', label: 'GPT-OSS 120B', tier: 'balanced', contextLength: 200000 },
      { id: 'gpt-oss-20b', label: 'GPT-OSS 20B', tier: 'fast', contextLength: 200000 },
    ],
  },
  'openai-compatible': {
    id: 'openai-compatible',
    name: 'OpenAI-Compatible (custom)',
    description: 'Any API that speaks the OpenAI chat completions format with a custom base URL.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: '',
    customBaseUrl: true,
    jsonMode: true,
    keyHint: 'Your API key',
    pricing: 'usage',
    color: '#6b7280',
    defaultModel: '',
    freeTier: false,
    modelsApi: null,
    models: [],
  },
  anthropic: {
    id: 'anthropic',
    name: 'Anthropic',
    description: 'Claude models for reliably high-quality reasoning and long context.',
    chat: 'anthropic',
    auth: 'x-api-key',
    baseUrl: 'https://api.anthropic.com/v1/messages',
    modelsUrl: 'https://api.anthropic.com/v1/models',
    anthropicVersion: '2023-06-01',
    jsonMode: false,
    keyHint: 'sk-ant-...',
    pricing: 'usage',
    color: '#d97757',
    defaultModel: 'claude-sonnet-4-5-20250514',
    freeTier: false,
    modelsApi: 'anthropic',
    models: [
      { id: 'claude-opus-5', label: 'Claude Opus 5', tier: 'frontier', contextLength: 200000, noTemp: true },
      { id: 'claude-sonnet-5', label: 'Claude Sonnet 5', tier: 'premium', contextLength: 200000, noTemp: true },
      { id: 'claude-opus-4-8', label: 'Claude Opus 4.8', tier: 'frontier', contextLength: 200000, noTemp: true },
      { id: 'claude-opus-4-7', label: 'Claude Opus 4.7', tier: 'premium', contextLength: 200000, noTemp: true },
      { id: 'claude-sonnet-4-6', label: 'Claude Sonnet 4.6', tier: 'balanced', contextLength: 200000, noTemp: true },
      { id: 'claude-haiku-4-5', label: 'Claude Haiku 4.5', tier: 'fast', contextLength: 200000, noTemp: true },
      { id: 'claude-sonnet-4-5-20250514', label: 'Claude Sonnet 4.5', tier: 'balanced', contextLength: 200000 },
      { id: 'claude-haiku-4-5-20251001', label: 'Claude Haiku 4.5 (dated)', tier: 'fast', contextLength: 200000 },
      { id: 'claude-4-5-sonnet-20250929', label: 'Claude 4.5 Sonnet (dated)', tier: 'balanced', contextLength: 200000 },
    ],
  },
  gemini: {
    id: 'gemini',
    name: 'Google Gemini',
    description: 'Gemini multimodal models with a 1M token context window.',
    chat: 'gemini',
    auth: 'bearer',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    modelsUrl: 'https://generativelanguage.googleapis.com/v1beta/models',
    jsonMode: false,
    keyHint: 'AIza...',
    pricing: 'usage',
    color: '#4285f4',
    defaultModel: 'gemini-2.5-flash',
    freeTier: true,
    modelsApi: 'gemini',
    models: [
      { id: 'gemini-3.6-flash', label: 'Gemini 3.6 Flash', tier: 'frontier', contextLength: 1000000 },
      { id: 'gemini-3.5-flash', label: 'Gemini 3.5 Flash', tier: 'premium', contextLength: 1000000 },
      { id: 'gemini-2.5-pro', label: 'Gemini 2.5 Pro', tier: 'frontier', contextLength: 1000000 },
      { id: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash', tier: 'balanced', contextLength: 1000000 },
      { id: 'gemini-2.5-flash-lite', label: 'Gemini 2.5 Flash-Lite', tier: 'fast', contextLength: 1000000 },
      { id: 'gemini-flash-latest', label: 'Gemini Flash Latest', tier: 'balanced', contextLength: 1000000 },
    ],
  },
  xai: {
    id: 'xai',
    name: 'xAI',
    description: 'Grok models with a 1M token context window. OpenAI-compatible endpoint.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.x.ai/v1/chat/completions',
    modelsUrl: 'https://api.x.ai/v1/models',
    jsonMode: true,
    keyHint: 'xai-...',
    pricing: 'usage',
    color: '#000000',
    defaultModel: 'grok-4',
    freeTier: false,
    modelsApi: 'openai',
    models: [
      { id: 'grok-4', label: 'Grok 4', tier: 'frontier', contextLength: 1000000 },
      { id: 'grok-3', label: 'Grok 3', tier: 'premium', contextLength: 1000000 },
      { id: 'grok-3-mini', label: 'Grok 3 Mini', tier: 'balanced', contextLength: 1000000 },
      { id: 'grok-3-fast', label: 'Grok 3 Fast', tier: 'fast', contextLength: 1000000 },
      { id: 'grok-2', label: 'Grok 2', tier: 'balanced', contextLength: 128000 },
    ],
  },
  mistral: {
    id: 'mistral',
    name: 'Mistral AI',
    description: 'European open models (Mistral Large/Small) with strong multilingual support.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.mistral.ai/v1/chat/completions',
    modelsUrl: 'https://api.mistral.ai/v1/models',
    jsonMode: true,
    keyHint: '...',
    pricing: 'usage',
    color: '#f6b000',
    defaultModel: 'mistral-small-latest',
    freeTier: false,
    modelsApi: 'openai',
    models: [
      { id: 'mistral-large-latest', label: 'Mistral Large', tier: 'premium', contextLength: 128000 },
      { id: 'mistral-small-latest', label: 'Mistral Small', tier: 'balanced', contextLength: 128000 },
      { id: 'codestral-latest', label: 'Codestral', tier: 'premium', contextLength: 256000 },
      { id: 'open-mistral-nemo', label: 'Mistral Nemo', tier: 'fast', contextLength: 128000 },
      { id: 'pixtral-large-latest', label: 'Pixtral Large', tier: 'premium', contextLength: 128000 },
    ],
  },
  meta: {
    id: 'meta',
    name: 'Meta / Llama',
    description: 'Meta Llama models — open-weight LLMs available via supported providers.',
    chat: 'openai-compatible',
    auth: 'bearer',
    baseUrl: '',
    customBaseUrl: true,
    jsonMode: true,
    keyHint: 'Provider key',
    pricing: 'usage',
    color: '#0668E1',
    defaultModel: 'llama-4-maverick',
    freeTier: true,
    modelsApi: null,
    note: 'Llama models are open-weight. Access via Groq, Together, Fireworks, SambaNova, Cerebras, etc.',
    models: [
      { id: 'llama-4-maverick', label: 'Llama 4 Maverick', tier: 'frontier', contextLength: 1000000 },
      { id: 'llama-4-scout', label: 'Llama 4 Scout', tier: 'premium', contextLength: 1000000 },
      { id: 'llama-3.3-70b-versatile', label: 'Llama 3.3 70B', tier: 'balanced', contextLength: 128000 },
      { id: 'llama-3.1-8b-instant', label: 'Llama 3.1 8B', tier: 'fast', contextLength: 128000 },
    ],
  },
  amazon: {
    id: 'amazon',
    name: 'Amazon Nova',
    description: 'Amazon Nova foundation models via Amazon Bedrock.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: '',
    customBaseUrl: true,
    jsonMode: true,
    keyHint: 'AWS key',
    pricing: 'usage',
    color: '#FF9900',
    defaultModel: 'nova-pro',
    freeTier: false,
    modelsApi: null,
    note: 'Access via AWS Bedrock with appropriate IAM credentials.',
    models: [
      { id: 'nova-pro', label: 'Nova Pro', tier: 'premium', contextLength: 300000 },
      { id: 'nova-lite', label: 'Nova Lite', tier: 'balanced', contextLength: 300000 },
      { id: 'nova-micro', label: 'Nova Micro', tier: 'fast', contextLength: 300000 },
      { id: 'nova-canvas', label: 'Nova Canvas', tier: 'premium', contextLength: 300000 },
      { id: 'nova-sonic', label: 'Nova Sonic', tier: 'premium', contextLength: 300000 },
    ],
  },
  microsoft: {
    id: 'microsoft',
    name: 'Microsoft Phi',
    description: 'Microsoft Phi small language models via Azure AI or OpenAI-compatible APIs.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: '',
    customBaseUrl: true,
    jsonMode: true,
    keyHint: 'Azure / API key',
    pricing: 'usage',
    color: '#00A4EF',
    defaultModel: 'Phi-4',
    freeTier: false,
    modelsApi: null,
    models: [
      { id: 'Phi-4', label: 'Phi-4', tier: 'balanced', contextLength: 16000 },
      { id: 'Phi-4-mini', label: 'Phi-4 Mini', tier: 'fast', contextLength: 128000 },
      { id: 'Phi-3.5-mini', label: 'Phi-3.5 Mini', tier: 'fast', contextLength: 128000 },
      { id: 'Phi-4-reasoning', label: 'Phi-4 Reasoning', tier: 'premium', contextLength: 32000 },
    ],
  },
  ai21: {
    id: 'ai21',
    name: 'AI21 (Jamba)',
    description: 'Jamba hybrid-Transformer-Mamba models with 256K context.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.ai21.com/studio/v1/chat/completions',
    modelsUrl: 'https://api.ai21.com/studio/v1/models',
    jsonMode: true,
    keyHint: 'AI21 key',
    pricing: 'usage',
    color: '#0d9488',
    defaultModel: 'jamba-1.5-large',
    freeTier: false,
    modelsApi: 'openai',
    models: [
      { id: 'jamba-1.5-large', label: 'Jamba 1.5 Large', tier: 'premium', contextLength: 256000 },
      { id: 'jamba-1.5-mini', label: 'Jamba 1.5 Mini', tier: 'balanced', contextLength: 256000 },
      { id: 'jamba-instruct', label: 'Jamba Instruct', tier: 'balanced', contextLength: 256000 },
    ],
  },
  writer: {
    id: 'writer',
    name: 'Writer',
    description: 'Palmyra enterprise models for content generation and enterprise use cases.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.writer.com/v1/chat/completions',
    modelsUrl: 'https://api.writer.com/v1/models',
    jsonMode: true,
    keyHint: 'Writer key',
    pricing: 'usage',
    color: '#000000',
    defaultModel: 'palmyra-x-004',
    freeTier: false,
    modelsApi: 'openai',
    models: [
      { id: 'palmyra-x-004', label: 'Palmyra X 004', tier: 'premium', contextLength: 128000 },
      { id: 'palmyra-medical-002', label: 'Palmyra Medical', tier: 'premium', contextLength: 128000 },
      { id: 'palmyra-fin-001', label: 'Palmyra Fin', tier: 'premium', contextLength: 128000 },
    ],
  },

  // ──────────── API Platforms / Aggregators ────────────
  openrouter: {
    id: 'openrouter',
    name: 'OpenRouter',
    description: 'One key for 300+ models from every major provider, with unified billing.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://openrouter.ai/api/v1/chat/completions',
    modelsUrl: 'https://openrouter.ai/api/v1/models',
    jsonMode: true,
    keyHint: 'sk-or-...',
    pricing: 'usage',
    color: '#8321fc',
    defaultModel: 'meta-llama/llama-3.3-70b-instruct',
    freeTier: true,
    modelsApi: 'openrouter',
    models: [
      { id: 'meta-llama/llama-3.3-70b-instruct', label: 'Llama 3.3 70B Instruct', tier: 'balanced', contextLength: 128000, pricing: { prompt: 0, completion: 0 } },
      { id: 'meta-llama/llama-3.1-70b-instruct', label: 'Llama 3.1 70B Instruct', tier: 'balanced', contextLength: 128000, pricing: { prompt: 0, completion: 0 } },
      { id: 'openai/gpt-4o-mini', label: 'GPT-4o Mini', tier: 'fast', contextLength: 128000 },
      { id: 'anthropic/claude-sonnet-4-5', label: 'Claude Sonnet 4.5', tier: 'premium', contextLength: 200000 },
      { id: 'google/gemini-2.5-flash', label: 'Gemini 2.5 Flash', tier: 'balanced', contextLength: 1000000 },
      { id: 'deepseek/deepseek-chat', label: 'DeepSeek Chat', tier: 'balanced', contextLength: 128000, pricing: { prompt: 0.14, completion: 0.28 } },
      { id: 'qwen/qwen-2.5-72b-instruct', label: 'Qwen 2.5 72B', tier: 'premium', contextLength: 128000 },
    ],
  },
  together: {
    id: 'together',
    name: 'Together AI',
    description: 'High-throughput open-source model hosting (Llama, Qwen, DeepSeek).',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.together.ai/v1/chat/completions',
    modelsUrl: 'https://api.together.ai/v1/models',
    jsonMode: true,
    keyHint: '...',
    pricing: 'usage',
    color: '#7b69c5',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    freeTier: true,
    modelsApi: 'openai',
    models: [
      { id: 'meta-llama/Llama-3.3-70B-Instruct-Turbo', label: 'Llama 3.3 70B Turbo', tier: 'premium', contextLength: 128000 },
      { id: 'Qwen/Qwen3.5-9B', label: 'Qwen 3.5 9B', tier: 'balanced', contextLength: 128000 },
      { id: 'MiniMaxAI/MiniMax-M3', label: 'MiniMax M3', tier: 'frontier', contextLength: 1000000 },
      { id: 'deepseek-ai/DeepSeek-V4-Flash-0731', label: 'DeepSeek V4 Flash', tier: 'balanced', contextLength: 128000 },
      { id: 'meta-llama/Llama-4-Maverick-17B-128E-Instruct', label: 'Llama 4 Maverick', tier: 'frontier', contextLength: 1000000 },
    ],
  },
  fireworks: {
    id: 'fireworks',
    name: 'Fireworks AI',
    description: 'Fast inference for open and reasoning models. Namespaced model IDs.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.fireworks.ai/inference/v1/chat/completions',
    modelsUrl: 'https://api.fireworks.ai/inference/v1/models',
    jsonMode: true,
    keyHint: 'fireworks key',
    pricing: 'usage',
    color: '#fb7825',
    defaultModel: 'accounts/fireworks/models/llama-v3p3-70b-instruct',
    freeTier: false,
    modelsApi: 'openai',
    models: [
      { id: 'accounts/fireworks/models/llama-v3p3-70b-instruct', label: 'Llama 3.3 70B', tier: 'premium', contextLength: 128000 },
      { id: 'accounts/fireworks/models/qwen3-235b-a22b-instruct-2507', label: 'Qwen 3 235B A22B', tier: 'frontier', contextLength: 128000 },
      { id: 'accounts/fireworks/models/deepseek-r1', label: 'DeepSeek R1', tier: 'premium', contextLength: 128000 },
      { id: 'accounts/fireworks/models/llama-v3p2-3b-instruct', label: 'Llama 3.2 3B', tier: 'fast', contextLength: 128000 },
    ],
  },
  groq: {
    id: 'groq',
    name: 'Groq',
    description: 'Ultra-fast inference on open models (Llama, GPT-OSS). Best for low-latency replies.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.groq.com/openai/v1/chat/completions',
    modelsUrl: 'https://api.groq.com/openai/v1/models',
    jsonMode: true,
    keyHint: 'gsk_...',
    pricing: 'usage',
    color: '#f55036',
    defaultModel: 'llama-3.3-70b-versatile',
    freeTier: true,
    modelsApi: 'openai',
    models: [
      { id: 'llama-3.3-70b-versatile', label: 'Llama 3.3 70B', tier: 'premium', contextLength: 128000 },
      { id: 'llama-3.1-8b-instant', label: 'Llama 3.1 8B Instant', tier: 'fast', contextLength: 128000 },
      { id: 'openai/gpt-oss-120b', label: 'GPT-OSS 120B', tier: 'balanced', contextLength: 200000 },
      { id: 'openai/gpt-oss-20b', label: 'GPT-OSS 20B', tier: 'fast', contextLength: 200000 },
      { id: 'meta-llama/llama-4-maverick-17b-128e-instruct', label: 'Llama 4 Maverick', tier: 'frontier', contextLength: 1000000 },
    ],
  },
  cerebras: {
    id: 'cerebras',
    name: 'Cerebras',
    description: 'Ultra-fast inference for GPT-OSS, Llama and Qwen. OpenAI-compatible.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.cerebras.ai/v1/chat/completions',
    modelsUrl: 'https://api.cerebras.ai/v1/models',
    jsonMode: true,
    keyHint: 'cerebras key',
    pricing: 'usage',
    color: '#08c19c',
    defaultModel: 'llama-3.3-70b',
    freeTier: true,
    modelsApi: 'openai',
    models: [
      { id: 'llama-3.3-70b', label: 'Llama 3.3 70B', tier: 'premium', contextLength: 128000 },
      { id: 'llama-3.1-8b', label: 'Llama 3.1 8B', tier: 'fast', contextLength: 128000 },
      { id: 'qwen-2.5-32b', label: 'Qwen 2.5 32B', tier: 'balanced', contextLength: 128000 },
      { id: 'llama-4-scout-17b-16e-instruct', label: 'Llama 4 Scout', tier: 'frontier', contextLength: 1000000 },
    ],
  },
  sambanova: {
    id: 'sambanova',
    name: 'SambaNova',
    description: 'Open models (Llama, DeepSeek, Qwen, MiniMax, GPT-OSS) on SambaNova Cloud.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.sambanova.ai/v1/chat/completions',
    modelsUrl: 'https://api.sambanova.ai/v1/models',
    jsonMode: true,
    keyHint: 'sambanova key',
    pricing: 'usage',
    color: '#4c1d95',
    defaultModel: 'Meta-Llama-3.3-70B-Instruct',
    freeTier: true,
    modelsApi: 'openai',
    models: [
      { id: 'Meta-Llama-3.3-70B-Instruct', label: 'Llama 3.3 70B', tier: 'premium', contextLength: 128000 },
      { id: 'DeepSeek-V3.2', label: 'DeepSeek V3.2', tier: 'premium', contextLength: 128000 },
      { id: 'DeepSeek-R1', label: 'DeepSeek R1', tier: 'premium', contextLength: 128000 },
      { id: 'Qwen3-235B', label: 'Qwen 3 235B', tier: 'frontier', contextLength: 128000 },
      { id: 'gpt-oss-120b', label: 'GPT-OSS 120B', tier: 'balanced', contextLength: 200000 },
      { id: 'MiniMax-M2.7', label: 'MiniMax M2.7', tier: 'premium', contextLength: 200000 },
      { id: 'Llama-4-Maverick-17B-128E-Instruct', label: 'Llama 4 Maverick', tier: 'premium', contextLength: 1000000 },
    ],
  },
  novita: {
    id: 'novita',
    name: 'Novita AI',
    description: 'Open-model inference hub (DeepSeek, Llama, Qwen) at low cost.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.novita.ai/v3/openai/chat/completions',
    modelsUrl: 'https://api.novita.ai/v3/openai/models',
    jsonMode: true,
    keyHint: 'novita key',
    pricing: 'usage',
    color: '#22c1c3',
    defaultModel: 'deepseek-ai/DeepSeek-V4-Pro',
    freeTier: false,
    modelsApi: 'openai',
    models: [
      { id: 'deepseek-ai/DeepSeek-V4-Pro', label: 'DeepSeek V4 Pro', tier: 'premium', contextLength: 128000 },
      { id: 'deepseek-ai/DeepSeek-V4-Flash', label: 'DeepSeek V4 Flash', tier: 'balanced', contextLength: 128000 },
      { id: 'meta-llama/llama-3.3-70b-instruct', label: 'Llama 3.3 70B', tier: 'premium', contextLength: 128000 },
      { id: 'Qwen/Qwen3-235B-A22B-Instruct', label: 'Qwen 3 235B A22B', tier: 'frontier', contextLength: 128000 },
    ],
  },
  huggingface: {
    id: 'huggingface',
    name: 'Hugging Face',
    description: 'Inference Providers router: open models served by top providers. OpenAI-compatible.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://router.huggingface.co/v1/chat/completions',
    modelsUrl: 'https://router.huggingface.co/v1/models',
    jsonMode: true,
    keyHint: 'hf_...',
    pricing: 'usage',
    color: '#ffd21e',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct',
    freeTier: true,
    modelsApi: 'openai',
    models: [
      { id: 'meta-llama/Llama-3.3-70B-Instruct', label: 'Llama 3.3 70B', tier: 'premium', contextLength: 128000 },
      { id: 'deepseek-ai/DeepSeek-V4-Pro', label: 'DeepSeek V4 Pro', tier: 'premium', contextLength: 128000 },
      { id: 'deepseek-ai/DeepSeek-V4-Flash', label: 'DeepSeek V4 Flash', tier: 'balanced', contextLength: 128000 },
      { id: 'openai/gpt-oss-120b', label: 'GPT-OSS 120B', tier: 'balanced', contextLength: 200000 },
    ],
  },
  nvidia: {
    id: 'nvidia',
    name: 'NVIDIA NIM',
    description: 'NVIDIA inference microservices for optimized open models.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://integrate.api.nvidia.com/v1/chat/completions',
    modelsUrl: 'https://integrate.api.nvidia.com/v1/models',
    jsonMode: true,
    keyHint: 'nvapi-...',
    pricing: 'usage',
    color: '#76B900',
    defaultModel: 'meta/llama-3.3-70b-instruct',
    freeTier: false,
    modelsApi: 'openai',
    models: [
      { id: 'meta/llama-3.3-70b-instruct', label: 'Llama 3.3 70B', tier: 'premium', contextLength: 128000 },
      { id: 'meta/llama-3.1-8b-instruct', label: 'Llama 3.1 8B', tier: 'fast', contextLength: 128000 },
      { id: 'nvidia/llama-3.1-nemotron-70b-instruct', label: 'Nemotron 70B', tier: 'premium', contextLength: 128000 },
      { id: 'deepseek-ai/deepseek-r1', label: 'DeepSeek R1', tier: 'premium', contextLength: 128000 },
    ],
  },
  siliconflow: {
    id: 'siliconflow',
    name: 'SiliconFlow',
    description: 'High-performance open model inference platform with free tier available.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.siliconflow.cn/v1/chat/completions',
    modelsUrl: 'https://api.siliconflow.cn/v1/models',
    jsonMode: true,
    keyHint: 'sk-...',
    pricing: 'usage',
    color: '#4F46E5',
    defaultModel: 'Qwen/Qwen2.5-7B-Instruct',
    freeTier: true,
    modelsApi: 'openai',
    models: [
      { id: 'Qwen/Qwen2.5-7B-Instruct', label: 'Qwen 2.5 7B', tier: 'balanced', contextLength: 32000 },
      { id: 'deepseek-ai/DeepSeek-V3', label: 'DeepSeek V3', tier: 'premium', contextLength: 64000 },
      { id: 'deepseek-ai/DeepSeek-R1', label: 'DeepSeek R1', tier: 'premium', contextLength: 64000 },
      { id: 'meta-llama/Meta-Llama-3.1-8B-Instruct', label: 'Llama 3.1 8B', tier: 'fast', contextLength: 8192 },
    ],
  },
  replicate: {
    id: 'replicate',
    name: 'Replicate',
    description: 'Run open-source models via API. Thousands of community models available.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: '',
    customBaseUrl: true,
    jsonMode: true,
    keyHint: 'r8_...',
    pricing: 'usage',
    color: '#18181B',
    defaultModel: 'meta/meta-llama-3.3-70b-instruct',
    freeTier: false,
    modelsApi: null,
    note: 'Replicate uses model-version predictions. Use their dashboard or OpenAI-compatible endpoint.',
    models: [
      { id: 'meta/meta-llama-3.3-70b-instruct', label: 'Llama 3.3 70B', tier: 'premium', contextLength: 128000 },
      { id: 'meta/meta-llama-3.1-8b-instruct', label: 'Llama 3.1 8B', tier: 'fast', contextLength: 128000 },
      { id: 'deepseek-ai/deepseek-r1', label: 'DeepSeek R1', tier: 'premium', contextLength: 128000 },
    ],
  },

  // ──────────── Aggregators (additional) ────────────
  deepseek: {
    id: 'deepseek',
    name: 'DeepSeek',
    description: 'Cost-efficient V4 reasoning and chat models. OpenAI-compatible API.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.deepseek.com/chat/completions',
    modelsUrl: 'https://api.deepseek.com/models',
    jsonMode: true,
    keyHint: 'sk-...',
    pricing: 'usage',
    color: '#4d6bfe',
    defaultModel: 'deepseek-chat',
    freeTier: false,
    modelsApi: 'openai',
    models: [
      { id: 'deepseek-chat', label: 'DeepSeek Chat', tier: 'balanced', contextLength: 64000 },
      { id: 'deepseek-reasoner', label: 'DeepSeek Reasoner', tier: 'premium', contextLength: 64000 },
    ],
  },
  cohere: {
    id: 'cohere',
    name: 'Cohere',
    description: 'Command R models with retrieval and RAG-friendly APIs.',
    chat: 'cohere',
    auth: 'bearer',
    baseUrl: 'https://api.cohere.ai/v2/chat',
    jsonMode: false,
    keyHint: '...',
    pricing: 'usage',
    color: '#39594d',
    defaultModel: 'command-a-plus-05-2026',
    freeTier: true,
    modelsApi: null,
    models: [
      { id: 'command-a-plus-05-2026', label: 'Command A+ 05-2026', tier: 'frontier', contextLength: 128000 },
      { id: 'command-a', label: 'Command A', tier: 'premium', contextLength: 128000 },
      { id: 'command-r-plus', label: 'Command R Plus', tier: 'premium', contextLength: 128000 },
      { id: 'command-r', label: 'Command R', tier: 'balanced', contextLength: 128000 },
    ],
  },
  perplexity: {
    id: 'perplexity',
    name: 'Perplexity',
    description: 'Search-grounded Sonar models with verified citations.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.perplexity.ai/chat/completions',
    modelsUrl: 'https://api.perplexity.ai/models',
    jsonMode: true,
    keyHint: 'pplx-...',
    pricing: 'usage',
    color: '#20808d',
    defaultModel: 'sonar-pro',
    freeTier: false,
    modelsApi: 'openai',
    models: [
      { id: 'sonar-pro', label: 'Sonar Pro', tier: 'premium', contextLength: 200000 },
      { id: 'sonar-reasoning-pro', label: 'Sonar Reasoning Pro', tier: 'frontier', contextLength: 200000 },
      { id: 'sonar', label: 'Sonar', tier: 'balanced', contextLength: 200000 },
      { id: 'sonar-deep-research', label: 'Sonar Deep Research', tier: 'frontier', contextLength: 200000 },
    ],
  },
  azure: {
    id: 'azure',
    name: 'Azure OpenAI',
    description: 'OpenAI models hosted in your Azure subscription with the OpenAI deployments API.',
    chat: 'azure',
    auth: 'api-key',
    baseUrl: '',
    azure: true,
    jsonMode: true,
    keyHint: 'Azure resource key',
    pricing: 'usage',
    color: '#0078d4',
    defaultModel: '',
    freeTier: false,
    modelsApi: null,
    models: [],
  },

  // ──────────── Chinese Models ────────────
  qwen: {
    id: 'qwen',
    name: 'Qwen (Alibaba)',
    description: 'Alibaba Qwen flagship and open models via DashScope. OpenAI-compatible API.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1/chat/completions',
    modelsUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1/models',
    jsonMode: true,
    keyHint: 'sk-...',
    pricing: 'usage',
    color: '#615ced',
    defaultModel: 'qwen-plus',
    freeTier: false,
    modelsApi: 'openai',
    models: [
      { id: 'qwen-max', label: 'Qwen Max', tier: 'frontier', contextLength: 32000 },
      { id: 'qwen-plus', label: 'Qwen Plus', tier: 'premium', contextLength: 128000 },
      { id: 'qwen-turbo', label: 'Qwen Turbo', tier: 'balanced', contextLength: 128000 },
      { id: 'qwen-long', label: 'Qwen Long', tier: 'premium', contextLength: 1000000 },
      { id: 'qwen2.5-72b-instruct', label: 'Qwen 2.5 72B', tier: 'premium', contextLength: 128000 },
      { id: 'qwen2.5-32b-instruct', label: 'Qwen 2.5 32B', tier: 'balanced', contextLength: 128000 },
      { id: 'qwen2.5-14b-instruct', label: 'Qwen 2.5 14B', tier: 'balanced', contextLength: 128000 },
      { id: 'qwen2.5-7b-instruct', label: 'Qwen 2.5 7B', tier: 'fast', contextLength: 128000 },
      { id: 'qwen2.5-coder-32b-instruct', label: 'Qwen 2.5 Coder 32B', tier: 'premium', contextLength: 128000 },
    ],
  },
  moonshot: {
    id: 'moonshot',
    name: 'Moonshot (Kimi)',
    description: 'Moonshot AI Kimi reasoning models. OpenAI-compatible API.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.moonshot.cn/v1/chat/completions',
    modelsUrl: 'https://api.moonshot.cn/v1/models',
    jsonMode: true,
    keyHint: 'sk-...',
    pricing: 'usage',
    color: '#1a1a2e',
    defaultModel: 'moonshot-v1-128k',
    freeTier: false,
    modelsApi: 'openai',
    models: [
      { id: 'moonshot-v1-128k', label: 'Moonshot V1 128K', tier: 'premium', contextLength: 128000 },
      { id: 'moonshot-v1-32k', label: 'Moonshot V1 32K', tier: 'balanced', contextLength: 32000 },
      { id: 'moonshot-v1-8k', label: 'Moonshot V1 8K', tier: 'fast', contextLength: 8000 },
      { id: 'moonshot-auto', label: 'Moonshot Auto', tier: 'balanced', contextLength: 128000 },
    ],
  },
  zai: {
    id: 'zai',
    name: 'Z.ai (GLM)',
    description: 'Zhipu GLM frontier models via the Z.ai open platform. OpenAI-compatible.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4/chat/completions',
    modelsUrl: 'https://open.bigmodel.cn/api/paas/v4/models',
    jsonMode: true,
    keyHint: 'your-Z.AI key',
    pricing: 'usage',
    color: '#3859ff',
    defaultModel: 'glm-4-flash',
    freeTier: false,
    modelsApi: 'openai',
    models: [
      { id: 'glm-4-plus', label: 'GLM 4 Plus', tier: 'premium', contextLength: 128000 },
      { id: 'glm-4-flash', label: 'GLM 4 Flash', tier: 'balanced', contextLength: 128000 },
      { id: 'glm-4-long', label: 'GLM 4 Long', tier: 'premium', contextLength: 1000000 },
      { id: 'glm-4-air', label: 'GLM 4 Air', tier: 'fast', contextLength: 128000 },
      { id: 'glm-4-flashx', label: 'GLM 4 FlashX', tier: 'fast', contextLength: 128000 },
      { id: 'glm-4-airx', label: 'GLM 4 AirX', tier: 'balanced', contextLength: 8000 },
    ],
  },
  minimax: {
    id: 'minimax',
    name: 'MiniMax',
    description: 'MiniMax M3/M2 series reasoning models. OpenAI-compatible API.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.minimax.chat/v1/chat/completions',
    modelsUrl: 'https://api.minimax.chat/v1/models',
    jsonMode: true,
    keyHint: 'sk-cp-... or MiniMax key',
    pricing: 'usage',
    color: '#26329a',
    defaultModel: 'MiniMax-Text-01',
    freeTier: false,
    modelsApi: 'openai',
    models: [
      { id: 'MiniMax-Text-01', label: 'MiniMax Text 01', tier: 'frontier', contextLength: 1000000 },
      { id: 'MiniMax-Text-02', label: 'MiniMax Text 02', tier: 'premium', contextLength: 200000 },
      { id: 'abab6.5s-chat', label: 'Abab 6.5S', tier: 'balanced', contextLength: 32000 },
      { id: 'abab5.5-chat', label: 'Abab 5.5', tier: 'balanced', contextLength: 32000 },
    ],
  },
  yi: {
    id: 'yi',
    name: '01.AI (Yi)',
    description: '01.AI Yi large language models for reasoning and multilingual tasks.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.lingyiwanwu.com/v1/chat/completions',
    modelsUrl: 'https://api.lingyiwanwu.com/v1/models',
    jsonMode: true,
    keyHint: '...',
    pricing: 'usage',
    color: '#000000',
    defaultModel: 'yi-large',
    freeTier: false,
    modelsApi: 'openai',
    models: [
      { id: 'yi-large', label: 'Yi Large', tier: 'premium', contextLength: 32000 },
      { id: 'yi-large-turbo', label: 'Yi Large Turbo', tier: 'balanced', contextLength: 32000 },
      { id: 'yi-medium', label: 'Yi Medium', tier: 'balanced', contextLength: 16000 },
      { id: 'yi-spark', label: 'Yi Spark', tier: 'fast', contextLength: 16000 },
    ],
  },
  internlm: {
    id: 'internlm',
    name: 'InternLM',
    description: 'Shanghai AI Lab InternLM models for general and code tasks.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://internlm-chat.intern-ai.org.cn/puyu/api/v1/chat/completions',
    jsonMode: true,
    keyHint: '...',
    pricing: 'usage',
    color: '#0EA5E9',
    defaultModel: 'internlm2.5-latest',
    freeTier: false,
    modelsApi: null,
    models: [
      { id: 'internlm2.5-latest', label: 'InternLM 2.5', tier: 'premium', contextLength: 128000 },
      { id: 'internlm2-latest', label: 'InternLM 2', tier: 'balanced', contextLength: 32000 },
      { id: 'internlm2-chat-20b', label: 'InternLM 2 20B', tier: 'balanced', contextLength: 32000 },
    ],
  },
  baichuan: {
    id: 'baichuan',
    name: 'Baichuan AI',
    description: 'Baichuan large language models with strong Chinese language capabilities.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.baichuan-ai.com/v1/chat/completions',
    modelsUrl: 'https://api.baichuan-ai.com/v1/models',
    jsonMode: true,
    keyHint: '...',
    pricing: 'usage',
    color: '#1e40af',
    defaultModel: 'Baichuan4',
    freeTier: false,
    modelsApi: 'openai',
    models: [
      { id: 'Baichuan4', label: 'Baichuan 4', tier: 'premium', contextLength: 32000 },
      { id: 'Baichuan3-Turbo', label: 'Baichuan 3 Turbo', tier: 'balanced', contextLength: 32000 },
      { id: 'Baichuan2-Turbo', label: 'Baichuan 2 Turbo', tier: 'fast', contextLength: 32000 },
    ],
  },
  stepfun: {
    id: 'stepfun',
    name: 'StepFun',
    description: 'Step AI large language models for general reasoning.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.stepfun.com/v1/chat/completions',
    modelsUrl: 'https://api.stepfun.com/v1/models',
    jsonMode: true,
    keyHint: '...',
    pricing: 'usage',
    color: '#6366F1',
    defaultModel: 'step-2-16k',
    freeTier: false,
    modelsApi: 'openai',
    models: [
      { id: 'step-2-16k', label: 'Step 2 16K', tier: 'premium', contextLength: 16000 },
      { id: 'step-2-32k', label: 'Step 2 32K', tier: 'premium', contextLength: 32000 },
      { id: 'step-1-flash', label: 'Step 1 Flash', tier: 'fast', contextLength: 8000 },
    ],
  },
  sensnova: {
    id: 'sensnova',
    name: 'SenseNova',
    description: 'SenseTime SenseNova large language models.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.sensenova.cn/v1/chat/completions',
    jsonMode: true,
    keyHint: '...',
    pricing: 'usage',
    color: '#00A651',
    defaultModel: 'nova-ptc-pro-32k',
    freeTier: false,
    modelsApi: null,
    models: [
      { id: 'nova-ptc-pro-32k', label: 'Nova PTC Pro 32K', tier: 'premium', contextLength: 32000 },
      { id: 'nova-ptc-lite-32k', label: 'Nova PTC Lite 32K', tier: 'balanced', contextLength: 32000 },
    ],
  },
  xverse: {
    id: 'xverse',
    name: 'XVERSE',
    description: 'XVERSE AI large language models.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.xverse.cn/v1/chat/completions',
    jsonMode: true,
    keyHint: '...',
    pricing: 'usage',
    color: '#DC2626',
    defaultModel: 'XVERSE-65B',
    freeTier: false,
    modelsApi: null,
    models: [
      { id: 'XVERSE-65B', label: 'XVERSE 65B', tier: 'premium', contextLength: 8192 },
      { id: 'XVERSE-13B', label: 'XVERSE 13B', tier: 'balanced', contextLength: 8192 },
    ],
  },
  longcat: {
    id: 'longcat',
    name: 'LongCat (Meituan)',
    description: 'Meituan LongCat large language models.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://open.longcat.chat/v1/chat/completions',
    jsonMode: true,
    keyHint: '...',
    pricing: 'usage',
    color: '#FF6B00',
    defaultModel: 'LongCat-Chat',
    freeTier: false,
    modelsApi: null,
    models: [
      { id: 'LongCat-Chat', label: 'LongCat Chat', tier: 'balanced', contextLength: 128000 },
    ],
  },
};

const PROVIDER_SPECS = (() => {
  const specs = {};
  for (const [id, p] of Object.entries(PROVIDER_CATALOG)) {
    specs[id] = {
      url: p.baseUrl || `https://api.${id}.com`,
      model: p.defaultModel || '',
      defaultMaxTokens: 2000,
      chat: p.chat === 'openai' ? undefined : p.chat,
    };
  }
  return specs;
})();

const getProvider = (id) => PROVIDER_CATALOG[id] || null;

const getModels = (id) => (PROVIDER_CATALOG[id] || { models: [] }).models || [];

const isValidProvider = (id) => Boolean(PROVIDER_CATALOG[id]);

const DEFAULT_MAX_PROVIDERS = 40;

module.exports = {
  PROVIDER_CATALOG,
  PROVIDER_SPECS,
  getProvider,
  getModels,
  isValidProvider,
  DEFAULT_MAX_PROVIDERS,
};
