const PROVIDER_CATALOG = {
  openai: {
    id: 'openai',
    name: 'OpenAI',
    description: 'GPT frontier and mini models for chat completions and structured JSON.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.openai.com/v1/chat/completions',
    jsonMode: true,
    keyHint: 'sk-...',
    pricing: 'usage',
    color: '#10a37f',
    defaultModel: 'gpt-5.4-mini',
    models: [
      { id: 'gpt-5.6-sol', label: 'GPT-5.6 Sol', tier: 'frontier' },
      { id: 'gpt-5.6-terra', label: 'GPT-5.6 Terra', tier: 'premium' },
      { id: 'gpt-5.6-luna', label: 'GPT-5.6 Luna', tier: 'balanced' },
      { id: 'gpt-5.5', label: 'GPT-5.5', tier: 'frontier' },
      { id: 'gpt-5.4', label: 'GPT-5.4', tier: 'premium' },
      { id: 'gpt-5.4-mini', label: 'GPT-5.4 mini', tier: 'balanced' },
      { id: 'gpt-5.4-nano', label: 'GPT-5.4 nano', tier: 'fast' },
      { id: 'gpt-4.1', label: 'GPT-4.1', tier: 'premium' },
      { id: 'gpt-4.1-mini', label: 'GPT-4.1 mini', tier: 'balanced' },
      { id: 'gpt-4.1-nano', label: 'GPT-4.1 nano', tier: 'fast' },
      { id: 'gpt-oss-120b', label: 'GPT-OSS 120B', tier: 'balanced' },
      { id: 'gpt-oss-20b', label: 'GPT-OSS 20B', tier: 'fast' },
    ],
  },
  'openai-compatible': {
    id: 'openai-compatible',
    name: 'OpenAI-Compatible (custom)',
    description: 'Any API that speaks the OpenAI chat completions format with a custom base URL.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: '',
    customBaseUrl: true,
    jsonMode: true,
    keyHint: 'Your API key',
    pricing: 'usage',
    color: '#6b7280',
    defaultModel: '',
    models: [],
  },
  anthropic: {
    id: 'anthropic',
    name: 'Anthropic',
    description: 'Claude models for reliably high-quality reasoning and long context.',
    chat: 'anthropic',
    auth: 'x-api-key',
    baseUrl: 'https://api.anthropic.com/v1/messages',
    anthropicVersion: '2023-06-01',
    jsonMode: false,
    keyHint: 'sk-ant-...',
    pricing: 'usage',
    color: '#d97757',
    defaultModel: 'claude-sonnet-5',
    models: [
      { id: 'claude-fable-5', label: 'Claude Fable 5', tier: 'frontier', noTemp: true },
      { id: 'claude-opus-5', label: 'Claude Opus 5', tier: 'frontier', noTemp: true },
      { id: 'claude-sonnet-5', label: 'Claude Sonnet 5', tier: 'premium', noTemp: true },
      { id: 'claude-haiku-4-5', label: 'Claude Haiku 4.5', tier: 'fast', noTemp: true },
      { id: 'claude-opus-4-8', label: 'Claude Opus 4.8', tier: 'premium', noTemp: true },
      { id: 'claude-opus-4-7', label: 'Claude Opus 4.7', tier: 'premium', noTemp: true },
      { id: 'claude-sonnet-4-6', label: 'Claude Sonnet 4.6', tier: 'balanced', noTemp: true },
      { id: 'claude-sonnet-4-5', label: 'Claude Sonnet 4.5', tier: 'balanced' },
      { id: 'claude-haiku-4-5-20251001', label: 'Claude Haiku 4.5 (dated)', tier: 'fast' },
      { id: 'claude-4-5-sonnet-20250929', label: 'Claude 4.5 Sonnet (dated)', tier: 'balanced' },
    ],
  },
  gemini: {
    id: 'gemini',
    name: 'Google Gemini',
    description: 'Gemini 2.5 multimodal models with a 1M token context window.',
    chat: 'gemini',
    auth: 'bearer',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    jsonMode: false,
    keyHint: 'AIza...',
    pricing: 'usage',
    color: '#4285f4',
    defaultModel: 'gemini-2.5-flash',
    models: [
      { id: 'gemini-2.5-pro', label: 'Gemini 2.5 Pro', tier: 'frontier' },
      { id: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash', tier: 'balanced' },
      { id: 'gemini-2.5-flash-lite', label: 'Gemini 2.5 Flash-Lite', tier: 'fast' },
      { id: 'gemini-flash-latest', label: 'Gemini Flash Latest', tier: 'balanced' },
    ],
  },
  groq: {
    id: 'groq',
    name: 'Groq',
    description: 'Ultra-fast inference on open models (Llama, GPT-OSS). Best for low-latency replies.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.groq.com/openai/v1/chat/completions',
    jsonMode: true,
    keyHint: 'gsk_...',
    pricing: 'usage',
    color: '#f55036',
    defaultModel: 'llama-3.3-70b-versatile',
    models: [
      { id: 'llama-3.3-70b-versatile', label: 'Llama 3.3 70B', tier: 'premium' },
      { id: 'llama-3.1-8b-instant', label: 'Llama 3.1 8B Instant', tier: 'fast' },
      { id: 'openai/gpt-oss-120b', label: 'GPT-OSS 120B', tier: 'balanced' },
      { id: 'openai/gpt-oss-20b', label: 'GPT-OSS 20B', tier: 'fast' },
    ],
  },
  mistral: {
    id: 'mistral',
    name: 'Mistral AI',
    description: 'European open models (Mistral Large/Small) with strong multilingual support.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.mistral.ai/v1/chat/completions',
    jsonMode: true,
    keyHint: '...',
    pricing: 'usage',
    color: '#f6b000',
    defaultModel: 'mistral-small-latest',
    models: [
      { id: 'mistral-large-latest', label: 'Mistral Large', tier: 'premium' },
      { id: 'mistral-small-latest', label: 'Mistral Small', tier: 'balanced' },
      { id: 'codestral-latest', label: 'Codestral', tier: 'premium' },
      { id: 'open-mistral-nemo', label: 'Mistral Nemo', tier: 'fast' },
    ],
  },
  deepseek: {
    id: 'deepseek',
    name: 'DeepSeek',
    description: 'Cost-efficient V4 reasoning and chat models. OpenAI-compatible API.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.deepseek.com/chat/completions',
    jsonMode: true,
    keyHint: 'sk-...',
    pricing: 'usage',
    color: '#4d6bfe',
    defaultModel: 'deepseek-v4-flash',
    models: [
      { id: 'deepseek-v4-pro', label: 'DeepSeek V4 Pro', tier: 'premium' },
      { id: 'deepseek-v4-flash', label: 'DeepSeek V4 Flash', tier: 'balanced' },
      { id: 'deepseek-chat', label: 'DeepSeek Chat (legacy alias)', tier: 'balanced' },
      { id: 'deepseek-reasoner', label: 'DeepSeek Reasoner (legacy alias)', tier: 'premium' },
    ],
  },
  openrouter: {
    id: 'openrouter',
    name: 'OpenRouter',
    description: 'One key for 300+ models from every major provider, with unified billing.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://openrouter.ai/api/v1/chat/completions',
    jsonMode: true,
    keyHint: 'sk-or-...',
    pricing: 'usage',
    color: '#8321fc',
    defaultModel: 'meta-llama/llama-3.1-70b-instruct',
    models: [
      { id: 'meta-llama/llama-3.1-70b-instruct', label: 'Llama 3.1 70B Instruct', tier: 'balanced' },
      { id: 'meta-llama/llama-3.3-70b-instruct', label: 'Llama 3.3 70B Instruct', tier: 'balanced' },
      { id: 'openai/gpt-4o-mini', label: 'GPT-4o mini', tier: 'fast' },
      { id: 'anthropic/claude-sonnet-4-5', label: 'Claude Sonnet 4.5', tier: 'premium' },
      { id: 'google/gemini-2.5-flash', label: 'Gemini 2.5 Flash', tier: 'balanced' },
    ],
  },
  together: {
    id: 'together',
    name: 'Together AI',
    description: 'High-throughput open-source model hosting (Llama, Qwen, DeepSeek).',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.together.xyz/v1/chat/completions',
    jsonMode: true,
    keyHint: '...',
    pricing: 'usage',
    color: '#7b69c5',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    models: [
      { id: 'meta-llama/Llama-3.3-70B-Instruct-Turbo', label: 'Llama 3.3 70B Turbo', tier: 'premium' },
      { id: 'meta-llama/Llama-3.1-8B-Instruct-Turbo', label: 'Llama 3.1 8B Turbo', tier: 'fast' },
      { id: 'deepseek-ai/deepseek-v3', label: 'DeepSeek V3', tier: 'balanced' },
    ],
  },
  cohere: {
    id: 'cohere',
    name: 'Cohere',
    description: 'Command R models with retrieval and RAG-friendly APIs.',
    chat: 'cohere',
    auth: 'bearer',
    baseUrl: 'https://api.cohere.com/v2/chat',
    jsonMode: false,
    keyHint: '...',
    pricing: 'usage',
    color: '#39594d',
    defaultModel: 'command-r-plus',
    models: [
      { id: 'command-r-plus', label: 'Command R Plus', tier: 'premium' },
      { id: 'command-r', label: 'Command R', tier: 'balanced' },
      { id: 'command-a', label: 'Command A', tier: 'balanced' },
    ],
  },
  perplexity: {
    id: 'perplexity',
    name: 'Perplexity',
    description: 'Search-grounded Sonar models with verified citations.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.perplexity.ai/chat/completions',
    jsonMode: true,
    keyHint: 'pplx-...',
    pricing: 'usage',
    color: '#20808d',
    defaultModel: 'sonar',
    models: [
      { id: 'sonar-pro', label: 'Sonar Pro', tier: 'premium' },
      { id: 'sonar', label: 'Sonar', tier: 'balanced' },
      { id: 'sonar-reasoning', label: 'Sonar Reasoning', tier: 'premium' },
    ],
  },
  xai: {
    id: 'xai',
    name: 'xAI',
    description: 'Grok models with a 1M token context window. OpenAI-compatible endpoint.',
    chat: 'openai',
    auth: 'bearer',
    baseUrl: 'https://api.x.ai/v1/chat/completions',
    jsonMode: true,
    keyHint: 'xai-...',
    pricing: 'usage',
    color: '#000000',
    defaultModel: 'grok-4',
    models: [
      { id: 'grok-4.6', label: 'Grok 4.6', tier: 'frontier' },
      { id: 'grok-4.3', label: 'Grok 4.3', tier: 'premium' },
      { id: 'grok-4', label: 'Grok 4', tier: 'premium' },
      { id: 'grok-build-0.1', label: 'Grok Build 0.1', tier: 'balanced' },
    ],
  },
  azure: {
    id: 'azure',
    name: 'Azure OpenAI',
    description: 'OpenAI models hosted in your Azure subscription with the OpenAI deployments API.',
    chat: 'azure',
    auth: 'api-key',
    baseUrl: '',
    azure: true,
    jsonMode: true,
    keyHint: 'Azure resource key',
    pricing: 'usage',
    color: '#0078d4',
    defaultModel: '',
    models: [],
  },
};

const PROVIDER_SPECS = (() => {
  const specs = {};
  for (const [id, p] of Object.entries(PROVIDER_CATALOG)) {
    specs[id] = {
      url: p.baseUrl || `https://api.${id}.com`,
      model: p.defaultModel || '',
      defaultMaxTokens: 2000,
      chat: p.chat === 'openai' ? undefined : p.chat,
    };
  }
  return specs;
})();

const getProvider = (id) => PROVIDER_CATALOG[id] || null;

const getModels = (id) => (PROVIDER_CATALOG[id] || { models: [] }).models || [];

const isValidProvider = (id) => Boolean(PROVIDER_CATALOG[id]);

const DEFAULT_MAX_PROVIDERS = 13;

module.exports = {
  PROVIDER_CATALOG,
  PROVIDER_SPECS,
  getProvider,
  getModels,
  isValidProvider,
  DEFAULT_MAX_PROVIDERS,
};