import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { parsePhoneNumberFromString } from 'libphonenumber-js';
import { countries } from '../data/countries';

const APP_NAME = 'WhatsApp Shield';
const APP_VERSION = '1.0.0';

export const getCountryName = (code) => {
  if (!code) return 'Unknown';
  const c = countries.find(c => c.iso.toLowerCase() === code.toLowerCase() || c.code === code);
  return c ? c.name : code;
};

export const getCountryFlag = (code) => {
  if (!code || code === 'N/A' || code === 'Unknown') return '';
  const c = countries.find(c => c.iso.toLowerCase() === code.toLowerCase());
  if (!c) return '';
  return String.fromCodePoint(...c.iso.toUpperCase().split('').map(ch => 0x1F1E6 + ch.charCodeAt(0) - 65));
};

export const getCountryFromNumber = (num) => {
  try {
    const parsed = parsePhoneNumberFromString(num);
    if (parsed && parsed.country) {
      const c = countries.find(c => c.iso.toLowerCase() === parsed.country.toLowerCase());
      return { code: parsed.country, name: c ? c.name : parsed.country };
    }
  } catch (e) {}
  return { code: 'Unknown', name: 'Unknown' };
};

function buildMetadata(campaign, filterLabel, totalRecords) {
  const now = new Date();
  const yieldRatio = campaign.totalChecked > 0
    ? Math.round((campaign.registeredCount / campaign.totalChecked) * 100)
    : 0;
  return {
    generatedAt: now.toISOString(),
    generatedDate: now.toLocaleDateString(),
    generatedTime: now.toLocaleTimeString(),
    appName: APP_NAME,
    appVersion: APP_VERSION,
    generatedBy: 'WhatsApp Shield Export Engine',
    exportType: filterLabel || 'Full Campaign Report',
    totalRecords,
    campaign: {
      id: campaign.id,
      ref: campaign.id?.substring(0, 8) || 'N/A',
      timestamp: campaign.timestamp,
      countryCode: campaign.countryCode || 'Unknown',
      shieldMode: campaign.shieldMode ? 'Enabled' : 'Disabled',
      delayMs: campaign.delayMs || 0,
      yieldRatio: yieldRatio + '%',
      totalChecked: campaign.totalChecked || 0,
      registeredCount: campaign.registeredCount || 0,
      unregisteredCount: campaign.unregisteredCount || 0,
      invalidCount: campaign.invalidCount || 0,
    },
  };
}

function formatRecord(r, campaign) {
  const country = r.detectedCountry || getCountryFromNumber(r.formatted || r.number || '');
  const countryName = typeof country === 'object' ? country.name : getCountryName(country);
  const countryCode = typeof country === 'object' ? country.code : country;
  const countryFlag = getCountryFlag(typeof country === 'object' ? country.code : country);
  const status = r.exists ? 'Registered' : (r.isValidFormat ? 'Not Registered' : 'Invalid Format');
  const ts = r.timestamp || campaign?.timestamp || new Date().toISOString();
  return {
    phoneNumber: r.formatted || r.number || '',
    originalNumber: r.number || '',
    countryCode: countryCode || 'Unknown',
    countryName,
    countryFlag,
    whatsappStatus: status,
    isBusinessAccount: r.isBusiness ? 'Yes' : 'No',
    isVerified: r.isVerified ? 'Yes' : 'No',
    profileName: r.statusText || '',
    profileImageUrl: r.avatar || '',
    verificationDate: ts.split('T')[0],
    verificationTime: new Date(ts).toLocaleTimeString(),
  };
}

function escapeCSV(val) {
  const str = String(val ?? '');
  if (str.includes(',') || str.includes('"') || str.includes('\n')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

export function downloadFile(content, fileName, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function exportFilteredCSV(results, campaign, filterLabel) {
  if (!results || results.length === 0) return;
  const meta = buildMetadata(campaign, filterLabel, results.length);
  const headers = [
    'Phone Number', 'Original Number', 'Country Code', 'Country Name', 'Country Flag',
    'WhatsApp Status', 'Business Account', 'Verified', 'Profile Name', 'Profile Image URL',
    'Campaign ID', 'Campaign Ref', 'Verification Date', 'Verification Time',
    'Shield Mode', 'Rate Limiting (ms)', 'Yield Ratio',
    'Export Date', 'Export Time', 'Generated By', 'Application', 'Version',
  ];
  const rows = results.map(r => {
    const rec = formatRecord(r, campaign);
    return [
      rec.phoneNumber, rec.originalNumber, rec.countryCode, rec.countryName, rec.countryFlag,
      rec.whatsappStatus, rec.isBusinessAccount, rec.isVerified, rec.profileName, rec.profileImageUrl,
      meta.campaign.id, meta.campaign.ref, rec.verificationDate, rec.verificationTime,
      meta.campaign.shieldMode, meta.campaign.delayMs, meta.campaign.yieldRatio,
      meta.generatedDate, meta.generatedTime, meta.generatedBy, meta.appName, meta.appVersion,
    ].map(escapeCSV).join(',');
  });
  const csv = '\uFEFF' + [headers.join(','), ...rows].join('\n');
  downloadFile(csv, `whatsapp-shield-report-${campaign.id?.substring(0, 8) || 'export'}.csv`, 'text/csv;charset=utf-8');
}

export function exportFilteredTXT(results, campaign, filterLabel) {
  if (!results || results.length === 0) return;
  const meta = buildMetadata(campaign, filterLabel, results.length);
  const lines = [];
  const sep = '='.repeat(72);
  const sep2 = '-'.repeat(72);
  lines.push(sep);
  lines.push('  WHATSAPP SHIELD - VALIDATION CAMPAIGN REPORT');
  lines.push(sep);
  lines.push('');
  lines.push(`  Application:      ${meta.appName} v${meta.appVersion}`);
  lines.push(`  Generated By:     ${meta.generatedBy}`);
  lines.push(`  Export Date:      ${meta.generatedDate} ${meta.generatedTime}`);
  lines.push('');
  lines.push(sep2);
  lines.push('  CAMPAIGN DETAILS');
  lines.push(sep2);
  lines.push(`  Campaign ID:      ${meta.campaign.id}`);
  lines.push(`  Campaign Ref:     ${meta.campaign.ref}`);
  lines.push(`  Executed:         ${new Date(campaign.timestamp).toLocaleString()}`);
  lines.push(`  Country Scope:    +${meta.campaign.countryCode} (${getCountryName(meta.campaign.countryCode)})`);
  lines.push(`  Shield Mode:      ${meta.campaign.shieldMode}`);
  lines.push(`  Rate Limiting:    ${meta.campaign.delayMs}ms delay`);
  lines.push(`  Export Filter:    ${filterLabel || 'All Results'}`);
  lines.push('');
  lines.push(sep2);
  lines.push('  SUMMARY');
  lines.push(sep2);
  lines.push(`  Total Records:    ${meta.campaign.totalChecked}`);
  lines.push(`  Registered:       ${meta.campaign.registeredCount}`);
  lines.push(`  Not Registered:   ${meta.campaign.unregisteredCount}`);
  lines.push(`  Invalid Format:   ${meta.campaign.invalidCount}`);
  lines.push(`  Yield Ratio:      ${meta.campaign.yieldRatio}`);
  lines.push(`  Exported Now:     ${results.length} records`);
  lines.push('');
  lines.push(sep2);
  lines.push('  VERIFICATION RESULTS');
  lines.push(sep2);
  lines.push('');
  const pad = (s, n) => String(s).padEnd(n);
  const rpad = (s, n) => String(s).padStart(n);
  lines.push(`  ${pad('#', 4)} ${pad('Phone Number', 20)} ${pad('Country', 14)} ${pad('Status', 16)} ${pad('Profile Name', 24)}`);
  lines.push(`  ${pad('', 4)} ${pad('', 20)} ${pad('', 14)} ${pad('', 16)} ${pad('', 24)}`);
  results.forEach((r, i) => {
    const rec = formatRecord(r, campaign);
    const statusIcon = rec.whatsappStatus === 'Registered' ? '[WA]' : rec.whatsappStatus === 'Not Registered' ? '[--]' : '[!!]';
    lines.push(`  ${rpad(i + 1, 3)}  ${pad(rec.phoneNumber, 20)} ${pad('+' + rec.countryCode, 14)} ${statusIcon} ${pad(rec.whatsappStatus.replace(/ /g, ''), 11)} ${pad(rec.profileName || '---', 24)}`);
  });
  lines.push('');
  lines.push(sep);
  lines.push(`  End of Report | ${meta.appName} v${meta.appVersion}`);
  lines.push(`  Generated: ${meta.generatedAt}`);
  lines.push(sep);
  downloadFile(lines.join('\n'), `whatsapp-shield-report-${campaign.id?.substring(0, 8) || 'export'}.txt`, 'text/plain;charset=utf-8');
}

export function exportFilteredJSON(results, campaign, filterLabel) {
  if (!results || results.length === 0) return;
  const meta = buildMetadata(campaign, filterLabel, results.length);
  const records = results.map(r => {
    const rec = formatRecord(r, campaign);
    return {
      phoneNumber: rec.phoneNumber,
      originalNumber: rec.originalNumber,
      country: { code: rec.countryCode, name: rec.countryName, flag: rec.countryFlag },
      whatsappStatus: rec.whatsappStatus,
      isBusinessAccount: rec.isBusinessAccount === 'Yes',
      isVerified: rec.isVerified === 'Yes',
      profile: { name: rec.profileName, imageUrl: rec.profileImageUrl },
      verification: { date: rec.verificationDate, time: rec.verificationTime },
    };
  });
  const output = {
    meta: {
      appName: meta.appName,
      appVersion: meta.appVersion,
      generatedBy: meta.generatedBy,
      generatedAt: meta.generatedAt,
      exportType: meta.exportType,
    },
    campaign: meta.campaign,
    summary: {
      totalRecords: meta.campaign.totalChecked,
      exportedRecords: results.length,
      registered: meta.campaign.registeredCount,
      notRegistered: meta.campaign.unregisteredCount,
      invalid: meta.campaign.invalidCount,
      yieldRatio: meta.campaign.yieldRatio,
    },
    records,
  };
  downloadFile(JSON.stringify(output, null, 2), `whatsapp-shield-report-${campaign.id?.substring(0, 8) || 'export'}.json`, 'application/json;charset=utf-8');
}

export function exportFilteredPDF(results, campaign, sessionUser, filterLabel) {
  if (!results || results.length === 0) return;
  const meta = buildMetadata(campaign, filterLabel, results.length);
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 14;

  function addHeader(doc) {
    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, pageW, 28, 'F');
    doc.setFillColor(0, 217, 126);
    doc.rect(0, 28, pageW, 1, 'F');
    doc.setFontSize(18);
    doc.setTextColor(255, 255, 255);
    doc.text(APP_NAME, margin, 12);
    doc.setFontSize(9);
    doc.setTextColor(180, 180, 180);
    doc.text('Validation Campaign Audit Report', margin, 19);
    doc.setFontSize(8);
    doc.setTextColor(130, 130, 130);
    doc.text(`Generated: ${meta.generatedDate} ${meta.generatedTime}`, margin, 25);
    doc.setTextColor(180, 180, 180);
    doc.text(`Page ${doc.internal.getCurrentPageInfo().pageNumber}`, pageW - margin - 20, 25);
  }

  function addFooter(doc) {
    const y = pageH - 8;
    doc.setFillColor(15, 23, 42);
    doc.rect(0, y - 2, pageW, 10, 'F');
    doc.setFontSize(7);
    doc.setTextColor(140, 140, 140);
    doc.text(`${APP_NAME} v${APP_VERSION} | Confidential Report | ${meta.generatedBy}`, margin, y + 3);
    doc.text(`Page ${doc.internal.getCurrentPageInfo().pageNumber}`, pageW - margin - 15, y + 3);
  }

  addHeader(doc);
  addFooter(doc);

  let y = 36;

  // Campaign info block
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin, y, pageW - 2 * margin, 22, 2, 2, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin, y, pageW - 2 * margin, 22, 2, 2, 'S');
  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.text(`Campaign ID: ${meta.campaign.id}`, margin + 4, y + 6);
  doc.text(`Ref: ${meta.campaign.ref}`, margin + 4, y + 12);
  doc.text(`Executed: ${new Date(campaign.timestamp).toLocaleString()}`, margin + 4, y + 18);
  doc.text(`Country: +${meta.campaign.countryCode} (${getCountryName(meta.campaign.countryCode)})`, margin + 80, y + 6);
  doc.text(`Shield: ${meta.campaign.shieldMode} | Delay: ${meta.campaign.delayMs}ms`, margin + 80, y + 12);
  doc.text(`Filter: ${filterLabel || 'All Results'} | Exported: ${results.length} of ${meta.campaign.totalChecked}`, margin + 80, y + 18);
  y += 28;

  // Summary cards
  const cards = [
    { label: 'Total Checked', value: meta.campaign.totalChecked, color: [15, 23, 42] },
    { label: 'Registered', value: meta.campaign.registeredCount, color: [0, 184, 110] },
    { label: 'Not Registered', value: meta.campaign.unregisteredCount, color: [239, 68, 68] },
    { label: 'Invalid', value: meta.campaign.invalidCount, color: [245, 158, 11] },
    { label: 'Yield Ratio', value: meta.campaign.yieldRatio, color: [0, 217, 126] },
  ];
  const cardW = (pageW - 2 * margin - 4 * 6) / 5;
  cards.forEach((card, i) => {
    const cx = margin + i * (cardW + 6);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(cx, y, cardW, 18, 2, 2, 'F');
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(cx, y, cardW, 18, 2, 2, 'S');
    doc.setFontSize(7);
    doc.setTextColor(107, 114, 128);
    doc.text(card.label.toUpperCase(), cx + cardW / 2, y + 6, { align: 'center' });
    doc.setFontSize(14);
    doc.setTextColor(...card.color);
    doc.text(String(card.value), cx + cardW / 2, y + 14, { align: 'center' });
  });
  y += 24;

  // Results table
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text('Detailed Verification Results', margin, y + 4);
  y += 8;

  const tableData = results.map((r, i) => {
    const rec = formatRecord(r, campaign);
    return [
      i + 1,
      rec.phoneNumber,
      `+${rec.countryCode}`,
      rec.countryName,
      rec.whatsappStatus,
      rec.isBusinessAccount,
      rec.profileName || '---',
    ];
  });

  autoTable(doc, {
    startY: y,
    head: [['#', 'Phone Number', 'Code', 'Country', 'Status', 'Business', 'Profile Name']],
    body: tableData,
    theme: 'striped',
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 8,
      cellPadding: 2,
    },
    styles: {
      cellPadding: 2,
      fontSize: 7.5,
      overflow: 'linebreak',
      lineColor: [226, 232, 240],
      lineWidth: 0.1,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      1: { cellWidth: 38, fontStyle: 'monospace' },
      2: { cellWidth: 16, halign: 'center' },
      3: { cellWidth: 36 },
      4: { cellWidth: 30 },
      5: { cellWidth: 18, halign: 'center' },
      6: { cellWidth: 'auto' },
    },
    didParseCell: function (data) {
      if (data.section === 'body' && data.column.index === 4) {
        const val = String(data.cell.raw);
        if (val === 'Registered') data.cell.styles.textColor = [0, 148, 90];
        else if (val === 'Not Registered') data.cell.styles.textColor = [220, 50, 50];
        else data.cell.styles.textColor = [200, 130, 0];
      }
    },
    margin: { left: margin, right: margin },
    didDrawPage: function () {
      addHeader(doc);
      addFooter(doc);
    },
  });

  doc.save(`whatsapp-shield-report-${campaign.id?.substring(0, 8) || 'export'}.pdf`);
}

export function exportAllHistoryCSV(campaigns, phone) {
  if (!campaigns || campaigns.length === 0) return;
  const allResults = [];
  campaigns.forEach(c => {
    if (c.results) {
      c.results.forEach(r => allResults.push({ result: r, campaign: c }));
    }
  });
  if (allResults.length === 0) return;
  const headers = [
    'Phone Number', 'Original Number', 'Country Code', 'Country Name', 'Country Flag',
    'WhatsApp Status', 'Business Account', 'Verified', 'Profile Name',
    'Campaign ID', 'Campaign Date', 'Shield Mode', 'Rate Limiting',
    'Export Date', 'Export Time', 'Application', 'Version',
  ];
  const now = new Date();
  const rows = allResults.map(({ result: r, campaign: c }) => {
    const rec = formatRecord(r, c);
    return [
      rec.phoneNumber, rec.originalNumber, rec.countryCode, rec.countryName, rec.countryFlag,
      rec.whatsappStatus, rec.isBusinessAccount, rec.isVerified, rec.profileName,
      c.id, new Date(c.timestamp).toLocaleString(), c.shieldMode ? 'Enabled' : 'Disabled', c.delayMs + 'ms',
      now.toLocaleDateString(), now.toLocaleTimeString(), APP_NAME, APP_VERSION,
    ].map(escapeCSV).join(',');
  });
  const csv = '\uFEFF' + [headers.join(','), ...rows].join('\n');
  downloadFile(csv, `whatsapp-shield-all-history-${phone || 'export'}.csv`, 'text/csv;charset=utf-8');
}

export function exportAllHistoryJSON(campaigns, phone) {
  if (!campaigns || campaigns.length === 0) return;
  const now = new Date();
  const output = {
    meta: {
      appName: APP_NAME,
      appVersion: APP_VERSION,
      generatedBy: 'WhatsApp Shield Export Engine',
      generatedAt: now.toISOString(),
      exportType: 'Full Account History',
      totalCampaigns: campaigns.length,
      totalRecords: campaigns.reduce((s, c) => s + (c.results?.length || 0), 0),
    },
    campaigns: campaigns.map(c => ({
      id: c.id,
      timestamp: c.timestamp,
      countryCode: c.countryCode,
      shieldMode: c.shieldMode,
      delayMs: c.delayMs,
      totalChecked: c.totalChecked,
      registeredCount: c.registeredCount,
      unregisteredCount: c.unregisteredCount,
      invalidCount: c.invalidCount,
      results: (c.results || []).map(r => {
        const rec = formatRecord(r, c);
        return {
          phoneNumber: rec.phoneNumber,
          country: { code: rec.countryCode, name: rec.countryName, flag: rec.countryFlag },
          whatsappStatus: rec.whatsappStatus,
          profile: { name: rec.profileName, imageUrl: rec.profileImageUrl },
        };
      }),
    })),
  };
  downloadFile(JSON.stringify(output, null, 2), `whatsapp-shield-all-history-${phone || 'export'}.json`, 'application/json;charset=utf-8');
}

export function exportAllHistoryPDF(campaigns, phone, sessionUser) {
  if (!campaigns || campaigns.length === 0) return;
  const now = new Date();
  const totalRecords = campaigns.reduce((s, c) => s + (c.results?.length || 0), 0);
  const totalRegistered = campaigns.reduce((s, c) => s + (c.registeredCount || 0), 0);
  const totalUnregistered = campaigns.reduce((s, c) => s + (c.unregisteredCount || 0), 0);
  const totalInvalid = campaigns.reduce((s, c) => s + (c.invalidCount || 0), 0);
  const avgYield = totalRecords > 0 ? Math.round((totalRegistered / totalRecords) * 100) : 0;

  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 14;

  function addHeader(d) {
    d.setFillColor(15, 23, 42);
    d.rect(0, 0, pageW, 28, 'F');
    d.setFillColor(0, 217, 126);
    d.rect(0, 28, pageW, 1, 'F');
    d.setFontSize(18);
    d.setTextColor(255, 255, 255);
    d.text(APP_NAME + ' - Complete History Report', margin, 12);
    d.setFontSize(9);
    d.setTextColor(180, 180, 180);
    d.text('Full Account Verification Audit', margin, 19);
    d.setFontSize(8);
    d.setTextColor(130, 130, 130);
    d.text(`Generated: ${now.toLocaleDateString()} ${now.toLocaleTimeString()}`, margin, 25);
    d.text(`Page ${d.internal.getCurrentPageInfo().pageNumber}`, pageW - margin - 20, 25);
  }

  function addFooter(d) {
    const y = pageH - 8;
    d.setFillColor(15, 23, 42);
    d.rect(0, y - 2, pageW, 10, 'F');
    d.setFontSize(7);
    d.setTextColor(140, 140, 140);
    d.text(`${APP_NAME} v${APP_VERSION} | Confidential Report | Generated by WhatsApp Shield Export Engine`, margin, y + 3);
    d.text(`Page ${d.internal.getCurrentPageInfo().pageNumber}`, pageW - margin - 15, y + 3);
  }

  addHeader(doc);
  addFooter(doc);

  let y = 36;

  // Account info block
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin, y, pageW - 2 * margin, 18, 2, 2, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin, y, pageW - 2 * margin, 18, 2, 2, 'S');
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);
  doc.text(`Account: ${sessionUser?.name || sessionUser?.number || 'N/A'}`, margin + 4, y + 6);
  doc.text(`Total Campaigns: ${campaigns.length}`, margin + 4, y + 12);
  doc.text(`Report Type: Full Account History`, margin + 80, y + 6);
  doc.text(`Generated: ${now.toLocaleString()}`, margin + 80, y + 12);
  y += 24;

  // Summary cards
  const cards = [
    { label: 'Total Records', value: totalRecords, color: [15, 23, 42] },
    { label: 'Registered', value: totalRegistered, color: [0, 184, 110] },
    { label: 'Not Registered', value: totalUnregistered, color: [239, 68, 68] },
    { label: 'Invalid', value: totalInvalid, color: [245, 158, 11] },
    { label: 'Avg Yield', value: avgYield + '%', color: [0, 217, 126] },
  ];
  const cardW = (pageW - 2 * margin - 4 * 6) / 5;
  cards.forEach((card, i) => {
    const cx = margin + i * (cardW + 6);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(cx, y, cardW, 18, 2, 2, 'F');
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(cx, y, cardW, 18, 2, 2, 'S');
    doc.setFontSize(7);
    doc.setTextColor(107, 114, 128);
    doc.text(card.label.toUpperCase(), cx + cardW / 2, y + 6, { align: 'center' });
    doc.setFontSize(14);
    doc.setTextColor(...card.color);
    doc.text(String(card.value), cx + cardW / 2, y + 14, { align: 'center' });
  });
  y += 24;

  // Campaigns table
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text('Campaign History', margin, y + 4);
  y += 8;

  const tableData = campaigns.map((c, i) => [
    i + 1,
    c.id ? c.id.substring(0, 16) + '...' : 'N/A',
    new Date(c.timestamp).toLocaleDateString(),
    '+' + (c.countryCode || 'N/A'),
    c.shieldMode ? 'ON' : 'OFF',
    String(c.totalChecked || 0),
    String(c.registeredCount || 0),
    String(c.unregisteredCount || 0),
    c.totalChecked > 0 ? Math.round((c.registeredCount / c.totalChecked) * 100) + '%' : '0%',
  ]);

  autoTable(doc, {
    startY: y,
    head: [['#', 'Campaign ID', 'Date', 'Country', 'Shield', 'Total', 'Registered', 'Not Reg.', 'Yield']],
    body: tableData,
    theme: 'striped',
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 8,
      cellPadding: 2,
    },
    styles: {
      cellPadding: 2,
      fontSize: 7.5,
      overflow: 'linebreak',
      lineColor: [226, 232, 240],
      lineWidth: 0.1,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      1: { cellWidth: 38, fontStyle: 'monospace' },
      2: { cellWidth: 24 },
      3: { cellWidth: 20, halign: 'center' },
      4: { cellWidth: 14, halign: 'center' },
      5: { cellWidth: 16, halign: 'center' },
      6: { cellWidth: 20, halign: 'center' },
      7: { cellWidth: 20, halign: 'center' },
      8: { cellWidth: 16, halign: 'center' },
    },
    margin: { left: margin, right: margin },
    didDrawPage: function () {
      addHeader(doc);
      addFooter(doc);
    },
  });

  doc.save(`whatsapp-shield-full-history-${phone || 'export'}.pdf`);
}

export function exportAllHistoryTXT(campaigns, phone) {
  if (!campaigns || campaigns.length === 0) return;
  const now = new Date();
  const lines = [];
  const sep = '='.repeat(72);
  const sep2 = '-'.repeat(72);
  lines.push(sep);
  lines.push('  WHATSAPP SHIELD - COMPLETE ACCOUNT HISTORY');
  lines.push(sep);
  lines.push('');
  lines.push(`  Application:      ${APP_NAME} v${APP_VERSION}`);
  lines.push(`  Export Date:      ${now.toLocaleDateString()} ${now.toLocaleTimeString()}`);
  lines.push(`  Total Campaigns:  ${campaigns.length}`);
  lines.push(`  Total Records:    ${campaigns.reduce((s, c) => s + (c.results?.length || 0), 0)}`);
  lines.push('');
  lines.push(sep2);

  campaigns.forEach((c, ci) => {
    lines.push('');
    lines.push(`  CAMPAIGN ${ci + 1}: ${c.id}`);
    lines.push(sep2);
    lines.push(`  Date:       ${new Date(c.timestamp).toLocaleString()}`);
    lines.push(`  Country:    +${c.countryCode} (${getCountryName(c.countryCode)})`);
    lines.push(`  Shield:     ${c.shieldMode ? 'Enabled' : 'Disabled'} | Delay: ${c.delayMs}ms`);
    lines.push(`  Total:      ${c.totalChecked} | Registered: ${c.registeredCount} | Not Registered: ${c.unregisteredCount} | Invalid: ${c.invalidCount}`);
    lines.push('');
    if (c.results && c.results.length > 0) {
      c.results.forEach((r, ri) => {
        const rec = formatRecord(r, c);
        const icon = rec.whatsappStatus === 'Registered' ? '[WA]' : rec.whatsappStatus === 'Not Registered' ? '[--]' : '[!!]';
        lines.push(`    ${String(ri + 1).padStart(3)}. ${rec.phoneNumber.padEnd(20)} +${rec.countryCode.padEnd(5)} ${icon} ${rec.profileName || '---'}`);
      });
    }
    lines.push('');
    lines.push(sep2);
  });

  lines.push('');
  lines.push(sep);
  lines.push(`  End of Report | ${APP_NAME} v${APP_VERSION}`);
  lines.push(sep);
  downloadFile(lines.join('\n'), `whatsapp-shield-all-history-${phone || 'export'}.txt`, 'text/plain;charset=utf-8');
}
